### ISSUE TITLE
Controller reports wrong values for triggers with LWJGL3

### ISSUE THREAD

**Issue by x44** [libgdx/libgdx#4067] opened 2016-05-05 18:27 UTC
#### Issue details
The left and right triggers are influencing each other. Also there is no axisCode to get the values
for the left and right trigger independently. The only way to get values from any of the triggers
is by calling Controller.getAxis(2), which returns the sum of the left and right trigger value.

#### Reproduction steps/code
Pressing only the LEFT trigger, getAxis(2) returns [0,1].
Pressing only the RIGHT trigger, getAxis(2) returns [0,-1].
Pressing BOTH triggers, getAxis(2) returns 0.

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.2, Windows 7, Xbox 360 Wireless Receiver for Windows.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Quexten** [comment] 2016-05-15 02:10
This is because using the DirectInput API, the Xbox Controller handles the triggers as one axis. The next GLFW release will add support for XInput. Once that's included, this should be fixed.
(This is only true for the Lwjgl 3 backend)

**Comment by Quexten** [comment] 2016-06-16 17:45
I can confirm that updating the Lwjgl version from **3.0.0b** to **3.0.0** fixed this issue in the latest libGDX snapshot (**1.9.4-SNAPSHOT**).

**Comment by x44** [comment] 2016-06-16 19:34
Yes, it works great now.
Thanks for the fix!
This also fixes #3889

**Comment by CreamyCookie** [comment] 2016-08-05 09:42
@x44 You can close this issue.

**Closed** 2016-08-18 09:31 UTC
