### ISSUE TITLE
Problem with mono samples on OSX

### ISSUE THREAD

**Issue by Arcnor** [libgdx/libgdx#3087] opened 2015-05-05 13:02 UTC
I've been having issues with audio in a game I'm making. It works perfectly fine on Windows, but on OSX the audio sounded very deep and low on volume (like it was playing at 10Hz or something).

It seems that the problem is mono samples. Playing any stereo sample works fine, but converting it to a mono sample makes the problem appear again.

Let me know if you need examples, but I've tried with multiple samples from different sources with the same result.

**Comment by Arcnor** [comment] 2015-05-05 13:05
Also, in case anyone asks for my code (which I don't think it's relevant, but just in case):

```java
public class MyGdxGame extends ApplicationAdapter {
	private Sound snd;

	@Override
	public void create () {
		snd = Gdx.audio.newSound(Gdx.files.internal("testMono.wav"));
		snd.play();
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(0, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
	}
}
```

**Comment by MobiDevelop** [comment] 2015-05-05 13:11
The audio file is probably more important than the code for this... I've not noticed any issues with sound playback on OSX.

**Comment by Arcnor** [comment] 2015-05-05 21:32
You can check any MP3 at github.com/Arcnor/pixel-dungeon-gdx,
android/assets folder.

I tried converting them to WAV just in case, but got the same result.

**Comment by MobiDevelop** [comment] 2015-05-06 13:27
They seem to work fine for me.

**Comment by Arcnor** [comment] 2015-05-06 21:56
That's very strange. I've tried with two different Macs, one with OSX 10.9, the other with OSX 10.10, and one being a Macbook Pro and the other a Mac Pro. So, as I said, it's very strange that it doesn't fail for you.

I've debugged a bit, but parameters passed to LibGDX are directly passed to the underlying OpenAL libraries, so I'm not sure how to continue from there...

**Comment by MobiDevelop** [comment] 2016-04-08 15:35
Unable to reproduce and a lack of others indicating that this is an actual issue for them, so I am going to close this out.

**Closed by MobiDevelop** 2016-04-08 15:35 UTC
