### ISSUE TITLE
Flicker

### ISSUE THREAD

**Issue by Oyatsumi** [libgdx/libgdx#3321] opened 2015-08-03 19:02 UTC
Hello devs,

First of all I apologize if I'm making a mistake posting it here.
However, recently I've updated the libgdx (from 1.4.1 to 1.6.1) without changing my game code.
I noticed that the bitmaps and the life bars started to flicker such as in:
http://www.mediafire.com/watch/42w5tb3dnrw2skk/ScreenCapture_03-08-2015_15.52.18.wmv
(PS.: After recording this video I noticed that it does not actually flicker when I'm recording the screen from my computer).
Therefore, I used my cellphone to record it (bad quality - I hope you can notice it, it happens when they are displaced). It did not happen in version 1.4.1.
https://drive.google.com/a/id.uff.br/file/d/0BxJH7y8eF0sjMGRPYUNxcE9QTU0/view?usp=sharing

The life bar is being drawn like that:
	public boolean drawLifeBar(SpriteBatch batch){
		if (this.getMaxHP() == 0) return false;
		//vars
		final byte lifebarWidth = 50, lifebarHeight = (byte) greenlifebar.getHeight(), paddinGdown = 18;
		final byte lifebarwidth2;
		//vars
		batch.draw(blackdotlife, this.x + (tilesPixelSize - lifebarWidth)/2 - 1, this.getNamePosY() - 1 + paddinGdown, lifebarWidth + 2, lifebarHeight + 2);
		lifebarwidth2 = (byte) ((lifebarWidth*this.getCurrentHP())/this.getMaxHP());
		//red bar draw
		if (lifebarwidth2 <= lifebarWidth/5) batch.draw(redlifebar, this.x + (tilesPixelSize - lifebarWidth)/2, this.getNamePosY() + paddinGdown, lifebarwidth2, lifebarHeight);
		else batch.draw(greenlifebar, this.x + (tilesPixelSize - lifebarWidth)/2, this.getNamePosY() + paddinGdown, lifebarwidth2, lifebarHeight);
		return true;
	}

I've already tried to cast the positions of the sprite to integers, but that did not stop the flickering.
Besides, using linear interpolation also did not change anything.

Here is an example of how it was in 1.4.1:
https://www.youtube.com/watch?v=jpmRXUH2qFU

PS.: I'm running it in the same computer with same specs in both versions.
Is this expected to happen?
Thank you so much.

**Comment by xoppa** [comment] 2015-08-03 20:06
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker
If you need help debugging your code you might want to give the forum or irc a try instead. See also: https://github.com/libgdx/libgdx/wiki/Getting-Help. If you actually found an issue with libgdx, then please include the [sscce](http://sscce.org/): we can't fix it if we can't reproduce it.

Btw, please take some time to format your post: https://guides.github.com/features/mastering-markdown/

**Comment by xoppa** [comment] 2015-08-18 18:27
Closing this, will reopen if you provide the required information.

**Closed by xoppa** 2015-08-18 18:27 UTC
