### ISSUE TITLE
Increase source level in gdx-setup

### ISSUE THREAD

**Issue by nooone** [libgdx/libgdx#3244] opened 2015-06-30 08:55 UTC
AFAIK the android build tools, as well as GWT support Java 7 these days. A project generated by gdx-setup is still set to 1.6 though. For example [here](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/android/build.gradle#L76).

IMHO it should be safe to set it to 1.7. @MobiDevelop says that he already works with 1.7 for a while and didn't run into problems.

**Comment by FyiurAmron** [comment] 2015-06-30 10:48
ain't this a duplicate of https://github.com/libgdx/libgdx/issues/1662 ? Also, http://stackoverflow.com/questions/7153989/java-7-language-features-with-android & the fact that AFAIR libGDX supports (at least in theory) up to API Level 8 - would Java 7-styled code be runnable on API Level 8-era machines?

**Comment by nooone** [comment] 2015-06-30 11:19
Kind of a duplicate, yes. Times have changed though since this other issue. @MobiDevelop already pointed out that GWT 2.6.0 (which we are using now) supports Java 7. The Android Build Tools seem to do so since version 19.

AFAIK, all Java 7 language features, but try-with-resources, are working as well on older android versions. Try-with-resources works only on API 19+, because the AutoClosable interface was missing.

**Comment by MobiDevelop** [comment] 2015-06-30 23:43
I think we'd have to switch to GWT 2.7.0 to be able to actually use Java 7
language features there. Unfortunately, GWT 2.7.0 has some issues that make
release builds incredibly slow.

Not a show stopper, but something to note.

**Comment by nooone** [comment] 2015-07-01 05:33
Only for release builds though? That would probably not be a huge problem.

I haven't tried it myself yet, but I read everywhere that 1.6.0 supports Java 7 language features. What exactly do you mean by "actually use Java 7"? What's not working with GWT 2.6.0?

**Comment by Tom-Ski** [comment] 2015-07-01 12:21
Not just release builds from my tests.

**Comment by Tom-Ski** [comment] 2015-08-19 09:34
Going to leave this 'til we can update GWT.

**Closed by Tom-Ski** 2015-08-19 09:34 UTC
