### ISSUE TITLE
Controller disconnect crashes with LWJGL3

### ISSUE THREAD

**Issue by saibotd** [libgdx/libgdx#3889] opened 2016-02-28 08:34 UTC
#### Issue details

When disconnecting a controller, while the game is running, crashing occurs.
#### Reproduction steps/code
- Enable LWJGL3
- Connect at least one gamepad
- Call Controllers.getControllers() within your Application to initialize
- Disconnect the controller
#### Version of LibGDX and/or relevant dependencies

LibGDX 1.9.2 on Windows 10. Using a MS wireless receiver and Xbox 360 controller.
#### Stack trace

http://pastebin.com/1TmNmbLH
#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by code-disaster** [comment] 2016-02-28 12:13
I can't reproduce this crash on my own PC or with Bootcamp on a MBP, but I've seen very similar crashs/callstacks happen on a Surface Pro 4, one without *any* controllers attached. Without further proof I currently suspect some USB-related, maybe even some power-saving issue. Google searches dug out different results though, without a clear solution.

**Comment by byron-conroy** [comment] 2016-04-11 12:22
I might be running into a similar problem, I have had 3 crashes since switching to the lwjgl3 backend.

Once occurred due to disconnecting / reconnecting the controllers, though the others happened when I was closing the application by clicking close button in the menu bar.

Here are the 3 error report files:

http://pastebin.com/rTxZTEyR
http://pastebin.com/RxF47VxC
http://pastebin.com/Sa92gF2z

**Comment by x44** [comment] 2016-05-05 18:06
Happens here, too. Windows 7, LibGDX 1.9.2, Xbox 360 Wireless Receiver for Windows.
After disconnecting the controller it takes about 15 second till the crash.
When reconnecting the controller it does not crash.

**Comment by x44** [comment] 2016-06-16 19:37
Does not happen anymore with libGDX snapshot (1.9.4-SNAPSHOT).

**Closed** 2016-12-10 18:15 UTC
Labels: LWJGL3
