### ISSUE TITLE
[iOS] life cycle: resize() is called before create()

### ISSUE THREAD

**Issue by burakkurkcu** [libgdx/libgdx#3850] opened 2016-02-17 06:55 UTC
This could be relative to #3789 but after upgrading from 1.7.2 to 1.9.1 on iOS, after application start, resize() is called before create() which causes initialization errors due to Gdx.app is null.

So it seems now the life cycle is:
Application start -> resize() -> create() -> ...

Instead of:
Application start -> create() -> resize() -> ...

**Comment by Darkyenus** [comment] 2016-02-17 14:33
#3709 fixes this

**Comment by manuelbua** [comment] 2016-03-04 17:55
I can confirm this behavior: it looks like we receive a `resize` call before reaching the `draw` [method](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java#L307) that invokes `create` and `resize` in the correct order.

I can see this quite hacky way to *create* the application is [untested](https://github.com/libgdx/libgdx/blame/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java#L307), i'm not sure what's involved and why this is needed to occur right during drawing operations, anyone know more?

**Comment by Darkyenus** [comment] 2016-03-04 18:50
From my research and understanding: iOS logically decouples update() and render(), where only render() can access (by default) GL context. In libGDX however, all ApplicationListener methods can use OpenGL calls, so these calls have to happen when libGDX's GL context is active. It can be forced to be active (which is used for pause/resume, IIRC) but I am not quite sure what are the rules for this.

iOS backend would deserve a cleanup IMO, but it seems that no one from core contributors currently has time to go over iOS related PRs, so it maybe now isn't the right time to do that. In my projects I'm using somewhat modified version of this backend and I'm considering cleaning it up myself, implementing missing features (accelerometer, compass, etc.) and releasing it separately, with a hope that it will get merged back into libGDX some time in the future when it is complete and tested. Would anyone be interested in using or testing it?

**Closed** 2016-03-10 19:59 UTC
Labels: ios
