### ISSUE TITLE
VBO indexing GL_LINES style

### ISSUE THREAD

**Issue by azlax** [libgdx/libgdx#3515] opened 2015-10-27 18:29 UTC
Say the vertices and indices indexing below, all while respecting the max of 32k vertices possible for a mesh:

![Image](http://s17.postimg.org/raq2q5167/verticesindices.png)

Couldn't we change the type of the indices array passed to the mesh from type short to int. Defining triangles with GL_LINES in VBO indexing style needs 5 indices per triangle and therefor quickly busts the indexes of a short[].

short: The short data type is a 16-bit signed two's complement integer. It has a minimum value of -32,768 and a maximum value of 32,767 (inclusive). 

32k vertices in this meshing fashion can create nearly ~ 32k triangles, indexing it needs 5 indices per triangle = 160k indices array size

Thanks for checking this,

**Comment by xoppa** [comment] 2015-10-27 18:51
There's no limit of 32k on the amount of indices, your math is wrong. Anyways, please make sure to carefully this read this (as you were asked when opening this issue):
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md
Closing, because duplicate of #3386

**Closed by xoppa** 2015-10-27 18:51 UTC

**Comment by azlax** [comment] 2015-10-27 22:01
I was accessing a short[] index with short variable.. accessing it with an int allows me to build a bigger short[]. My bad, got to sleep sometimes hehe
