### ISSUE TITLE
Sprite.getColor.a is equal to 0.99607843 instead of 1. Sprite.setAlpha(1) does not work.

### ISSUE THREAD

**Issue by SasLuca** [libgdx/libgdx#3680] opened 2015-12-30 08:55 UTC
If I create a new Sprite (sprite = new Sprite(new Texture(Gdx.files.internal("badlogic.jpg")))) by default sprite.getColor().a should be 1 but it is instead 0.99607843. Also, if I try sprite.setAlpha(1) and sprite.getColor.a = 1 and sprite.setColor(new Color(1,1,1,1) then sprite.getColor().a is still 0.99607843 instead of 1.

**Comment by xoppa** [comment] 2015-12-30 09:45
duplicate of #2593

**Closed by xoppa** 2015-12-30 09:45 UTC
