### ISSUE TITLE
Switching to fullscreen causes CPU to spike

### ISSUE THREAD

**Issue by Anti-Alias** [libgdx/libgdx#5005] opened 2017-12-03 21:00 UTC
#### Issue details
I am making an LibGdx build using the Lwjgl3 backend 'gdx-backend-lwjgl3'.
I am using Kotlin.

When I run the desktop application (after enabling vsync) in windowed mode, the CPU is about 1-2%.
When I switch it to fullscreen with an Alt+Enter toggle I created, the task manager says that
the java process is taking up to 50%. I have a multi-monitor desktop, so I can look at both.
Also, when in fullscreen, the FPS seems unlimited, as the logger show it going above 4,000
despite the fact that my Lwjgl3ApplicationConfiguration has vsync set to true.

If I force it to use vsync after it goes to fullscreen (Using Gdx.graphics.setVsync(true) ), the logger says that the fps is at 60, but the CPU utilization does not go down.

When the is windowed, but stretched to fill most of the screen, the cpu utilization is still low.
This only happens when it goes to fullscreen  or starts in fullscreen.

#### Reproduction steps/code
1) Clone build  here: https://github.com/Anti-Alias/pokemaker-core

2) Run application in cmd or git bash using:
gradlew desktop:run
or
./gradlew desktop:run

3) Open task manager on a Windows machine and note the cpu usage.

3) Press Alt+Enter and notice change in task manager's cpu usage for that java process.
You will need at least two monitors to test this.

#### Version of LibGDX and/or relevant dependencies
LibGdx version:     1.9.7
gdx backend:        gdx-backend-lwjgl3 : 1.9.7

#### Please select the affected platforms
Windows 10

**Comment by Anti-Alias** [comment] 2017-12-03 21:05
I also want to point out that I am using an Nvidia Gtx 1070 with updated drivers according to my device manager.

CPU is an Intel(R) Core(TM) i5-6600K CPU @ 3.5GHz 3.50 GHz

**Comment by crykn** [comment] 2020-08-30 18:28
Duplicate of #5826.

**Closed by crykn** 2020-08-30 18:28 UTC
Labels: desktop

**Comment by Anti-Alias** [comment] 2020-12-28 16:30
Hello, those from 3 years ago.
So, I am nearly certain that this is not a LibGDX issue as I was able to replicate this by compiling and running the GLFW examples here: https://github.com/glfw/glfw

That being said, I'm going to report on some interesting findings since I spent a few nights banging my head against a wall to figure out what was going on.
Don't want this to feel like a total loss.
Long story short, I found out that NVidia's implementation of SwapBuffers uses a yielding spinlock when VSync is enabled.

https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/103908/vsync-spin-lock-8600m-25896-xp-sp3/
https://community.khronos.org/t/kernel-mode-cpu-usage-is-high-in-opengl-rendering/62800 (Call stack has lines starting with "nv", so I assume it's an nvidia driver)
https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/110506/nvoglntdlldrvcopycontext-take-a-sleep/
https://www.reddit.com/r/opengl/comments/7cv62w/high_cpu_usage_using_nvidia_card_low_cpu_usage/ (Source: ___some_guy :))


I also did some measurements:

First, I closed all programs and fired up my game.
When I measured the temp of my CPU when running my game in windowed mode, it hovered around 40°C. Basically idle. CPU usage was around 1-3% for my game.

When I jumped to fullscreen, it hovered to around 50°C. CPU usage was around 20-30% for my game.

So, clearly the CPU was doing enough work to warm the CPU a tad.
It wasn't just a matter of Windows reporting CPU usage incorrectly.


Here is where things get interesting, though.
When I stress test my CPU in CPU-Z, the CPU usage of my game in fullscreen drops to 1-2% while CPU-Z uses about 98-99%.
My suspicion is that since the CPU is being sufficiently used by more than one process, Nvidia's driver has something to actually yield to.
In the previous example, when nothing else was going on, the scheduler probably had less to yield to and was likely just switching back in.
This meant that while it didn't take processing power away from my machine, it still strained the CPU unnecessarily.
Kind of a bummer if you're a laptop user since you need all of the battery life you can get...

I have a half-solution to this problem:
When in fullscreen, I force my application to Thread.sleep(${msRemaining}-${aFewMS}) at the end of my game loop.
This drops the CPU usage to about 5-7% and seems to work fine regardless of the refresh rate of the monitors I test this on, 60hz and 144hz respectively.
I can drop the CPU usage further my making ${aFewMS} smaller, but that runs the risk of making the app stutter more since Thread.sleep() isn't all that accurate.
Basically, the less time the driver has to SwapBuffers, the better.

¯\_(ツ)_/¯
