### ISSUE TITLE
GlyphRun: Final white space omitted

### ISSUE THREAD

**Issue by ViktorMihhailov** [libgdx/libgdx#3134] opened 2015-05-15 08:53 UTC
LibGdx 1.6.0 font markupEnabled set to true
<h4>1.Incorrect color if alpha channel missed</h4>
<p>
HTML style color tag without alpha channel produces incorrect color. Color tag <code>[#00FF00]</code> instead of green color gives blue.
</p>

<h4>2.First whitespace before color tag is omitted</h4>
<p>
If font is generated with <code>FreeTypeFontGenerator</code> then first whitespace before color tag disappears.
</p>
Code below reproduces all described issues. 

    import com.badlogic.gdx.ApplicationAdapter;
    import com.badlogic.gdx.Gdx;
    import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
    import com.badlogic.gdx.graphics.GL20;
    import com.badlogic.gdx.graphics.g2d.BitmapFont;
    import com.badlogic.gdx.graphics.g2d.SpriteBatch;
    import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;
    import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.FreeTypeFontParameter;
    
    public class BitmapFontMarkupBugExample extends ApplicationAdapter {
        SpriteBatch batch;
        BitmapFont font;
        String alphaChannelBug;
        String whiteSpaceBug;
        
        public void create () {
            batch = new SpriteBatch();
            
            FreeTypeFontParameter param = new FreeTypeFontParameter();
            param.size = 26;
            font = new FreeTypeFontGenerator(Gdx.files.internal("data/arial.ttf")).generateFont(param);
            font.getData().markupEnabled = true;
            
            alphaChannelBug = "1.Alpha channel bug:\n \n"
                    + "[GREEN]OK green color [['GREEN'] tag;\n"
                    + "[#00FF00FF]OK green color [['#00FF00FF'] tag;\n"
                    + "[#00FF00]BUG green color [['#00FF00'] tag";
            
            whiteSpaceBug = "2.White space bug:\n \n"
                    + "OK Sphinx of black quartz\n"
                    + "BUG Sphinx [RED]of black quartz";
        }
    
        public void render () {
            Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
            batch.begin();
            
            
            font.draw(batch, alphaChannelBug, 100, 400);
            font.draw(batch, whiteSpaceBug, 100, 200);
            
            batch.end();
        }
    
        public static void main (String[] args) throws Exception {
            new LwjglApplication(new BitmapFontMarkupBugExample());
        }
    }

**Comment by MobiDevelop** [comment] 2015-05-29 04:26
The color piece seems to be fixed already. Whitespace issue looks to still exist.

**Comment by davebaol** [comment] 2015-05-29 08:51
Quickly looked into the code and I think that the white space issue has nothing to do with color markup.
It looks like the problem is related to a glyph run ending with a white space (a color tag just determines a new run).

**Comment by MobiDevelop** [comment] 2015-05-29 12:26
That was my conclusion as well.

**Comment by davebaol** [comment] 2015-05-29 14:34
Ok, I took the liberty to edit the title and add the bug label.

**Comment by davebaol** [comment] 2015-06-25 15:11
This should now be fixed by #3217 which has been merged

**Closed by davebaol** 2015-06-25 15:11 UTC
Labels: bug
