### ISSUE TITLE
Exception on linux running tests with external monitor

### ISSUE THREAD

**Issue by billy1380** [libgdx/libgdx#3527] opened 2015-11-01 23:18 UTC
I get this exception

``` java

Exception in thread "LWJGL Application" java.lang.ExceptionInInitializerError
    at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:510)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:118)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:954)
    at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
    at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
    ... 2 more

```

when running `LwjglTestStarter` on my laptop with an external monitor plugged in.

I have unplugged the monitor and used the laptop (built in) monitor and "randomly selected" tests seem to work as expected.

**Comment by billy1380** [comment] 2015-11-02 21:06
I am pretty sure this is not a libgdx problem and probably LWJGL problem... but just going to leave `xrandr -q` results here anyway
```
xrandr -q
Screen 0: minimum 8 x 8, current 1920 x 1200, maximum 16384 x 16384
eDP-1-0 connected
   3840x2160     60.00 +
   2048x1536     60.00  
   1920x1440     60.00  
   1856x1392     60.01  
   1792x1344     60.01  
   1920x1200     59.95  
   1920x1080     59.93  
   1600x1200     60.00  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1280x1024     60.02  
   1440x900      59.89  
   1280x960      60.00  
   1360x768      59.80    59.96  
   1152x864      60.00  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   960x600       60.00  
   960x540       59.99  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   800x512       60.17  
   700x525       59.98  
   640x512       60.02  
   720x450       59.89  
   640x480       60.00    59.94  
   680x384       59.80    59.96  
   576x432       60.06  
   512x384       60.00  
   400x300       60.32    56.34  
   320x240       60.05  
VGA-1-0 disconnected
DisplayPort-1-0 disconnected
HDMI-1-0 connected primary 1920x1200+0+0 518mm x 324mm
   1920x1200     59.95*+
   1600x1200     60.00  
   1680x1050     59.88  
   1400x1050     59.95  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1360x768      59.80  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.08    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    60.00  
   720x400       70.08  
HDMI-1-1 disconnected
``` 

Is there a way to specify the display id via a command line variable?

**Comment by Tom-Ski** [comment] 2015-11-04 07:22
You should test this with a raw Lwjgl app.

**Comment by badlogic** [comment] 2015-11-16 23:40
I plan on finishing the LWJGL 3 backend over Christmas, which should fix this ipand related issues. Will leave it open for now.

**Comment by Tucura** [comment] 2016-10-25 11:10
Is this Issue still relevant? I also have the problem like billy1380.

`Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp
Exception in thread "LWJGL Application" java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:558)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:122)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:954)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 2 more
AL lib: (EE) alc_cleanup: 1 device not closed`
I followed the 'Getting started' instruction but the window with the image badlogic.png wont show up.
I'm developing in Netbeans on Arch Linux with to monitors connected.

Is there already a work around or fix for this? Disabling my second monitor didnt help. Take care

**Comment by badlogic** [comment] 2016-12-10 18:40
You can try the LWJGL3 backend. This appears to be a bug in LWJGL2 which does not get any updates anymore.

**Closed by badlogic** 2016-12-10 18:40 UTC
