### ISSUE TITLE
No supported display modes on Linux desktop

### ISSUE THREAD

**Issue by IoriBranford** [libgdx/libgdx#5230] opened 2018-05-23 02:33 UTC
#### Issue details
I started a new project for Android/desktop. When running the desktop application on Linux with default configuration, it isn't able to find a supported display mode.

![20180522_161314](https://user-images.githubusercontent.com/7191895/40399723-d51f67cc-5df3-11e8-8fd8-4f67d84d2917.jpg)

gdx's display modes:
```
1920x1200, bpp: -1, hz: 50
1920x1080, bpp: -1, hz: 53
1600x1200, bpp: -1, hz: 60
1280x1024, bpp: -1, hz: 61
1280x720, bpp: -1, hz: 63
1152x864, bpp: -1, hz: 66
1024x768, bpp: -1, hz: 67
800x600, bpp: -1, hz: 69
720x576, bpp: -1, hz: 71
720x480, bpp: -1, hz: 72
640x480, bpp: -1, hz: 73
1680x1050, bpp: -1, hz: 76
1440x900, bpp: -1, hz: 77
1366x768, bpp: -1, hz: 78
1280x800, bpp: -1, hz: 79
```
don't match what's actually available as reported by xrandr:
```
HDMI-0 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+  59.88  
   1920x1080     60.00    59.94    50.00    23.98    60.05    60.00    50.04  
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
```
Trying to force the one matching display mode, 1600x1200@60hz, doesn't help. Disabling fullscreen doesn't help.

OS: Xubuntu 18.04
Graphics card: NVIDIA GeForce GTX 750 Ti
Driver version: 396.24
IDE: Android Studio 3.1.2

#### Reproduction steps/code
1. Create new desktop/Android project with latest gdx-setup
1. Open project in Android Studio
1. When asked to update Gradle plugin, update
1. Make any tweaks necessary for successful build
    1. Disable Configure on Demand in project settings
1. Try to run or debug DesktopLauncher.main()

The application tries to set an unknown or non-standard display mode which the monitor may or may not support.

#### Version of LibGDX and/or relevant dependencies
        gdxVersion = '1.9.8'
        roboVMVersion = '2.3.3'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'

#### Please select the affected platforms
- [x] Linux

**Comment by shatterblast** [comment] 2020-03-24 18:42
@IoriBranford The current form of LWJGL 3 of LibGDX 1.9.10 and what comes after should fix this issue.  LWJGL 2 does not support all modern devices.  LWJGL 3 supports hardware from 2012 and after, when the 64-bit leap in architecture happened with graphics devices.  If you need to support something prior to 2012 for some reason, then LWJGL 2 may still serve a purpose for you.  Otherwise, please, close this issue.

Thank you.

**Comment by crykn** [comment] 2020-08-28 16:22
Closing this, as there was no response from the original author and the problem is most likely fixed by LWJGL 3, the recommended backend.

**Closed by crykn** 2020-08-28 16:22 UTC
