### ISSUE TITLE
Large delta in the second return after pause/resume with some delay in render (Android)

### ISSUE THREAD

**Issue by newMemberHub** [libgdx/libgdx#7419] opened 2024-07-16 06:46 UTC
#### Issue details
I work on libgdx for pause and resume, but when resume I faced issue with deltatime and delay in rendering in resume.
- The first returned deltatime is 0.
- The next one is 2.1.
- From the third one, the deltatime is normal.
About the 2.1s depends on how long you was pending in pause status. If pause time is large, the deltatime will be same duration.
I checked with latest version 1.12.1 and on Android run Android 13.

#### Reproduction steps/code
With simple code for printing the delta in render(deltatime) function and will capture the issue.
- The deltatime in render function will be 0 (first time) and large time depends on how long you come back to resume state. 
- Besides, the game have some delayed in rendering.

#### Version of libGDX and/or relevant dependencies
I am using libgdx 1.12.1 and run with Android that run Android OS 13.

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by TCreutzenberg** [comment] 2024-07-18 13:36
The delta should be exactly the time difference between the renders, so what you are experiencing is exactly what should happen.
This raw delta can be used and is needed for other purposes (track loading time, give hint s for lags, etc.), so it cannot be auto-adjusted as you want it to.
What you most likely want to do is to limit the delta for your game loop, i.e. instead of using the "raw" delta use e.g. float gameLoopDelta = Math.min(1/30f, delta);

**Comment by newMemberHub** [comment] 2024-07-18 15:54
When returned resume status from pause status, the first deltatime is 0, but the second deltatime is large (from 0.9 to 2.1 depends on pause time). From the third deltatime, it returned normal number.
About the first deltatime, it is 0 because of [this fix](https://github.com/libgdx/libgdx/issues/1196). Then I think it is the issue related to deltatime, it should be normal number from the second time, not third time.

**Comment by obigu** [comment] 2024-07-20 10:02
Delta time reporting after pause varies by platform and best approach not to have to worry about is to follow @TCreutzenberg suggested approach. 

What you are reporting though is not expected behaviour and, if confirmed, would deserve some investigation. @newMemberHub Can you confirm that this behaviour occurs on a new empty Android project?

**Comment by newMemberHub** [comment] 2024-07-30 16:07
This issue appear when interstitial ads appeared. When interstitial ads showed, the status will be lost focus (paused). After dismissing the ads, the status will be resumed. And at that time, the issue happened. 
In another normal case, no issue happened.

**Comment by obigu** [comment] 2024-07-30 16:14
Ok, considering we don't have a reproducible example and that it only occurs when losing focus with a specific Ads SDK I'll assume the lag is caused by the SDK (maybe it loads a new ad after dismissal of the old one causing a slow 2nd or 3rd frame after resume). Closing the issue for now.

**Closed by obigu** 2024-07-30 16:14 UTC
