### ISSUE TITLE
Mesh.dispose() does not free memory on Linux

### ISSUE THREAD

**Issue by dns2utf8** [libgdx/libgdx#2926] opened 2015-03-10 09:22 UTC
Hi all

I am having trouble with a memory leak on the Linux Platform. My Programm generates a lot of Mesh.
So to save memory, it calls dispose on the unneeded mesh objects.
This works perfectly on Windows, but it has no effect on Linux.

After some debugging I gave up. If I had to guess, I would search the C++ parts, but I was unable to make sense there.

Regards dns2utf8

**Comment by xoppa** [comment] 2015-03-10 18:16
Please provide the info required to reproduce the issue you're reporting, like a [sscce](http://sscce.org) and the steps you took to verify that it is indeed a memory leak caused by the Mesh class. I'm afraid that I won't be able to test on linux atm, but someone else might be able to reproduce the issue and debug it.

**Comment by xoppa** [comment] 2015-03-22 20:11
Closing this, will reopen if you provide the required information to reproduce the issue.

**Closed by xoppa** 2015-03-22 20:11 UTC
