### ISSUE TITLE
[Android] TextField and OnScreenKeyBoard error ! 

### ISSUE THREAD

**Issue by saruno** [libgdx/libgdx#2491] opened 2014-10-23 10:09 UTC
Hi,
I using TextField to input string. When i use SamSung (Samsung Galaxy S3) keyboard, the keyboard always pop. But when I type anything, it don't display any letters. The problems seems to appear only when "predictive text" is enabled. Please, fix it. It is really uncomfortable :(

**Comment by bachtrong43** [comment] 2015-01-23 03:22
I guess it's the same issue as https://github.com/libgdx/libgdx/issues/2604
That is really uncomfortable

**Comment by badlogic** [comment] 2016-01-05 17:19
Duplicate of #2604, closing this out.

**Closed by badlogic** 2016-01-05 17:19 UTC
Labels: android, bug
