### ISSUE TITLE
Glyph class xOffset,yOffset,width/height are integers, should be float

### ISSUE THREAD

**Issue by azakhary** [libgdx/libgdx#4635] opened 2017-03-06 09:38 UTC
Hi,

I have just generated font file with [literra](http://kvazars.com/littera/)  which is a great tool, and bitmaps look better quality than with others. Thing is, it has high precision for offsets and sizes of glyphs so they are float. And libgdx Glyph class stores them as int. As a result, the precision is lost, and when you add antialiasing in the mix, the typograhy does not look very good. 
Is there any reason this values are int? can we change this to float?

We are releasing a big title next week, and I would love for it to have good typography.

@NathanSweet Obi-Wan?

<img width="266" alt="screen shot 2017-03-06 at 1 37 09 pm" src="https://cloud.githubusercontent.com/assets/2115888/23604374/1447969c-0272-11e7-810f-0c492d235a40.png">
I am not sure if it's easy to notice the issue if not familiar with this language. Let me know if english version will help better.

**Comment by xoppa** [comment] 2017-03-06 18:52
duplicate of #2960

**Closed by xoppa** 2017-03-06 18:52 UTC
