### ISSUE TITLE
Extract a shared dependency for libgdx utility classes to reduce coupling

### ISSUE THREAD

**Issue by pakoito** [libgdx/libgdx#2793] opened 2015-01-31 14:05 UTC
I just wanted to add this promise into the tracker, where you would extract some common functionality like the Collections and Reflection helpers geared towards mobile and put them in a separate reusable project by modules like libgdx-ai in order to reduce their complete dependency on libgdx.

http://www.reddit.com/r/gamedev/comments/2u8ytc/gdxai_150_released/co6b3hx

**Comment by vaxquis** [comment] 2015-02-01 12:14
Frankly, that's one of my main problems with libGDX at the moment - it tries to be "everything in one", in result being barely extendable or modifiable without recompiling the whole artifact from the scratch and the core modules are coupled together so tightly it's impossible to fix even the simplest of bugs without either commiting a PR patch to trunk & waiting for a pull (which can take up to 1 year AFAIK) or rewriting the entire lib... the private/protected/public members are mixed, making extending a real PITA, while at the same time Gradle dependencies management combo'ed with Android APK compiler essentially prevents "overriding" single class files by requiring an artifact to be included as a whole, with no option to e.g. use the package/class name in your project to "disable" the core class and replace it with your own; javac compiler works OK, just providing duplicate files in JAR, allowing to delete them with post-compile hook.

The only working solution for me was to manually create a lib with updated files, and manually update it every time new major version comes out. Yugh.

What I'm virtually dreaming of is a set of *interfaces* or abstract base classes with implementations instead of current concrete classes, allowing easy decoupling of all the basic libGDX functionalities - math/vector, 3D OpenGL interface, audio, 2D interface, particle effects, data input helpers (JSON, XML etc).

Well, time to get back to reality.

**Comment by badlogic** [comment] 2015-02-02 16:19
I hear you, and we had some efforts to decouple things (e.g. move things out into "extensions", etc.). We also have interfaces in places where they make sense (where you say we don't, e.g. vectors, GL, batchers, etc.). I'd be very curious for a link to a library that you can fix without recompiling it.

End of the day it's a question of resources.

**Comment by vaxquis** [comment] 2015-02-02 21:58
Frankly, I say there ain't interfaces because there ain't... While `Vector` is a interface, it can't be used for nothing, because everything depends on Vector3/Vector2 implementations, and there *ain't* an interface for them - making switching core classes to different implementation with conforming interface (e.g. with optimized operations) not possible. Similarly, while there is an interface for e.g. ShaderProvider, Shader & GL20, there's no interface for Matrix3/4, RenderContext, ModelBatch or Renderable, the last one being a class with public fields, essentially making an interface for it impossible without rewriting entire 3D code.

As to fixing lib without recompiling - it's extremely easy if the library has code points that allow easy class extension or code pluging-in; e.g. I was able to create a wicked fix for a wicked bug in Bullet just because a few versions before (2.72 AFAIR) EC created a couple of hooks (gContactAddedCallback, gContactProcessedCallback & gContactDestroyedCallback), allowing me to filter those contacts later on... it was essentially unfixable without manual recompilation in the versions prior to that (i.e. 2.0), because it didn't have all that hooks coded. Same applies to any other lib - if I can replace a fixed element by creating a subclass or reimplementation and plug it into existing lib code - everything's completely fine. If I can't - it's a strong signal that the lib's internals are too strongly coupled.

Still, I completety understand & empathize with the "resource" part.

**Comment by NathanSweet** [comment] 2015-02-02 22:05
It is over design to make everything abstract before there is a need for customization. It's as bad as premature optimization. @vaxquis You are hijacking this issue with your ranting walls of text.

Collections are useful outside of libgdx and could be separated nicely. The reflection utilities are for GWT, I'm not sure they can be easily separated.

**Comment by badlogic** [comment] 2015-02-02 22:23
Interfacing Matrix3/4 does not make a lot of sense. If you want to extend Matrix3/4 it's likely you want to override only a handful of methods with optimized/specialized versions and reuse the rest of the methods. In 99.9% of cases users of the lib will not ever want to touch any code in Matrix3/4. By interfacing it, the majority of users would pay a performance penalty (vcall) on something that is invoked at a very high frequency. I don't think that's a good trade-off at all. The same is true for Vector2/3.

If you see public members then you can assume that we have a reason for them existing. In 99% of cases the reason is Dalvik, which imposes a penalty of field access via (virtual) getters/setters. Using public fields in those places can be a sensible option if these fields get accessed a lot per frame, as is the case with Renderable and other struct-likes.

There's a case to be made for interfacing RenderContext and ModelBatch. As Nate said, preemptively interfacing is something we do not do. As with SpriteBatch, it becomes clear after a while what should be interfaced and what shouldn't based on usage patterns that we observe over time in our own code and the code of our users. Trying to anticipate this from the inception of an API like the 3D API is a tough cookie to crack, and you'll always have some unhappy people one way or the other.

We do employ the visitor pattern you cited in Bullet (along with other patterns) in a lot of places in libGDX, be it scene2d or box2d. There's places where it makes sense. And there's places where it doesn't make sense. 

If you have concrete suggestions for decoupling oportunities i'm all ears. Just dropping the names of a few classes is not enough though. One has to analyse:

* concrete usage scenarios (decoupling for the sake of decoupling is time wasted)
* additional maintainance burden vs. #users that will benefit from it
* impact on performance

**Comment by FranciscoEstevez** [comment] 2015-02-02 22:30
My suggestion is the issue linked atop of the request, mostly about libgdx-ai depending on the whole library.

I believe we discussed this two years ago, I was not allowed to leverage the library on the apps our company is working on because of that overhead. I'd love to use your collections, OGL wrappers and such without bringing the rest of it.

I understand that resource allocation is the issue here, so maybe one step at a time, freeing libgdx-ai would be a good starting point :)

**Comment by badlogic** [comment] 2015-02-02 22:35
Putting the utils package into a separate project is totally feasible and a good idea imo. The GL wrappers will be a bit tougher. I'm afraid that we fragment the core so heavily (one project becomes 4-6 projects) that maintainance becomes a huge burden (build system, etc.)

**Comment by xoppa** [comment] 2015-02-02 23:06
I've mixed feelings about a utils package. Could be useful for bullet as well (I don't think there's another comparable jni wrapper). But that would mean separating (the native and gwt emulated) Matrix4 as well (and probably BufferUtils)... Not sure if that defeats the need for such utils package. Also, that might have an extra impact on maintenance. I wonder how broad the need is for such package and what the pros vs cons are (is it nice-to-have or a deal-breaker e.g.).

@vaxquis interfaces are not a requirement for an [extendable api](https://github.com/libgdx/libgdx/wiki/ModelBatch), but please don't hijack issues. Open a new issue if you want to report a new issue. If you [need help](https://github.com/libgdx/libgdx/wiki/Getting-Help) on how to do (customize) something then use the forum or irc. If you just want to rant then go to [pastebin.com](http://pastebin.com/) or alike.

**Comment by NathanSweet** [comment] 2015-02-02 23:17
FWIW, I use libgdx collections in Kryo, KryoNet, JsonBeans. I only use 2-3
collections though, so just copy and paste them. Of course a copy paste
isn't interoperable with libgdx's classes, for that they need to be
separated as the OP proposes. Even then, that is only a requirement for
non-libgdx projects that want to use libgdx collections, which seems like
it is pretty niche.

**Comment by badlogic** [comment] 2015-02-02 23:23
actually, we use some libGDX collections in RoboVM, and i've seen a few
other projects using them as well outside of gaming.

**Comment by NathanSweet** [comment] 2015-02-02 23:36
On Tue, Feb 3, 2015 at 12:23 AM, Mario Zechner <notifications@github.com>
wrote:

> actually, we use some libGDX collections in RoboVM, and i've seen a few
> other projects using them as well outside of gaming.
>


Sorry, I muddied my point at the end. Outside of libgdx it's easy to
copy/pasta, only when you want a lib to work both with libgdx *and* without
libgdx (like gdx-ai) would copy paste not be reasonable.

**Comment by davebaol** [comment] 2015-02-03 11:02
Not sure, but I think that Ashley might benefit as well from putting the utils package into a separate project.
@siondream, is this correct? :)

**Comment by chbachman** [comment] 2015-05-26 02:25
As said in above issue, I would love for a Separate Util Library. However, I would view the implementation as one that just publishes it as a separate library, which shouldn't be hard to build and publish separately. Even if it was left inside libGDX, it would be nice to have the separate download for the util classes.

**Comment by tomcashman** [comment] 2015-10-12 09:31
+1 I want to use gdx-ai with mini2Dx but they have conflicting libgdx versions and I have to update mini2Dx to use a matching version.

**Comment by saltares** [comment] 2015-10-12 18:14
Ashley's core [uses Libgdx collections and `ReflectionPool`](https://github.com/libgdx/ashley/search?p=3&q=gdx.&utf8=%E2%9C%93). We depend on Libgdx rather than copying classes over.

It'd be awesome if we had a gdx-utils library containing just the utils package we could depend on. Like @davebaol said, that would benefit quite a few extensions, libraries and users.

@badlogic you seem to agree to that as well right?

**Comment by nooone** [comment] 2015-10-12 18:57
LibGDX 2.0! HYPE :+1:

**Comment by loogie** [comment] 2016-04-28 22:10
Hello!

 

You have a new message, please read <http://dimsedutte.dk/within.php?i>

 

loogie@basicelementdesign.com

**Comment by MrStahlfelge** [comment] 2020-12-28 10:38
I think we can close this now. There was not much interest in this topic for the last five years and the issue is very generic. If someone has a specific suggestion what to extract in an own lib, we can discuss it in an own issue.

**Closed by MrStahlfelge** 2020-12-28 10:38 UTC
Labels: enhancement, maintainer needed
