### ISSUE TITLE
Add support for borderless fullscreen mode on supporting desktop OSes

### ISSUE THREAD

**Issue by MontyHimself** [libgdx/libgdx#6646] opened 2021-09-11 11:01 UTC
#### Issue details
On desktop, libGDX currently offers windowed mode and fullscreen mode. There is a special third option, typically called borderless fullscreen, whereby a window with the exact characteristics of the monitor's display mode is created. There are two main advantages to this. One is smoother switching between the 'fullscreen' window and other programs (no black flickering due to display mode changes). The other is that it prevents the 'fullscreen' window from being iconified when focusing on another window on a different monitor, which is what happens when using the traditional fullscreen mode with autoIconify set to true.

For Windows (only tested on Windows 10), one can activate borderless fullscreen as follows:
```java
public static void setBorderlessFullscreenMode(Graphics.Monitor monitor) {
    var window = ((Lwjgl3Graphics) Gdx.graphics).getWindow();
    var mode = (Lwjgl3Graphics.Lwjgl3DisplayMode) Gdx.graphics.getDisplayMode(monitor);
    GLFW.glfwSetWindowMonitor(window.getWindowHandle(), 0, 0, 0, mode.width, mode.height, mode.refreshRate);
}
```

The functionality is documented here: https://www.glfw.org/docs/latest/window_guide.html#window_windowed_full_screen
What is not mentioned, however, is that one needs to set the monitor parameter to 0 for this to work (see https://github.com/glfw/glfw/issues/1267).

I think it would be great for this to be added as a method in `Gdx.graphics`.

Someone should test whether this also works on macOS and Linux.

#### Version of libGDX and/or relevant dependencies
libGDX 1.10.0 with LWJGL3 backend

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by Frosty-J** [comment] 2021-09-11 13:27
I can test stuff on Linux, bearing in mind behaviour may differ between distros and window managers. Might give that a dabble later today, might not.

#4785 may be useful to read through if you haven't already seen it, with its `setAutoIconify()` and all that.

**Comment by crykn** [comment] 2021-09-11 14:33
Borderless fullscreen is already supported, just use:
```java
Graphics.DisplayMode displayMode = Lwjgl3ApplicationConfiguration.getDisplayMode();
Gdx.graphics.setUndecorated(true);
Gdx.graphics.setWindowedMode(displayMode.width, displayMode.height);
```

**Comment by MontyHimself** [comment] 2021-09-11 18:52
> Borderless fullscreen is already supported, just use:
> 
> ```java
> Graphics.DisplayMode displayMode = Lwjgl3ApplicationConfiguration.getDisplayMode();
> Gdx.graphics.setUndecorated(true);
> Gdx.graphics.setWindowedMode(displayMode.width, displayMode.height);
> ```

This doesn't produce the same results for me, the task bar is rendered on top of the window.

**Comment by crykn** [comment] 2021-09-12 08:35
Did you  get the order of the method calls right? For it to work, `setUndecorated(true)` has to be called before `setWindowedMode(...)`.

**Comment by MontyHimself** [comment] 2021-09-12 11:28
Yes, I tried it in exactly this order. Both in the case when I set it in the config before window creation (`config.setDecorated(false)`) and in the above case, the task bar is still rendered on top of the window.

**Comment by crykn** [comment] 2021-09-12 14:20
That is strange. Does the borderless fullscreen work in other applications on your machine?

**Comment by MontyHimself** [comment] 2021-09-12 18:37
I just tested it on a freshly configured libGDX game and the same thing happens. As for other applications, borderless fullscreen certainly works. Most recently I have used it in Mini Motorways.

I don't quite understand why this is surprising, though. Has the above code snippet ever worked in the past? The GLFW wiki entry I linked at the beginning only states one way to achieve a borderless fullscreen window, and the window decoration is not part of it.

**Comment by crykn** [comment] 2021-09-12 21:25
> I don't quite understand why this is surprising, though. Has the above code snippet ever worked in the past?

Yes it has and (at least on my end) it still does. 

Does the piece of code you posted above work? Because behind the scenes `Gdx.graphics.setWindowedMode(displayMode.width, displayMode.height)` does [exactly the same](https://github.com/libgdx/libgdx/blob/add6031b113d9e255f791656581bdffbbff83f89/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java#L418-L420).

**Comment by Frosty-J** [comment] 2021-09-13 00:37
I don't really know what's going on here, but I agree that Monty's code behaves as expected (not sure how it's different from `setFullScreenMode()` in practice when it comes to LWJGL3) and crkyn's code results in taskbars overlapping the game. I'm doing both of them at the end of my `create()`.

>Does the piece of code you posted above work? Because behind the scenes Gdx.graphics.setWindowedMode(displayMode.width, displayMode.height) does [exactly the same](https://github.com/libgdx/libgdx/blob/add6031b113d9e255f791656581bdffbbff83f89/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java#L418-L420).

This code only runs if the game is full screen. It works if the game is already full screen (for example, if `config.setFullscreenMode(Lwjgl3ApplicationConfiguration.getDisplayMode());` is in `DesktopLauncher`) but otherwise we get the overlapping taskbar issue.

**Comment by MontyHimself** [comment] 2021-09-13 08:46
This is all quite strange. The behavior seems to depend on the available monitors.

If I have only one monitor connected, there are two methods:
1) The code snippet from the beginning, but only when adding `setUndecorated(true)` before setting the window mode
2) The code by @crykn, with the call to `setUndecorated(true)` before the mode change, but only when fullscreen mode is activated on startup in the config (i.e. in `Lwjgl3ApplicationConfiguration`, it doesn't work for me by just calling `setFullscreenMode()` beforehand)

The result of this is effectively the same as the normal fullscreen mode, except that when alt-tabbing the window doesn't immediately iconify, but rather just loses focus (the other applications are rendered on top of it). Most importantly, it still has the same flickering as the traditional fullscreen mode.

If I have a second monitor connected, the behavior is the same as above, with one caveat. In both cases, if I remove the call to `setUndecorated(true)`, I get better results. Without the call, alt-tabbing is perfectly smooth with no flickering at all. That is the behavior I was initially looking for. Apparently I had the second monitor connected when testing it at the beginning.

So as of yet, I can only achieve a proper borderless fullscreen when having more than one monitor connected. 🤔

**Comment by Frosty-J** [comment] 2021-09-13 08:57
I kinda skimmed over that flickering business. This is strange - LWJGL3 full screen shouldn't cause anything like that, even in full screen mode, as it doesn't do the same exclusive full screen stuff the LWJGL2 backend does. I only have one monitor connected, and can't really go testing with more unless I create a virtual monitor or something. Unsure how to help - it's a head-scratcher, for sure.

**Comment by crykn** [comment] 2021-09-13 11:22
I just did some extensive testing with various different combinations of methods and config options. The raw data can be found at the bottom. My main conclusions were:

- Regardless of which method is used to achieve borderless fullscreen,  on my end (Windows 10, build 19043.1165) **the taskbar only disappears when `setUndecorated` is set to `true`**. This, in turn, inevitably leads to flickering.
- The code suggested by @MontyHimself does work as expected when used in conjunction with `setUndecorated(true)`. However, it doesn't have the desired effect, when the window isn't located on the primary monitor.
- When using the solution I suggested above (i.e., `setUndecorated(true)` and `setWindowedMode(...)`) the taskbar is not rendered, but can apparently _still be clicked on_. (Similarly to @MontyHimself's findings, this does not happen, when fullscreen mode is activated on startup, while later calls of `setFullscreenMode()` don't have the same effect. This seems to be caused by the fact that the if-condition [here](https://github.com/libgdx/libgdx/blob/add6031b113d9e255f791656581bdffbbff83f89/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java#L408-L410) is only `true` in the former case.) **However, before 1.9.12 this bug doesn't seem to happen, so it was most likely introduced in #6178. Interestingly enough, the behaviour in 1.9.11 also wasn't flawless: it only worked on the primary monitor; on any other monitor it behaved the same as it does now (i.e. the taskbar isn't visible, but still clickable).**

Suggestions on how to fix this are very welcome!


<details>
  <summary><b><i>Click to expand raw data</i></b></summary>

### Primary monitor in multi-monitor environment
| Startup    | In Create()                                    | Taskbar visible? | Taskbar clickable? | Flickering? | Applications on top? | Auto-minimise |
|------------|------------------------------------------------|------------------|--------------------|-------------|----------------------|---------------|
| Window     | setUndecorated; setWindowedMode                | n                | **y (!)**              | y           | y                    | n             |
| Window     | setWindowedMode                                | y                | –                  | n           | y                    | n             |
| Fullscreen | setUndecorated; setWindowedMode                | n                | n                  | y           | y                    | n             |
| Fullscreen | setWindowedMode                                | y                | –                  | n           | y                    | n             |
| Window     | setFullscreen; setUndecorated; setWindowedMode | n                | **y (!)**              | y           | y                    | n             |
| Window     | setFullscreen; setWindowedMode                 | y                | –                  | n           | y                    | n             |
|            |                                                |                  |                    |             |                      |               |
| Window     | setBorderlessFullscreen()                      | y                | –                  | n           | y                    | n             |
| Window     | setUndecorated; setBorderlessFullscreen        | n                | n                  | y           | y                    | n             |
| Fullscreen | setBorderlessFullscreen()                      | y                | –                  | n           | y                    | n             |
| Fullscreen | setUndecorated; setBorderlessFullscreen        | n                | n                  | y           | y                    | n             |
|            |                                                |                  |                    |             |                      |               |
| _Window_     | _setFullscreen_                                  | n                | n                  | y           | n                    | y*            |
| _Fullscreen_ | _---_                                              | n                | n                  | y           | n                    | y*            |

### Single monitor connected  
| Startup    | In Create()                                    | Taskbar visible? | Taskbar clickable? | Flickering? | Applications on top? | Auto-minimise |
|------------|------------------------------------------------|------------------|--------------------|-------------|----------------------|---------------|
| Window     | setUndecorated; setWindowedMode                | n                | **y (!)**              | y           | y                    | n             |
| Window     | setWindowedMode                                | y                | –                  | n           | y                    | n             |
| Fullscreen | setUndecorated; setWindowedMode                | n                | n                  | y           | y                    | n             |
| Fullscreen | setWindowedMode                                | y                | –                  | n           | y                    | n             |
| Window     | setFullscreen; setUndecorated; setWindowedMode | n                | **y (!)**              | y           | y                    | n             |
| Window     | setFullscreen; setWindowedMode                 | y                | –                  | n           | y                    | n             |
|            |                                                |                  |                    |             |                      |               |
| Window     | setBorderlessFullscreen()                      | y                | –                  | n           | y                    | n             |
| Window     | setUndecorated; setBorderlessFullscreen        | n                | n                  | y           | y                    | n             |
| Fullscreen | setBorderlessFullscreen()                      | y                | –                  | n           | y                    | n             |
| Fullscreen | setUndecorated; setBorderlessFullscreen        | n                | n                  | y           | y                    | n             |
|            |                                                |                  |                    |             |                      |               |
| _Window_     | _setFullscreen_                                  | n                | n                  | y           | n                    | y*            |
| _Fullscreen_ | _---_                                              | n                | n                  | y           | n                    | y*            |

<b>*:</b> since `autoIconify` is set to `true` by default
</details>

**Comment by MontyHimself** [comment] 2021-09-13 17:33
Thanks @crykn for the thorough testing!

I did some more research and figured out that the flickering for undecorated windows is apparently due to OpenGL not having the same control over the swapchain as DirectX. See here: https://discourse.glfw.org/t/cannot-manage-to-create-borderless-windowed-form/1592/2

The workaround described in that discussion is to add one pixel to the resolution of the window. Lo and behold, the flickering disappears when doing that. This is the code I used:
```java
public static void setBorderlessFullscreenMode() {
	Gdx.graphics.setUndecorated(true);
	Lwjgl3Graphics.Lwjgl3Monitor monitor = (Lwjgl3Graphics.Lwjgl3Monitor) Gdx.graphics.getMonitor();
	Lwjgl3Graphics.Lwjgl3DisplayMode mode = (Lwjgl3Graphics.Lwjgl3DisplayMode) Gdx.graphics.getDisplayMode(monitor);
	Lwjgl3Window window = ((Lwjgl3Graphics) Gdx.graphics).getWindow();
	GLFW.glfwSetWindowPos(window.getWindowHandle(), monitor.virtualX, monitor.virtualY);
	GLFW.glfwSetWindowSize(window.getWindowHandle(), mode.width, mode.height + 1);
}
```

This works on both the primary and other monitors. The only downside that I can see is that, well, the window is now one pixel larger than necessary. You would have to account for that in your game. Also, when making a screenshot or recording, the resolution of that would be one pixel larger as well.

(I also noticed that the flickering comes back when the window is already opened and I plug in a second monitor, but I guess monitor plug and play can always lead to strange issues.)

**Comment by crykn** [comment] 2021-09-13 19:52
Ah nice, that is good to know! I have opened a PR (#6649) to fix the issues mentioned in my comment above. After it is merged (reviews are welcome!), borderless fullscreen can be achieved as follows:

```java
Gdx.graphics.setUndecorated(true);
Graphics.DisplayMode displayMode = Gdx.graphics.getDisplayMode();
Gdx.graphics.setWindowedMode(displayMode.width, displayMode.height);
```

Or, if you want to use the '1 pixel wider' trick, the last line has to be change to `Gdx.graphics.setWindowedMode(displayMode.width, displayMode.height + 1);`.

**Closed** 2021-10-04 21:38 UTC
Labels: bug, LWJGL3, graphics
