### ISSUE TITLE
BSpline::calculate/derivative (and their calling functions) are silently failing for degre != 3

### ISSUE THREAD

**Issue by Omicron666** [libgdx/libgdx#6313] opened 2020-12-15 18:55 UTC
https://github.com/libgdx/libgdx/blob/bc314368a18e0c916437f3dd7b4172714e6abf8b/gdx/src/com/badlogic/gdx/math/BSpline.java#L133-L167

**Comment by NathanSweet** [comment] 2020-12-16 04:36
I assume having a degree parameter that only supports 3 is because the author didn't have time to implement others. Contributions are welcome.

**Comment by tommyettinger** [comment] 2020-12-19 22:27
I think the problem is more that the spline doesn't do anything when degree is not 3 (hence "silently" failing), and it isn't documented that 3 is the only spline degree that does anything. Is the solution here for someone to implement other degrees? Would it be enough to document that degree should always be 3?

**Comment by NathanSweet** [comment] 2020-12-19 23:16
Aye, we should document and throw illegal argument exception if it's not 3 until the time that someone implements other values.

**Comment by tommyettinger** [comment] 2020-12-27 01:00
Now that the texture atlas PR is merged, the requirement for spline degree to be 3 is documented and the method throws an IllegalArgumentException if degree is not 3. If anyone intends to implement more degrees later, we could leave this open until those are ready, but otherwise this could maybe be closed.

**Closed** 2020-12-27 06:18 UTC
Labels: enhancement, good first issue, math
