### ISSUE TITLE
TextField issue

### ISSUE THREAD

**Issue by panli32811** [libgdx/libgdx#3420] opened 2015-09-17 03:27 UTC
in the method #paste, if writeEnters is false and c is \n, c won't be filtered out.

**Comment by xoppa** [comment] 2015-09-17 14:05
Please include an [executable example](https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code).

**Comment by nhydock** [comment] 2015-09-17 14:24
I think this is a duplicate of #3340

**Comment by panli32811** [comment] 2015-09-18 07:20
I used a font in android system - Roboto-Regular.ttf. I'm sorry it can't be uploaded. My code:
```java
        FreeTypeFontParameter para = new FreeTypeFontParameter();
        para.size = 15;
        para.incremental = true;
        systemFont = new FreeTypeFontGenerator(Gdx.files.internal("Roboto-Regular.ttf")).generateFont(para);
        stage = new Stage(new StretchViewport(800, 600, camera), batch);
        skin = new Skin(new TextureAtlas(Gdx.files.internal("uiskin.atlas")));
        TextFieldStyle style = new TextFieldStyle();
        style.background = skin.getDrawable("textfield");
        style.selection = skin.getDrawable("selection");
        style.fontColor = new Color(0.41f, 0.75f, 0.99f, 1f);
        style.font = systemFont;
        style.disabledFontColor = new Color(0.79f, 0.79f, 0.79f, 0.1f);
        style.cursor = skin.getDrawable("cursor");
        textField = new TextField("text\nfield", style);
        textField.setPosition(300, 300);
        stage.addActor(textField);
```
The textField showed like this:
text
field

**Comment by Tom-Ski** [comment] 2015-09-18 11:50
What exactly is the issue? How does your provided code show this issue? 
Please read the link that @Xoppa provided.

**Comment by panli32811** [comment] 2015-09-21 02:14
Ok, the entire codes are:
```java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.FreeTypeBitmapFontData;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.FreeTypeFontParameter;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.scenes.scene2d.ui.Label.LabelStyle;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.TextField;
import com.badlogic.gdx.scenes.scene2d.ui.TextField.TextFieldStyle;
import com.badlogic.gdx.utils.Align;
import com.badlogic.gdx.utils.viewport.StretchViewport;

import depthui.freetype.DPFreeType;
import depthui.freetype.DPFreeTypeFont;
import depthui.freetype.DPFreeTypeFontData;
import depthui.freetype.DPFreeTypeStyle;

public class TextFieldTest extends ApplicationAdapter {
    SpriteBatch batch;
    OrthographicCamera camera;
    BitmapFont font;
    Stage stage;
    TextField textField;
    Label label;
    Skin skin;

    @Override
    public void create() {
        batch = new SpriteBatch();
        camera = new OrthographicCamera();

        FreeTypeFontParameter para = new FreeTypeFontParameter();
        para.size = 15;
        para.incremental = true;
        font = new FreeTypeFontGenerator(Gdx.files.internal("Roboto-Regular.ttf")).generateFont(para);

        stage = new Stage(new StretchViewport(800, 600, camera), batch);
        skin = new Skin(new TextureAtlas(Gdx.files.internal("uiskin.atlas")));

        TextFieldStyle style = new TextFieldStyle();
        style.background = skin.getDrawable("textfield");
        style.selection = skin.getDrawable("selection");
        style.fontColor = new Color(0.41f, 0.75f, 0.99f, 1f);
        style.font = font;
        style.disabledFontColor = new Color(0.79f, 0.79f, 0.79f, 0.1f);
        style.cursor = skin.getDrawable("cursor");
        textField = new TextField("text\nfield", style);
        textField.setPosition(300, 300);
        stage.addActor(textField);

        Gdx.input.setInputProcessor(stage);
    }

    @Override
    public void resize(int width, int height) {
        stage.getViewport().update(width, height);
    }

    @Override
    public void render() {
        Gdx.gl20.glClearColor(0.5f, 0.5f, 0.5f, 1f);
        Gdx.gl20.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
        stage.act();
        stage.draw();
    }

    @Override
    public void dispose() {
        batch.dispose();
        skin.dispose();
        font.dispose();
    }

    public static void main(String args[]) {
        new LwjglApplication(new TextFieldTest(), "Test", 800, 600);
    }
}
```
And the result is:
![qq 20150921101042](https://cloud.githubusercontent.com/assets/8217836/9984389/2688fea8-6049-11e5-9bb8-f67d36c61d9c.png)

I meant that a `TextField` should not be wrapped as it's not a `TextArea`.

**Comment by NathanSweet** [comment] 2016-11-25 01:26
Seems this got fixed at some point.
![](http://n4te.com/x/975-IWlj.png)

**Closed by NathanSweet** 2016-11-25 01:26 UTC
Labels: need more info, scene2d
