### ISSUE TITLE
Nexus 7 Android 5.0.1 Music not playing

### ISSUE THREAD

**Issue by milos1290** [libgdx/libgdx#2663] opened 2014-12-20 19:31 UTC
Just tested with latest nightlies and stable build music is not playing on 5.0.1 Nexus 7, i tested on Nexus 5 on 5.0 and it runs normally. Here is the log

```
E/MediaPlayer﹕ prepareAsync called in state 0
W/System.err﹕ java.lang.IllegalStateException
W/System.err﹕ at android.media.MediaPlayer._prepare(Native Method)
W/System.err﹕ at android.media.MediaPlayer.prepare(MediaPlayer.java:1125)
W/System.err﹕ at com.badlogic.gdx.backends.android.AndroidMusic.play(AndroidMusic.java:85)
W/System.err﹕ at com.badlogic.gdx.backends.android.AndroidMusic$1.run(AndroidMusic.java:177)
W/System.err﹕ at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:409)
W/System.err﹕ at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
W/System.err﹕ at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

E/MediaPlayer﹕ Error (-38,0)
E/MediaPlayer﹕ Error (100,0)
W/AudioSystem﹕ AudioPolicyService server died!
W/System.err﹕ java.io.IOException: Prepare failed.: status=0x64
W/System.err﹕ at android.media.MediaPlayer._prepare(Native Method)
W/System.err﹕ at android.media.MediaPlayer.prepare(MediaPlayer.java:1125)
W/System.err﹕ at com.badlogic.gdx.backends.android.AndroidMusic.play(AndroidMusic.java:85)
W/System.err﹕ at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
W/System.err﹕ at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
W/System.err﹕ at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:344)
W/System.err﹕ at com.badlogic.gdx.backends.android.AndroidInput.processEvents(AndroidInput.java:360)
W/System.err﹕ at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:414)
W/System.err﹕ at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
W/System.err﹕ at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

Sound effects works as intended.

**Comment by alex-dorokhov** [comment] 2015-02-01 11:15
Happens for me too on my Nexus 5. I have 2 Music instances. If the game is just started, the first music start to play just fine. Once I have opened another screen, the second music should start playing: there is fadeout/fadein effect with both music volumes. But the second music just don't start to play and I've similar stacktrace like @milos1290 has.

**Comment by badlogic** [comment] 2015-02-02 17:29
I can't reproduce this on any of my devices, so it's gonna be tough to fix. I know cocos2d-x had a similar issue and i think they fixed it. If someone with a device that shows the error can reproduce, please let us know.

**Comment by obigu** [comment] 2015-02-16 23:36
I can reproduce it in both a Nexus 5 and a Nexus 7.

This issue only happens with NuPlayer (active in Developer Options by default).

A simple way to reproduce it is by creating a Music instance and calling stop() before calling play().

```
music = Gdx.audio.newMusic(Gdx.files.internal(("song.mp3")));
music.setLooping(true);
music.stop();
music.play();
```

This code works in desktop and AwesomePlayer (the Android non experimental one that was also the the default one before 5.0.0). I think a fix would be to only call player.stop() in the stop() AndroidMusic method if the player is prepared.

**Comment by Angryhead** [comment] 2015-04-14 07:40
Having the same issue on my first-gen Motorola Moto G, 5.0.2.

As obigu said, only seems to happen when using NuPlayer.

**Comment by MisterMagister** [comment] 2015-08-01 15:47
On moto g 2 gen the same when using NuPlayer

**Comment by bitdream** [comment] 2018-07-03 02:02
What's the status of this issue. I still see this from Google play crash report.

**Comment by fmmarzoa** [comment] 2018-10-07 14:45
Similar problem here, only with one audio file, but on a variety of devices and Android versions:

Android 7.1.1 on SM-J250M
Android 5.1.1 on HT-704
Android 4.4.2 on Galaxy Tab4 7.0
Android 6.0.1 on miTab_PRO_10
Android 6.0 on STUDIO G2
Android 7.0 on SM-G610M
Android 4.4.2 on PocketBook SURFpad 3 (7,85")
Android 5.1 on 8050D

I'm using libgdx 1.9.9-snapshot. Here's the stack trace:

```
Caused by java.io.IOException: Prepare failed.: status=0x64
       at android.media.MediaPlayer._prepare(MediaPlayer.java)
       at android.media.MediaPlayer.prepare(MediaPlayer.java:1146)
       at com.badlogic.gdx.backends.android.AndroidAudio.newMusic(AndroidAudio.java:123)
       at com.badlogic.gdx.assets.loaders.MusicLoader.loadAsync(MusicLoader.java:48)
       at com.badlogic.gdx.assets.loaders.MusicLoader.loadAsync(MusicLoader.java:29)
       at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:70)
       at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:34)
       at com.badlogic.gdx.utils.async.AsyncExecutor$2.call(AsyncExecutor.java:58)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

I attach the mp3 file. It's a tiny clip from a Kevin MacLeod song.

[gameover.mp3.zip](https://github.com/libgdx/libgdx/files/2454004/gameover.mp3.zip)

**Comment by shatterblast** [comment] 2020-04-27 13:06
Is this still an issue?  Or can we close this, please?

**Comment by noblemaster** [comment] 2020-08-28 02:51
This is a very old issue. There are newer issue and some sound API changes. I'll close this for now. But we can re-open if non of the newer issues/pull requests don't address it.

**Closed by noblemaster** 2020-08-28 02:51 UTC
Labels: android, bug
