### ISSUE TITLE
Eclipse formatter doesn't work for Mars

### ISSUE THREAD

**Issue by StrongJoshua** [libgdx/libgdx#3285] opened 2015-07-16 01:16 UTC
Not that you can't import it, but it behaves differently from Luna. The major aspect that I have noticed is that while in Luna the following code looks like this:

		removeButton.addListener(new ClickListener() {
			@Override
			public void clicked (InputEvent event, float x, float y) {
				editor.remove();
			}
		});
in Mars it looks like this:

		removeButton.addListener(new ClickListener() {
			@Override
			public void clicked (InputEvent event, float x, float y) {
			editor.remove();
			}
		});
Although this might seem minor just looking at it like this, the difference ruins commits because of how many places this change occurs. I haven't been able to find the setting to change it back, in Mars, to the way it works in Luna. Just for extra clarification, I am importing the exact same formatter to Luna and Mars, getting those respective results.

**Comment by NathanSweet** [comment] 2015-07-16 01:50
Maybe Mars is broken?

**Comment by StrongJoshua** [comment] 2015-07-16 03:27
Haha very much a possibility :P

**Comment by StrongJoshua** [comment] 2015-07-16 14:56
[This Stackoverflow question](http://stackoverflow.com/questions/31073603/eclipse-4-5-java-formatter-changed) (not mine) describes the same problem and has a workaround. When the poster says "add 2" they actually mean to add 2, so it would be 5 and 5 for indentation size and tab size, respectively.

I don't know if there are any other major issues, but you might want to upload a formatter for Mars, or put a notice somewhere, so contributors don't mess up the formatting.

**Comment by MobiDevelop** [comment] 2015-07-16 15:49
Better yet, someone should report it as a regression bug in Eclipse Mars.

**Comment by StrongJoshua** [comment] 2015-07-16 15:59
I found [this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=467229).

**Comment by nooone** [comment] 2015-07-28 11:56
Can you rename this issue to "Eclipse formatter doesn't work on Mars"?

**Comment by Darkyenus** [comment] 2015-07-28 12:12
Yeah, those [rovers](https://en.wikipedia.org/wiki/Curiosity_(rover)) keep committing badly formatted code.


(Sorry.)

**Comment by Lestat** [comment] 2015-07-28 16:57
How long did I sleep this time, how many centuries, what the hell is mars, is eclipse still a thing?

**Comment by GreenLightning** [comment] 2015-08-06 11:11
@Lestat Eclipse is still a thing and Mars is just the code name for Eclipse 4.5 which was released on 24th June 2015.

**Comment by xoppa** [comment] 2015-08-18 18:31
Looks like it will be fixed, so I guess this is not a libgdx issue.

**Closed by xoppa** 2015-08-18 18:31 UTC
