### ISSUE TITLE
FreeTypeFontGenerator fails to generate atlas and use it in version 1.9.13, was working in 1.6.5

### ISSUE THREAD

**Issue by kunterbunt2** [libgdx/libgdx#6429] opened 2021-02-22 15:18 UTC
![1 9 13](https://user-images.githubusercontent.com/8464449/108728202-a2c72080-7529-11eb-8a41-de4ff45e2444.png)
![1 6 5](https://user-images.githubusercontent.com/8464449/108728203-a2c72080-7529-11eb-8d8b-d2423fe6dbfa.png)

Please ensure you have given all the following requested information in your report.

#### Issue details
I generate font pixel data from ttf into an atlas and use it in my project. this was working fine in 1.6.5, but not anymore in 1.9.13. The text displayed in the atlas looks scrambled and also on the screen.
I attached images of both cases.

_Please provide the details of your issue_

#### Reproduction steps/code
Please run proveded junit test in attached maven project. It includes all the code and a ttf font. It will work fine with 1.6.5 but will display scrambled text in 1.9.13.

#### Version of LibGDX and/or relevant dependencies
1.9.13, maybe earlier. Workdk fine in version 1.6.5.

#### Stacktrace
It does not crash

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS
[test.font.zip](https://github.com/libgdx/libgdx/files/6022912/test.font.zip)

**Comment by kunterbunt2** [comment] 2021-02-22 16:06
I  found a workaround by using BitmapFontWriter. For that I need to generate also fnt files that can be used later to read fonts from the atlas.

**Comment by tommyettinger** [comment] 2021-02-24 00:17
This issue is caused by two things: you dispose `Pixmap`s while they are still in use (you shouldn't call `pixmap.dispose();` in `createAtlas()`, since it leads to essentially random pixels being used), and after that's fixed, your PixmapPacker settings are wrong somehow. The settings I used are:
```java
PixmapPacker packer = new PixmapPacker(256, 128, Format.RGBA8888, 1, false);
```

I got this incredible mess to work, somehow, with 1.9.13: https://i.imgur.com/pO2QPJi.png . I had to fix quite a lot of issues in your test, though, from misspelled Maven configurations, to a dependency on a non-existent library of yours, to just in general the test not being immediately runnable. Not many people who use libGDX also use Maven, and even though I am familiar with Maven, I'm not usually able to help with FreeType issues -- thankfully this one was relatively simple. Please consider trying Gradle via gdx-setup or [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff).

I'm closing this now; the main bug was user error in the form of premature dispose() calls, and the other error had to do with incorrectly duplicating padding in the settings for PixmapPacker. I don't know why this ever worked on 1.6.5; maybe some Pixmaps were copied back then and disposing one copy didn't trash the other copy.

**Closed by tommyettinger** 2021-02-24 00:17 UTC

**Comment by kunterbunt2** [comment] 2021-02-25 07:50
Thanks @tommyettinger for reviewing my ticket so fast and very sorry for causing you that much trouble.

**you shouldn't call pixmap.dispose()**
I am disposing the image after it has been used.
This should not have any impact.
I tested your advise, but this did not help.
Also, the resulting image is not randomized. It is always the same, but wrong.

**PixmapPacker settings**
This fixed it! Thank you!
The whole code was copied from a tutorial and worked fine in 1.6.5, so that is why I assumed it to be a bug.
I need to understand this duplicateBorder parameter which must have a good reason to exist, but in this case together with the 0 padding was causing havoc in my font.

**Maven**
I understand that libgdx community is working mostly on android and therefore using gradle. Unfortunately I lack the know how in gradle. I have years of experience with maven and only target desktop at the moment.
Sorry about the depedndency to one of my local libraries. Lesson to learn from that: Next time I will delete the maven repository to ensure I see unresolved dependencies to local libraries.
Probably also better to try to migrate the test project to gradle.


**misspelled Maven configurations**
After deleting the maven repository I was able to build successfully (after removing the local library dependency of course).
I cannot reproduce this issue. Will not be able to learn from this one.

**test not being immediately runnable**
The test class did not start or end with "Test" and therefore is by default ignored in the junit tests. I did all my tests with eclipse and it behaves differently.
Lesson to learn from that: Next time test all code on the command line.

Thank @tommyettinger you for your help, advise and the time you took to help!

**Comment by tommyettinger** [comment] 2021-02-25 09:25
Well I definitely got different results when `pixmap.dispose()` was commented out on 1.9.13... It could have been related to a different change, since some of your code loaded an existing image that wasn't created by the same PixmapPacker (I think, I'm not sure that code ever ran how I thought it would). I think I may have identified the wrong problem here, though I was able to get it to run -- I'll zip up my solution and attach it here. Still Maven :) You can reproduce the issue by changing the PixmapPacker constructor calls and running, sometimes twice. Twice because sometimes the old atlas file isn't deleted when it runs, which I only realized just now, and is probably why removing pixmap.dispose() seemed to clear up the issue -- atlas generation had been fixed on the previous run, but appeared broken in the app, I removed pixmap.dispose(), and only on the latest run did it appear fixed.
[test_font.zip](https://github.com/libgdx/libgdx/files/6041873/test_font.zip)
