### ISSUE TITLE
libGDX Setup Tool: glitches when moving the window around on Linux

### ISSUE THREAD

**Issue by tsteinholz** [libgdx/libgdx#3043] opened 2015-04-22 23:52 UTC
This is an awesome tool, works great, looks great, love it! But on linux, I have seen in the Gnome, Unity, KDE, and Cinnimon Desktop Environments. When ever you move the window around, it has the strangest seisure like movement. Its really disturbing and I would love it if it was fixed. If you need to see it just ask me for a video or install some distro of linux in a vm and test it. Thanks :)

**Comment by Tom-Ski** [comment] 2015-05-02 15:06
I've ran the setup the same environments, no issue for me.  This is the code responsible for moving the undecorated frame, perhaps you could give a few things a go and see what reproduces/causes the issue? 
https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java#L104-L115

**Comment by tsteinholz** [comment] 2015-05-02 15:18
https://www.dropbox.com/s/6wkk177rccx8n9v/2015-04-23%2020-03-41.flv?dl=0 - This is a video of what happens for me.

**Comment by Tom-Ski** [comment] 2015-05-09 17:41
This probably won't be fixed unless someone can provide a PR. I cant reproduce this using cinnamon, and I'm sorry but I'm not going to install distros until I can!

PR welcome!

**Closed by Tom-Ski** 2015-05-09 17:41 UTC
