### ISSUE TITLE
animation.getKeyFrames().length throws Casting Exception

### ISSUE THREAD

**Issue by gembutterfly** [libgdx/libgdx#4660] opened 2017-03-22 14:42 UTC
#### Issue details
Getting the length of the key frame array of an animation causes a Casting Exception.

#### Reproduction steps/code
```java
Array<TextureAtlas.AtlasRegion> regions = textureAtlas.findRegions("test");
Animation<TextureAtlas.AtlasRegion> animation = new Animation<>(.1f, regions, PlayMode.LOOP);
int i = animation.getKeyFrames().length;
```

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Stacktrace
Error Message: 
```java
Exception in thread "LWJGL Application" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lcom.badlogic.gdx.graphics.g2d.TextureAtlas$AtlasRegion;
```

#### Please select the affected platforms
- probably all

**Comment by xoppa** [comment] 2017-03-22 16:04
Duplicate of #4476

**Closed by xoppa** 2017-03-22 16:04 UTC
