### ISSUE TITLE
render() method called twice when switching between screen modes in the Lwjgl3 backend

### ISSUE THREAD

**Issue by angns9** [libgdx/libgdx#5496] opened 2019-01-02 01:24 UTC
(First of all, sorry for my bad English) In the Lwjgl3 backend, when I switch to a different screen mode (fullscreen or window mode) inside the render method, it is called again in the same call stack and this can lead to potential issues. I can solve this by calling the code in a post runnable or in a non-critical part, but this problem doesn't occur in the Lwjgl backend. For example, in the next code, If you uncomment the lines relating to the updating variable, it will throw an exception.

#### Reproduction steps/code
Press F4 to switch between fullscreen and window mode and see the stacktrace.
```java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;

public class DesktopLauncher extends ApplicationAdapter {
	boolean updating = false;
	boolean switchedScreenMode = false;

	@Override
	public void render() {
		// if (updating) throw new IllegalStateException();

		if (switchedScreenMode) {
			printStackTrace();
			switchedScreenMode = false;
		}
		updating = true;

		if (com.badlogic.gdx.Gdx.input.isKeyJustPressed(Input.Keys.F4)) {
			switchedScreenMode = true;
			if (!Gdx.graphics.isFullscreen())
				Gdx.graphics.setFullscreenMode(Gdx.graphics.getDisplayMode());
			else
				Gdx.graphics.setWindowedMode(800, 600);
		}

		// updating = false;
	}

	void printStackTrace() {
		System.out.println(Thread.currentThread().getName());
		for (StackTraceElement tmp : Thread.currentThread().getStackTrace())
			System.out.println(tmp);
		System.out.println("-----------------------------");
	}

	public static void main (String[] arg) {
		new Lwjgl3Application(new DesktopLauncher(), new Lwjgl3ApplicationConfiguration());
	}

}
````
#### Version of LibGDX and/or relevant dependencies
1.9.10-SNAPSHOT
Lwjgl3 Backend

#### Stacktrace
```java
java.lang.Thread.getStackTrace(Thread.java:1556)
com.aob.appinst.Lwjgl3AppListener.printStackTrace(Lwjgl3AppListener.java:40)
com.aob.appinst.Lwjgl3AppListener.render(Lwjgl3AppListener.java:17)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Graphics$1.invoke(Lwjgl3Graphics.java:72)
org.lwjgl.glfw.GLFWFramebufferSizeCallbackI.callback(GLFWFramebufferSizeCallbackI.java:37)
org.lwjgl.system.JNI.invokePPV(Native Method)
org.lwjgl.glfw.GLFW.glfwSetWindowMonitor(GLFW.java:2611)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Graphics.setFullscreenMode(Lwjgl3Graphics.java:344)
com.aob.appinst.Lwjgl3AppListener.render(Lwjgl3AppListener.java:25)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
com.aob.appinst.desktop.DesktopLauncher.main(DesktopLauncher.java:15)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by ejamshidiasl** [comment] 2019-01-06 16:45
you should update screen size in _**resize**_ function

**Comment by crykn** [comment] 2020-09-11 12:29
Duplicate of #5281.

**Closed by crykn** 2020-09-11 12:29 UTC
Labels: LWJGL3
