### ISSUE TITLE
Can't deploy Desktop project with Gradle.

### ISSUE THREAD

**Issue by Blezyn** [libgdx/libgdx#5716] opened 2019-07-19 14:38 UTC
#### Issue details
I am using the 1.9.10 libGDX version with the Libgdx Project Generator. I create a new project with only Desktop selected and I generate it. The generation is successful, so I continue by opening the project in IntelliJ IDEA 2019.1.3 Community Edition (Windows 10 Home 64 bit). Even though the default red background with the libGDX logo application runs fine, I just can't deploy it with Gradle to Desktop. I am using JDK 1.8.0_211 but the same happens with JDK 12.0.1

#### Reproduction steps/code
Create a new project with the Libgdx Project Generator only for Desktop and with no extensions, open it in IntelliJ IDEA, go to Terminal tab at the bottom and type gradlew desktop:dist.

#### Version of LibGDX and/or relevant dependencies
1.9.10 with no extensions as per Libgdx Project Generator

#### Stacktrace
```java
> Task :core:compileJava FAILED
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Compilation failed; see the compiler error output for details. 
```

After getting that error I changed the build.gradle in Core and Desktop sourceCompatibility to 1.8. But I still get an error:
```java
> Task :desktop:dist FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:dist'.
> Failed to create MD5 hash for file '...\Deploy\core\build\libs\core-1.0.jar' as it does not exist.
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment] 2019-07-19 15:03
Seems to be some kind of regression in 5.4.1

**Comment by Tom-Ski** [comment] 2019-07-19 15:06
Please try using 5.4 in your gradle/wrapper/gradle-wrapper.properties file.

Fixed in https://github.com/libgdx/libgdx/commit/0283370634b17deae54c38ad82ee61dbf8efd8d5

**Comment by Blezyn** [comment] 2019-07-19 15:17
I changed it to 5.4, but the problem is still there.

**Comment by Tom-Ski** [comment] 2019-07-19 15:20
Ah no. Run ./gradlew desktop:run, before a ./gradlew desktop:dist. Ill fix up shortly.

**Comment by Blezyn** [comment] 2019-07-19 15:24
It worked. Thank you very much!

**Comment by Tom-Ski** [comment] 2019-07-19 15:31
In your desktop/build.gradle, change the dist task to follow this commit: https://github.com/libgdx/libgdx/commit/fadd79b2ebe5d00e85373892e92e37e741b614b0

**Closed** 2019-07-19 15:31 UTC
