### ISSUE TITLE
Large delta after pause/resume (iOS)

### ISSUE THREAD

**Issue by jkazma-logisk** [libgdx/libgdx#6093] opened 2020-07-03 19:27 UTC
Similar to #1196

#### Issue details
If a game is paused for a long time, after resuming, Gdx.graphics.getDeltaTime() will give the delta of the entire pause duration. This causes freeze/stutter on resume as the game tries to process possibly hours worth of delta. This was fixed for the android version but not for iOS which makes it inconsistent across backends.

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._
1.9.10

#### Please select the affected platforms
- [ ] Android
- [x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment] 2020-07-05 16:55
Yep, it looks like a similar fix to the Android one can be applied to iOS backend. In the meantime as a workaround you can clamp the delta (for instance to 1/30f) which in most games it's a good practice protect against lag spikes (Scene2D for instance has this behaviour by default).

**Comment by jkazma-logisk** [comment] 2020-07-06 13:21
Great, thank you.

**Comment by furrysonly93** [comment] 2020-11-11 23:22
good first issue! 👍

**Comment by LK-Drako** [comment] 2020-11-24 09:29
@T45K #6247 
Duplicate of 

- [ ] #6273 [167.159.354.000](url)

**Comment by Armaxxx** [comment] 2020-12-17 19:10
Has this been completely solved? (I'm almost finished with the zip file handle one, but I'm having a bit of trouble)

**Comment by obigu** [comment] 2020-12-17 22:05
I haven't had a look to it, do you want it assigned?

**Comment by Armaxxx** [comment] 2020-12-18 22:05
For sure, I'll be finishing the other pr by weekend.

**Closed** 2021-01-10 13:58 UTC
Labels: bug, good first issue, ios

**Comment by newMemberHub** [comment] 2024-07-16 06:30
I work on libgdx for pause and resume, but when resume 
- The first deltatime is 0.
- The next one is 2.1. 
- From the third one, the deltatime is normal.
About the 2.1s depends on how long you was pending in pause status. If pause time is large, the deltatime will be same large.
I checked with latest version 1.12.1 and on Android run Android 13.

I think this fix is just for the first time.
The logs:
