### ISSUE TITLE
LWJGL3 windows no longer update while being resized

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx#6808] opened 2022-03-03 14:08 UTC
Looks like we have a regression on our hands. Videos are by @fgnm in #6785 - that issue is closed and the callback the issue it was about is resolved. While our windows used to update when resized, they don't anymore, which looks a bit odd.

My concern is more to do with games during development than once released, as resizing your window is an excellent way of telling if UI and all that is responding to different sizes correctly.

## 1.10.0

https://user-images.githubusercontent.com/60154347/156578877-accacbc5-fd5b-47ca-99f6-9b71627fcfb7.mp4

## 1.10.1-SNAPSHOT

https://user-images.githubusercontent.com/60154347/156578881-0845af51-4a3f-4233-9661-5710cf6e547d.mp4

## Affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [X] macOS

Windows and macOS tested by fgnm. Does not affect Linux in my test.

**Comment by tommyettinger** [comment] 2022-03-03 22:11
It certainly doesn't look good in the SNAPSHOT. Does anyone know the chain of events that led up to the current SNAPSHOT condition? I know there was something about a callback being called many times all at once, but that wasn't an issue in 1.10.0...

**Comment by crykn** [comment] 2022-03-03 22:42
https://github.com/libgdx/libgdx/pull/6772/commits/76a4e18e5120c8c8e0198707d68101c543b3a2c4 seems to be the culprit.

**Comment by tommyettinger** [comment] 2022-03-03 22:49
It looks like the changed code should only apply to MacOS, no? It seems to cause issues on Windows...

**Comment by fgnm** [comment] 2022-03-04 06:23
I have the same issue on macOS too, I'll try to upload another video for it soon

**Comment by fgnm** [comment] 2022-03-04 21:12
This is the behaviour using macOS.. Even weirder than Windows xD
https://user-images.githubusercontent.com/5543339/156841975-e5af4b3a-202d-423d-b8db-9c3248452cec.mp4

**Comment by crykn** [comment] 2022-04-26 20:04
This change is definitely not needed for Windows (and probably not for Linux either), so we could toggle this behaviour depending on the platform. Since this hadn't been an issue before #6772, it'd be nice if someone with a Mac could check, whether this change is needed for _every_  1.10.1-SNAPSHOT LWJGL 3 app on macOS or only when the gdx-lwjgl3-glfw-awt-macos extension is used. 

Getting rid of the `postRunnable` call would also allow us to revert https://github.com/libgdx/libgdx/commit/a5286e70f1ee279859ee8e8cc798b8444d458aaf.

**Comment by fgnm** [comment] 2022-04-26 20:22
With a bit more dig in the issue, I'd say that probably the real fix could be the use of a different thread to handle GLFW input events.. This would also fix the issue that when dragging on Windows the rendering freeze (like explained here https://github.com/glfw/glfw/issues/2074#issuecomment-1089094608)

**Comment by naphipps** [comment] 2022-10-29 01:32
[In my own repo](https://github.com/naphipps/NP-Engine), I fixed this issue and [glfw's #2074](https://github.com/glfw/glfw/issues/2074). The issue is that Windows starts an infinite loop during their window procedures to handle window resizing and moving -- and it starts that loop on a mousedown event on the titlebar/caption.

(I personally recommend that libgdx and glfw should not fix this unless they expose their loops to the user.)

Basically, my fix was to handle window sizing and moving directly/natively, and avoided calling Window's DefWindowProc so those infinite loops were avoided and my application loop could continue (in which, I handle window sizing/moving/etc). GLFW defers windows sizing and moving to DefWindowProc, so this issue is not their doing either... I think this behavior from DefWindowProc is a necessary evil for things to work "out of the box", but I wish their documentation would explain these things better... Anyways, I recommend you handle window sizing/moving directly/natively in a way that allows your application loop to continue. If you only care about rendering, then rendering in another can help but won't prevent the application loop from getting interrupted.

Specifically, I ended up just subclassing the window procedure. Feel free to take a look at my [repo NP-Engine](https://github.com/naphipps/NP-Engine). Under include/Window/Detail/Glfw, you'll find my implementation in GlfwWindow.hpp

I wrote more in the comments of [glfw's #2074](https://github.com/glfw/glfw/issues/2074), so feel free to head over their for more details in case I missed something here.

**Closed** 2023-06-18 20:27 UTC
Labels: bug, desktop, LWJGL3
