### ISSUE TITLE
Moving the assets directory for projects which include an Android module

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx#6612] opened 2021-07-30 01:35 UTC
The topic of moving the assets directory has come up again. Currently, gdx-setup puts assets in `android/assets/` if an Android module is present, and `core/assets/` otherwise.

So let's say we were to change this up, as there doesn't appear to be any reason to have it in `android/` in the present day. There are two obvious choices of where to move it:

❤️ `core/assets/`: This would be most consistent with gdx-setup's current behaviour when an Android module isn't present. I like this because it should be obvious to developers of all skill levels that it gets shared between Android/Desktop/HTML/iOS modules in the same way as `core/src/`.

🚀 `assets/`: This would be consistent with what gdx-liftoff does, I am told. myke says putting it at the project root may be good for subprojects that don't rely on the core module, such as editor tools.

We can use those message reaction thingies as a way of voting - heart for core, rocket for root and thumbs-down if you completely oppose changing where assets live. And of course an actual comment if you have something to say!

**Comment by tommyettinger** [comment] 2021-07-30 02:03
It would be nice if I didn't have to preface any assets-related help with "Well, that tutorial expects your assets will be in core/assets/, but you checked Android in gdx-setup, so it's in android/assets/ instead." And if people use Liftoff, it places things in assets/ as a rule, so that's another thing I need to mention as a difference...

There's also some nice possibilities here with module-specific assets that aren't shared with the rest of the modules, like desktop icons vs. app icons.

The editor tools point is a good one; now that LWJGL3 is the default, I'm not sure how gdx-tools is affected. A module that just invokes the texture packer would probably need access to the assets, but wouldn't always need to depend on core.

This would mess up a lot of older tutorials in a small way, and IDEA still doesn't like sharing a resources root between modules (though Gradle is fine with it). I think that either one of these would be an improvement, but 🚀 assets/ makes the least work to explain how resources are handled in libGDX.

**Comment by raeleus** [comment] 2021-07-30 02:19
In terms of simplicity, I like it in the project root. It's obvious and easy to find. Old tutorials are lacking in many ways already, so I feel we just need to move on. Thanks for writing this, Frosty J.

**Comment by mgsx-dev** [comment] 2021-07-30 06:56
duplicate of #4955

**Closed by mgsx-dev** 2021-07-30 06:56 UTC
