### ISSUE TITLE
Feature: Allow adding/modifying log destination

### ISSUE THREAD

**Issue by MrPlow442** [libgdx/libgdx#4251] opened 2016-08-15 16:47 UTC
Libgdx exposes it's built-in logger through `Gdx.app.log` methods. From what I can gather, these log messages are always sent to stdout as that is the default behavior of the lwjgl logger. 

I suggest adding a feature which would allow developers to change that default behavior and set a different output stream/writer, add new writers, or hook onto the current log methods so that they might also be output somewhere else (such as a file or dev console).

For example, let's say that the game has a dev console and we wish to redirect all logging calls to the in-game dev console instead of stdout. Ideally it would look something like this:

```
// Create a custom output writer
public class ConsoleWriter extends Writer     
     //........
     public void write(char cbuf[], int off, int len) throws IOException {
           console.write(cbuf, off, len);
     }
     //........
}

Gdx.app.setLogWriter(new ConsoleWriter()); 
// from this point on all Gdx.app.log/error/debug invocations will write to the ConsoleWriter instead of stdout
```

**Comment by xoppa** [comment] 2016-08-15 17:07
Possible duplicate of #1311

**Closed** 2016-08-24 02:53 UTC
