### ISSUE TITLE
Can not get superdevmode in RELEASE mode for HTML5?

### ISSUE THREAD

**Issue by EvgeniiZaikin** [libgdx/libgdx#7337] opened 2024-02-11 13:01 UTC
Hello! 

I created HTML5 application. I run _gradlew html:dist_ command. I run _http-server html/build/dist_ command. Where my game? I see message that superdevmode need. Why?

<img width="1792" alt="Снимок экрана 2024-02-11 в 15 59 08" src="https://github.com/libgdx/libgdx/assets/56962640/6a67f19c-6982-4729-9f7b-d8f29b4c7d24">

**Comment by EvgeniiZaikin** [comment] 2024-02-11 18:59
Well... I normally run release app by [this instruction](https://www.mgsx.net/html5-libgdx-tutorial). Summary I copied dist folder from app folders to external folder (in my case desktop folder). Remove WEB-INF folder. And successfully run with node.js server. May be you can add this into [deploying instruction](https://libgdx.com/wiki/deployment/deploying-your-application).

**Comment by tommyettinger** [comment] 2024-02-12 06:01
Those deploying instructions have said this about Node.js, since about 2 years ago:

> With Node.js `npm install http-server -g` then `http-server html/build/dist` and browse at http://localhost:8080/ . [docs](https://github.com/indexzero/http-server)

Does that not work? I really don't think the desktop module should have any HTML-specific files in it. If you meant the Desktop folder for your user account, not a desktop project's folder, I don't know of any particular reason why one would be different from the other. If your project is in a OneDrive folder, take it out of there, because OneDrive really makes a mess out of IDEA's or Android Studio's caches, and causes strange bugs.

I've never had to remove the WEB-INF folder. Then again, I almost exclusively use projects generated by gdx-liftoff for HTML, and Liftoff removes the contents of `WEB-INF/deploy/html/symbolMaps/` for dist builds (because they can be quite large). So I suppose the code I wrote removes specific parts of WEB-INF anyway...

**Comment by crykn** [comment] 2024-08-23 08:18
This seems to be a user error and not a bug, so closing this for now. If you have any other questions, take a look at our [Discord](https://libgdx.com/community/discord/) server.

**Closed by crykn** 2024-08-23 08:18 UTC
Labels: bug, gwt, need more info
