### ISSUE TITLE
Make G3dModelLoader customizable

### ISSUE THREAD

**Issue by VinceAngel** [libgdx/libgdx#3345] opened 2015-08-12 07:36 UTC
Hi,

Here is my issue : I'm customizing the json content for models, but the G3dModelLoader cannot be customized without copy/pasting the whole class.
I'm thinking about a PR to set all the parseMesh/Material/etc... methods public or protected to let them being overriden if necessary.

What do you think about this ?
Regards,
    Vincent.

**Comment by FyiurAmron** [comment] 2015-08-12 11:05
@VinceAngel personally, I'd say "give it a go", since that's the exact issue (non-extensibility) I've already voiced a couple of times regarding various classes. I have a feeling some devs gone with Josh Bloch's saying "either prepare class & document it for extensibility or explicitly prevent it" - still, IMO that just means a minor refactoring and/or doc preparation should be in place, not that there shouldn't be a way to extend library classes.

**Comment by nooone** [comment] 2015-08-12 11:25
Yeah, it would be nice if all package-private/default scoped fields in libgdx would be protected... not being able to extend some classes without making a PR beforehand was something I've encountered a few times before.

**Comment by xoppa** [comment] 2015-08-12 16:59
Is this a duplicate of #3186

**Comment by FyiurAmron** [comment] 2015-08-12 17:09
@xoppa with the bits OP said about this I wouldn't call it a dupe. He explicitly mentioned the JSON content, so I guess he's referring to e.g. https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/loader/G3dModelLoader.java#L81 , https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/loader/G3dModelLoader.java#L143 etc.

**Comment by VinceAngel** [comment] 2015-08-25 09:58
Not really a duplicate, but both can be done in the same time to make loader and model "builder" able to be customized.

**Comment by badlogic** [comment] 2015-11-17 00:08
Since we got no PR for this, and since the JSON format is what gets output by fbxconv which nobody except Xoppa is working on, i'm closing this.

**Closed by badlogic** 2015-11-17 00:08 UTC
