### ISSUE TITLE
Driver performance warnings after recent shader unbinding change

### ISSUE THREAD

**Issue by Crunkle** [libgdx/libgdx#5945] opened 2020-03-11 14:50 UTC
The commit 01ea5b1 (#5944) has caused performance warnings to appear, and sometimes spam, when drawing. A minimal reproducible example is shown below which can be fixed by reverting to any previous commit, or unbinding the shader yourself.

These warnings show when using an Nvidia card. I have not yet tested any AMD cards. I am unsure which specific GL state is causing the shader to be recompiled, but it could be various combined.

This also occurs when using `SpriteBatch`, `SpriteCache`, and other drawing classes.

```
[LWJGL] OpenGL debug message
	ID: 0x20092
	Source: API
	Type: PERFORMANCE
	Severity: MEDIUM
	Message: Program/shader state performance warning: Vertex shader in program 3 is being recompiled based on GL state.
```

```java
Lwjgl3ApplicationConfiguration options = new Lwjgl3ApplicationConfiguration();

options.enableGLDebugOutput(true, System.err);

new Lwjgl3Application(new ApplicationAdapter() {

    private ShapeRenderer shapeRenderer;

    @Override
    public void create() {
        shapeRenderer = new ShapeRenderer();
    }

    @Override
    public void render() {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        shapeRenderer.begin(ShapeRenderer.ShapeType.Line);
        shapeRenderer.line(0.0f, 0.0f, 1.0f, 1.0f);
        shapeRenderer.end();
    }

    @Override
    public void dispose() {
        shapeRenderer.dispose();
    }
}, options);
```

**Comment by mgsx-dev** [comment] 2020-03-11 23:20
Hi @Crunkle , i'm not able to reproduce it with my setup : 
Linux / NVIDIA GTX 950m drivers: 384.130

I have few questions:
* Could you tell us what's your setup? OS/version GPU Driver/version
* How much it spams when drawing? like every frame, every seconds? in this example or in your project?
* Did you noticed performance issues? FPS before / FPS after, glitches/freeze

I made [some searches](https://stackoverflow.com/questions/12004396/opengl-debug-context-performance-warning), and all i found so far might be related to [some nvidia dirvers versions](https://community.khronos.org/t/nvidia-280-x-and-geforce-4xx/65916/6). It try to optimize rendering by compiling shaders based on various states (eg. blending, buffer masking). That is, a side effect because of current shader still bound.

Could you upgrade your driver and test again please? :-)

**Comment by WickedShell** [comment] 2020-03-11 23:45
@mgsx-dev I just reproduced this here:
ArchLinux using 5.5.7-arch1-1 kernel
Java: 1.8.0_242
GTX 1070
NVIDIA 440.64 drivers

I get it without using the shaperenderer, I just took my existing application and told it to use the `1.9.11-SNAPSHOT`. I'd actually suggest you might be getting away with it due to the older driver version you are on. (You also have to actually enable the GLDebug output on LWJGL3 which I hadn't realized was a thing before now, but this is the only message I've seen come out it so far.)

**Comment by Crunkle** [comment] 2020-03-12 14:25
@mgsx-dev

I reproduced this using the exact example shown above on the very latest Nvidia driver 442.59 as well as various 400 drivers. It is not limited to Windows as far as I have tested. It is possibly due to depth masking being toggled whilst the shader is bound causing a recompilation.

I do agree that we should not need to constantly unbind shaders or textures with modern GL, but I do not see any performance improvement after your patch on my system. It is possible your older version does not optimize this, but later drivers do.

I have also noticed one other mention this outside of GitHub. It will always throw once at startup then, especially when using multiple drawing classes, can spam a few times.

**Comment by RUSshy** [comment] 2020-03-12 14:50
Sounds like a driver bug if it wasn't the case for previous version

I personally don't have this issue on AMD gpu (RX 580)

**Comment by RUSshy** [comment] 2020-03-12 14:51
libgdx needs a proper opengl state managements tbh, a cleanup needs to happen

**Comment by mgsx-dev** [comment] 2020-03-12 16:08
@Crunkle few remaining questions :-) :

* How much it spams when drawing? like every frame, every seconds? in this example or in your project?
* Did you noticed performance issues? FPS before / FPS after, glitches/freeze (without debug logs enabled)

Sure, get rid of unbind won't improve performance so much since there are typically a few shader switches but if it has bad impact on performance, maybe we should reconsider and revert.

I don't know if driver really recompile or simply say it may recompile at next drawing. So it might not be an issue.

**Comment by Crunkle** [comment] 2020-03-12 18:35
Sure, hope this helps:

On my system, in the example above, it outputs once on startup only. In more complex applications with multiple shaders it can output multiple messages with no set interval between them. It depends on state and so I can't give you any fixed timing.

Whilst running the latest driver I do not notice any performance difference. I am receiving identical frame times with or without the commit my larger application. I am unable to comment on performance for the example above as the frame time is too short to precisely measure.

**Comment by shatterblast** [comment] 2020-03-20 16:52
Proper use of .dispose() can help a lot, except in the case of a Music object.  In that case, you have to set it to null to clear the Listener.

The new Typing-Label library should be interesting.  When compiled separately from LibGDX, it seems to cause memory leaks.  I will like to see how it handle in the next stable LibGDX version.

**Comment by AndEditor7** [comment] 2020-07-22 03:36
I decided to visit this issue because I got this same message when I recently updated my project to 1.9.11 and LWJGL 3.2.3. Even tho I got a new Geforce GTX 1660 SUPER graphic card with a lastest driver update (451.67 - July 9th, 2020), and it appears in my console log with enabled GL debug output. But good news, I found what causes it, and fix. (may not work on every GPU and drivers). How I found it? I traced the log by adding a breakpoint in `System.err.println()` to found what triggers it. From what I found, it caused by `Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);`. I added 'Gdx.gl.glUseProgram(0);' before the `Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);`. And what you know, the debug message is gone!

**Comment by mgsx-dev** [comment] 2020-08-31 21:21
Does anyone here able to measure any performance issue? 
Issue opener didn't notice any, so i think it could be closed.

**Comment by AndEditor7** [comment] 2020-08-31 22:23
I doubted this would affect any performance unless specific GL state (or various combined) causes the GPU's shader compiler compiles with less efficient code. GPU can't predict GL state changes and should the shader needs to recompile. The GPU might have multiple compiled shader code for specific or various combined GL state, but I can't confirm it.

**Comment by mgsx-dev** [comment] 2020-10-08 23:06
Since nobody reported any performance issues, i'm closing it. Feel free to reopen if needed.

**Closed by mgsx-dev** 2020-10-08 23:06 UTC
Labels: GL, need more info
