### ISSUE TITLE
Crash when screen size hits 0

### ISSUE THREAD

**Issue by chbachman** [libgdx/libgdx#2651] opened 2014-12-16 23:56 UTC
Running a Macbook Pro, OSX Yosemite
While running, if the screen size ever hits 0, e.g.: 

![screen shot 2014-12-16 at 5 52 19 pm](https://cloud.githubusercontent.com/assets/6267043/5464335/891e650e-854c-11e4-8ed3-36fe9b6a9560.png)

the game crashes. 

Log is here: http://pastebin.com/v1FZ5C2d

I have not found a way to set a minimum screen size, or a way to prevent this from happening. Either of these would work. As it currently stands, I have to have code in resize to prevent it from getting that small. 

Sorry if this has been reported before, I did a quick search, and asked around on the IRC channel, and was told that there was no way to set a minimum screen size, nor did they know why this was happening.

**Comment by MobiDevelop** [comment] 2015-01-24 05:09
Can't reproduce on Windows or Linux (Fedora 21). Don't have a Mac to try with. Can someone else with a Mac try to reproduce, please?

**Comment by siondream** [comment] 2015-01-25 14:53
This is most likely also an issue with LWJGL. Cannot confirm though as I don't have a Mac.

**Comment by chbachman** [comment] 2015-01-26 02:16
A workaround could possibly be a setting for a minimum screen size, which I do not believe that libGDX has (although I could be wrong). Is this feasible?

**Comment by badlogic** [comment] 2015-02-02 17:31
This is an issue in LWJGL. I can reproduce it on my Mac. That's something the LWJGL guys need to fix. Which it is, in LWJGL 3, as they use the more stable GLFW. We'll need to write a new backend for that. I'm closing this out as it's not super high priority and will be fixed eventually. Thanks for reporting!

**Closed by badlogic** 2015-02-02 17:31 UTC
Labels: desktop
