### ISSUE TITLE
Incorrect Layout Rendering of LwjglCanvas or LwjglAWTCanvas on swing applications on Mac

### ISSUE THREAD

**Issue by julienvillegas** [libgdx/libgdx#5004] opened 2017-12-02 17:02 UTC
**Issue**

On MAC, When a LibGDX LwjglAWTCanvas  canvas is embedded in a Swing application as a Panel, it is drawn at the bottom left independently of where in the layout the canvas is added to.

This is not a commong use case but the standard LibGDX Particle Editor depends on this.

**Issue details**

Given a simple Swing layout such as the one provided below, with 4 panels.

![ok](https://user-images.githubusercontent.com/12996613/33619874-968c10f0-d9e6-11e7-9f3f-56de82f1c54a.jpeg)

I change the top right element to put inside the JPanel a LwjglAWTCanvas object showing the standard LibGDX application, it is shown in the bottom left (the red part) instead of the top right as shown below. The top right panel then is shown as black.

![error](https://user-images.githubusercontent.com/12996613/33619990-e3af712e-d9e6-11e7-890f-af4dac3abdb3.jpeg)

Here is a self contained code showing the issue.

https://github.com/julienvillegas/LibGDXSwingTest

To run is, simply run the Desktop code pointing the asset folder in the core module.

**Comment by julienvillegas** [comment] 2017-12-05 17:08
**Issue**

When a LibGDX LwjglAWTCanvas  canvas is embedded in a Swing application as a Panel, it is drawn at the bottom left independently of where in the layout the canvas is added to.

**Issue details**

If I replace the canvas element with another Swing component (Label or image) the element is shown at the right place so clearly the issue is with the LwjglCanvas/LwjglAWTCanvas element.

Given a simple Swing layout such as the one provided below:

![ok](https://user-images.githubusercontent.com/12996613/33619874-968c10f0-d9e6-11e7-9f3f-56de82f1c54a.jpeg)

I change it to replace the top right JPanel with a LwjglAWTCanvas object showing the standard LibGDX application, it is shown in the bottom left instead of the top right as shown below:

![error](https://user-images.githubusercontent.com/12996613/33619990-e3af712e-d9e6-11e7-890f-af4dac3abdb3.jpeg)

Here is a self contained code showing the issue.

https://github.com/julienvillegas/LibGDXSwingTest

To run is, simply run the Desktop code pointing the asset folder in the core module.

**Comment by Tom-Ski** [comment] 2017-12-05 21:21
Can't reproduce this on windows, perhaps try wrapping your main function with 

```java
SwingUtilities.invokeLater(new Runnable() {
   LwjglAWTCanvas canvas .... etc
});
```


https://pix.asidik.com/tomski-H2qYi6.mp4

**Comment by julienvillegas** [comment] 2017-12-06 01:02
Tried the suggested method but this does not solve the issue.
This means that LwjglAWTCanvas cannot be used on Mac at this point.
Looking into it although it reaches mey limits.

**Comment by pamel4** [comment] 2017-12-21 08:25
Hi! I've also been struggling with this issue - on OSX only of course. I'd guess it's somehow related to the platform's window manager and how the UI components are packed and updated. If you try to resize the frame with mouse the canvas jumps to the right position. Any ideas what could be the root cause?

**Comment by julienvillegas** [comment] 2018-12-28 18:00
Any chance someone can help on this? I provided the SSCCE here https://github.com/julienvillegas/LibGDXSwingTest 
Looks like this is a Mac Related issue

**Comment by selimanac** [comment] 2019-10-14 09:04
+1

**Comment by selimanac** [comment] 2019-10-15 07:10
I found a workaround for this issue by repacking on windowActivated event. I also set the `setMinimumSize` little smaller then the `setSize`

```java

frame.setSize(605, 305);
frame.setMinimumSize(new Dimension(600, 300));


addWindowListener(new WindowAdapter() {
        @Override
        public void windowActivated(WindowEvent e) {
            pack();
        }
    }
});
```

**Comment by crykn** [comment] 2020-12-06 16:02
It doesn't really seem worth to fix this issue, considering LWJGL2 itself is no longer actively developed. There is a workaround mentioned above and all future readers should consider moving to the lwjgl3 backend and Lwjgl3AwtCanvas, as soon as #6247 is merged.

**Closed by crykn** 2020-12-06 16:02 UTC
Labels: LWJGL2, bug, desktop
