### ISSUE TITLE
NetJavaImpl$HttpClientResponse.getResultAsStream shouldn't return silently an error stream

### ISSUE THREAD

**Issue by fwolff** [libgdx/libgdx#3567] opened 2015-11-16 10:24 UTC
Hi,

The implementation of NetJavaImpl$HttpClientResponse.getResultAsStream is as follow:

```
public InputStream getResultAsStream () {
    return getInputStream();
}
...
private InputStream getInputStream () {
    try {
        return connection.getInputStream();
    } catch (IOException e) {
        return connection.getErrorStream();
    }
}
```

I don't see any - good, reliable - way to figure out if the returned stream is the expected one or not... Is there any rational behind this?

Thanks,
Franck.

**Comment by FyiurAmron** [comment] 2015-11-16 18:33
honestly, all the suppressing going in in `NetJavaImpl` (and related HTTP classes) is IMO a very bad thing... it made the debugging of https://github.com/libgdx/libgdx/issues/3226 and couple of other HTTP issues I encountered a real PITA; if it was my decision, I'd add a boolean flag, allowing toggling the exception suppression *off* if needed; for the time being, I just forked the code and added the exception propagation by hand.

If somebody decides it's worth it and does a PR - he gets my most sincere thumb up for it.

**Comment by badlogic** [comment] 2015-11-16 23:28
Yeah, that's no good. We should fix it proper and get rid of the old behavior.

**Comment by MrStahlfelge** [comment] 2020-09-05 21:22
Duplicate of #4700

**Closed by MrStahlfelge** 2020-09-05 21:22 UTC
Labels: android, desktop, duplicate, enhancement, ios
