### ISSUE TITLE
1.11 Cannot set color on labels using the new default `lsans-15.fnt` font

### ISSUE THREAD

**Issue by jonatino** [libgdx/libgdx#6933] opened 2022-07-22 00:40 UTC
Please ensure you have given all the following requested information in your report.

#### Issue details
After upgrading to 1.11, our previous white colored arial-15.fnt is now a dark brown/black and regardless of the label style, it will always stay that color.

Screenshot (1.11):
https://i.imgur.com/KE8bpsJ.png

Screenshot (1.10):
https://i.imgur.com/EJ0DHU9.png

#### Reproduction steps/code
Create a new screen with the following code and display it on a stage.
```
        font = new BitmapFont();

        label = new Label("Checking for updates...", new Label.LabelStyle(font, Color.WHITE));
        label.setAlignment(Align.bottom);
        stage.addActor(label);
 ```
 
#### Version of libGDX and/or relevant dependencies
1.11.0

#### Stacktrace
N/A

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] macOS

**Comment by tommyettinger** [comment] 2022-07-22 02:40
...No? I'll reproduce your example exactly, but I've been using LSans in my tests for a while now without issues. As you can see here, in the left column, which uses only `BitmapFont` on `Label`s with backgrounds: ![](https://i.imgur.com/VJsMMHA.png) Most likely, something in your code is changing the `Batch` color or the `BitmapFont`'s color and it isn't being changed back to white. The internal mechanics for font color changed a while before LSans was brought in, during a series of complex updates to GlyphLayout and BitmapFont. [The code I used to make the above screenshot is here](https://github.com/tommyettinger/textratypist/blob/0f56731cc664618e3b8f3ab2e90b4c5728619bbe/src/test/java/com/github/tommyettinger/textra/LabelRotationTest.java).

If that isn't enough, [I exactly reproduced the code you posted](https://github.com/tommyettinger/textratypist/blob/9e7f132d6b9a371a55f9226b2a1e8f747e96f129/src/test/java/com/github/tommyettinger/textra/Issue6933Test.java) and it doesn't have any issue: ![We're good.](https://i.imgur.com/Xw7WxVy.png)

I'm closing this issue, because I can't reproduce it as posted. If you have more information on what's going on in your code, then we can reopen, but it looks like you didn't run your own issue-reproduction code (in part because it isn't an SSCE).

**Closed by tommyettinger** 2022-07-22 02:40 UTC

**Comment by Frosty-J** [comment] 2022-07-22 09:19
Hm, yeah, doesn't seem hugely likely the font itself is to blame, though I do wonder what may have changed in 1.11.0 to cause something like this. Needs more info.

Since it's pretty hard to see against the dark background, especially on mobile where even finding the image is a challenge due to Imgur's absurd levels of shittiness, here's the text ("Checking for updates...") with increased contrast, uploaded to GitHub by dragging it into this comment:

![](https://user-images.githubusercontent.com/60154347/180406722-5b80521c-d6fe-4ec9-a7a5-8a16fa057e23.png)

Might be worth checking the texture has loaded in properly? Black rectangles are never a good sign.

**Comment by tommyettinger** [comment] 2022-07-22 09:32
Yeah, the Texture used by the BitmapFont could easily be disposed, which would cause this.

**Comment by jonatino** [comment] 2022-07-22 17:37
> Yeah, the Texture used by the BitmapFont could easily be disposed, which would cause this.

Which shouldn't happen by changing a version number hence the issue.

**Comment by tommyettinger** [comment] 2022-07-22 20:50
Well, try running your own reproduction example without any other code and see if you can reproduce still. This is not something that has happened in anyone else's code.

**Comment by tommyettinger** [comment] 2022-07-22 21:16
I would try tracking down where in your original game you could be calling dispose() before or during the screen you showed; maybe something changed in the disposal logic for some class, but there's no way we can tell what it could be without looking at your code.
