### ISSUE TITLE
*.wav music not played in deployed .jar

### ISSUE THREAD

**Issue by Naxos84** [libgdx/libgdx#5254] opened 2018-06-07 20:59 UTC
Please ensure you have given all the following requested information in your report.

#### Issue details
I built a very simple prototype of a game. I have some .ogg / .wav / .mp3 files for audio. During debugging in IDEA everything is fine. When the application is deployed only .ogg and .mp3 music files are played.

#### Reproduction steps/code
Music menuMusic = Gdx.audio.newMusic(Gdx.files.internal("audio/menu_screen_loop.wav"));
menuMusic.play();
<----- this does not work

Music gameMusic = Gdx.audio.newMusic(Gdx.files.internal("audio/DST-DustLoop.mp3"));
gameMusic.play();
<------ this does work.

https://github.com/Naxos84/TestRepo.git

#### Version of LibGDX and/or relevant dependencies
Libgdx 1.9.8
Gradle Wrapper: https\://services.gradle.org/distributions/gradle-2.14.1-bin.zip

#### Stacktrace
```java
No Stacktrace available
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [ ] MacOS

I could not test on other platforms yet.

**Comment by Naxos84** [comment] 2018-06-08 06:01
Link to a minimal example:
https://github.com/Naxos84/TestRepo.git

To deploy I use the gradle task desktop/Tasks/other/dist (from within IDEA)

**Comment by mgsx-dev** [comment] 2018-06-08 09:33
@Naxos84 The SSCCE is perfect and i was able to reproduce it with eclipse on Linux (you can add linux as affected platform as well).

I investigate by debugging the jar directly with jdwp : `java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=1044 -jar desktop-1.0.jar`.
I was able to reproduce it as well directly from eclipse by packaging the wave file into a jar and added it to the classpath.

The issue is related to the InputStream type : 
* from IDE (with gdx internal file) this is java.io.FileInputStream
* from IDE (with gdx classpath file) this is java.io.BufferedInputStream
* from a JAR this is sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream with an underlying java.util.zip.ZipFile$ZipFileInflaterInputStream)

The first and second one reads directly the whole buffer size (40960 bytes) but the third one (from JAR) only read 8182 or 8153 bytes which are not aligned with channels and bitrate (and maybe too small). Then OpenAL return error and the sound is just stopped.

Problem occurs [here](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/Wav.java#L136) and [here](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALMusic.java#L254)

To be sure, i watch how MP3 and OGG behaves : 
* OGG libgdx decoder reads 40960 bytes (the whole buffer)
* MP3 (javazoom) reads 36864 bytes (almost the whole buffer but frame aligned)

I think there is not really workaround for you now : you could extract the wav file at runtime or don't use WAV for music but it's far to be a solution obviously.

I'll try to fix this and provide a PR.

**Comment by mgsx-dev** [comment] 2018-06-08 10:32
@Naxos84 fixed ! I tried with your wave file and it works perfectly (playing and looping correctly).
You have to wait until it's merged and available in snapshot.

**Closed** 2018-06-09 06:37 UTC
