### ISSUE TITLE
LibGDX project created using the tool giving errors

### ISSUE THREAD

**Issue by ninesw** [libgdx/libgdx#6726] opened 2021-12-10 12:18 UTC
Please ensure you have given all the following requested information in your report.

#### Issue details
When I run my project, I get this error telling me its failed to load a library:
<img width="894" alt="Screenshot 2021-12-10 at 12 02 18" src="https://user-images.githubusercontent.com/85068023/145571290-66165afb-1cbf-49b3-9ef4-592510cc1636.png">

I also downloaded Lwjgl and added all the class files to my project structure but it still did not fix this
When I added the lwjgl to libraries this is how it added:
<img width="660" alt="Screenshot 2021-12-10 at 12 16 57" src="https://user-images.githubusercontent.com/85068023/145572872-ce941ada-1df4-4b39-87f1-87225af7e3bb.png">
(some more below, the screenshot is cut off)

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue. This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_
I created a libgdx project using the setup tool, selected only the desktop option, and selected all the extensions.
the external libraries added
<img width="622" alt="Screenshot 2021-12-10 at 12 15 31" src="https://user-images.githubusercontent.com/85068023/145572695-53c334d9-3293-47d5-92ac-4ec777468632.png">
<img width="649" alt="Screenshot 2021-12-10 at 12 15 46" src="https://user-images.githubusercontent.com/85068023/145572720-5ad67e06-9028-43ec-b408-0dd22d194720.png">

#### Version of libGDX and/or relevant dependencies
_Please provide the version(s) affected._
used the latest nightly release

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib
	at org.lwjgl.system.Library.loadSystem(Library.java:162)
	at org.lwjgl.system.Library.loadSystem(Library.java:62)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:41)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:91)
	at com.mygdx.game.DesktopLauncher.main(DesktopLauncher.java:12)

```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] macOS

**Comment by Frosty-J** [comment] 2021-12-10 14:23
While I don't know what the issue is, I can tell you LWJGL is a Gradle dependency and shouldn't be manually added, and that adding all the extensions isn't a good idea (more likely to run into errors and the project will be slower to download/index/build).

Does your Mac have an M1 or Intel CPU? gdx-liftoff 1.10.0.9-SNAPSHOT [has M1 support](https://github.com/tommyettinger/gdx-liftoff/commit/bcebcfb7f3adce4e4d31962a38d3098ff8af63f0), so it's a pretty good test (but the projects it generates don't support M1, so if it does work it's still not useful for libGDX development).

**Comment by ninesw** [comment] 2021-12-10 21:05
> 

HI, thanks for the suggestion,
Does this mean that I cannot use LibGDX for on my m1 MacBook, currently?

**Comment by Frosty-J** [comment] 2021-12-10 21:48
Hold on a minute, I think it should work after changing `gdxVersion` to `'1.10.1-SNAPSHOT'` in `build.gradle`. #6721 has been merged.

**Comment by tommyettinger** [comment] 2021-12-10 22:26
M1 Macs aren't supported by any stable release of libGDX yet, but they are pretty much supported by the current snapshot, `1.10.1-SNAPSHOT` . The beta version Frosty linked of gdx-liftoff should run correctly on an M1 Mac, even if you have an ARM64 JDK (the native type for your machine, instead of an x86_64 JDK, which would be emulated with Rosetta). If you give `1.10.1-SNAPSHOT` as the version to gdx-liftoff, then the projects it generates should build and run on your Mac. You don't need to self-build LWJGL 3.3.0 unless you're making some changes to it. If you do need to change LWJGL 3.3.0, you can use the steps that gdx-liftoff itself follows (or followed) to ensure 3.3.0 was used even before libGDX used it: https://github.com/tommyettinger/gdx-liftoff/blob/24765d3728deba96a9dda361d414ab359927ef60/build.gradle#L60-L100 If your `lwjgl3Version` is defined in `gradle.properties` as the custom name you have for your self-built version, it will use that self-built version.

**Comment by ninesw** [comment] 2021-12-10 23:43
> Hold on a minute, I think it should work after setting `gdxVersion` to `'1.10.1-SNAPSHOT'` in `build.gradle`. #6721 has been merged.

HI, thanks a lot, this solved by problem and the program works fine
however in the console I get these warnings:
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings

Is this anything to worry about.
Thanks for you help again, I've been trying to get solutions for this for so long.

**Comment by tommyettinger** [comment] 2021-12-10 23:53
Yeah, those are fine. Eventually libGDX will update to Java 8 entirely, but for now, RoboVM only has partial Java 8 support. That means libGDX itself sticks to Java 7 internally, despite it producing those warnings on newer JDKs. If you don't target iOS or rather-old Android versions, you can safely use Java 8, and if you only target desktop platforms (LWJGL3), then you can use as high as Java 17 with a gdx-liftoff project. If targeting desktop, the right way to distribute your game on Mac involves bundling a JRE with your game, which Packr or the built-in jpackage tools can do. If you bundle a JRE, then no one running your game has to know what Java they have installed (since you provide one).

But if you do target iOS, you should stick with version 7 until some future RoboVM update that gets Java 8 compatible with iOS.
You can ignore the warnings unless years in the future, Java 7 is entirely removed and we for whatever reason need to use a much newer JDK version. Java 17 is LTS (long-term supported) by Oracle, so Java 7 will have to be supported as much as JDK 17 supports it now for at least 3 years.

This seems to be resolved now, so hooray! I'll close this.

**Closed by tommyettinger** 2021-12-10 23:53 UTC
