### ISSUE TITLE
modelInstance.getRenderable throws an error

### ISSUE THREAD

**Issue by little-brother** [libgdx/libgdx#7211] opened 2023-08-15 21:22 UTC
I try to get renderable part of a model instance like below
```
ModelLoader loader = new G3dModelLoader(new JsonReader(), new AbsoluteFileHandleResolver());
model = loader.loadModel(Gdx.files.internal("model.g3dj"));
modelInstance = new ModelInstance(model);

Renderable renderable = new Renderable();
modelInstance.getRenderable(renderable);
Gdx.app.log("TEST", renderable.toString());
```

The `modelInstance.getRenderable(renderable);`-call falls with an error
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: index can't be >= size: 0 >= 0
```

I made some research. Underhood `getRenderable(renderable)` calls `getRenderable(renderable, modelInstance.nodes.get(0), modelInstance.nodes.get(0).parts.get(0))`. In my model `modelInstance.nodes.get(0).parts.get(0))` (the third argument) is empty. So the last `.get(0)` throws this error.
The modelInstance is rendered because render gets data from `modelInstance.nodes.get(0).parts.getChild`. So the solution is to use the first child
```
Node node0 = modelInstance.nodes.get(0);
NodePart nodePart0;
if (node0.parts.size > 0)
	nodePart0 = node0.parts.get(0);
else
	nodePart0 = node0.getChild(0).parts.get(0);

Renderable renderable = new Renderable();
modelInstance.getRenderable(renderable, node0, nodePart0);
Gdx.app.log("TEST", renderable.toString());
```
But it's a little bit clumsy.

I don't know what is wrong with my model. I made it in SketchUp, exported as fbx and converted by `fbx-conv`.

The g3dj model and the complete project - [test.zip](https://github.com/libgdx/libgdx/files/12353086/test.zip)

LibGDX 1.12.0

**Comment by JamesTKhan** [comment] 2023-08-22 20:05
So the issue is because your model, the way it is structured, does not have any parts on the first node, but its children does have parts. The `getRenderable()` method documentation says 

```java
	/** @return The renderable of the first node's first part. */
	public Renderable getRenderable (final Renderable out) {
	```
	
But, the way your model is structured, the first node has no parts. Only children with parts. Instead you can use `getRenderables()`
method which traverses the node, checks if it has parts first, then also checks the children.

I modified your project to use getRendables and your model then loaded.

**Comment by little-brother** [comment] 2023-08-23 20:28
The goal is not to make the code works. I just marked that `getRenderable` can fail with some valid model instances. In my opinion it shouldn't happen.

**Comment by JamesTKhan** [comment] 2023-08-23 21:34
> The goal is not to make the code works. I just marked that `getRenderable` can fail with some valid (loaded) model instances. By my opinion it shouldn't happen.

I think it is confusing and the error is not helpful at a glance, at the same time, the method is doing exactly what the documentation on the method says it does and it has been the same way since 2013 from what I can tell.

Maybe an error could be thrown here to explain the problem in this case rather then letting it hit an  `IndexOutOfBoundsException`.

In your opinion, how do you think it should behave? Find the first **valid** node part by searching the nodes and children until it finds one? Or throw an error with a better description? Or something else.

**Comment by little-brother** [comment] 2023-08-23 21:41
> Find the first valid node part by searching the nodes and children until it finds one?

This one.

**Comment by JamesTKhan** [comment] 2023-08-23 21:51
> > Find the first valid node part by searching the nodes and children until it finds one?
> 
> This one.

I am open to the idea since it makes it more user friendly and _should_ still behave the same for existing implementations.

**Comment by JamesTKhan** [comment] 2023-09-10 18:39
Just following up. Are you planning to put in a PR for this? I'd be willing to approve it (but it will require another approver as well)

**Comment by little-brother** [comment] 2023-09-27 18:11
> Are you planning to put in a PR for this?

Nope. I think it's just a minor changes that can be implemented by any regular member.

**Comment by mgsx-dev** [comment] 2023-11-13 12:09
see : https://github.com/libgdx/libgdx/blob/a25ceaddd8e9ea740b7e50e486ea4f815d2a3f58/gdx/src/com/badlogic/gdx/graphics/g3d/ModelInstance.java#L360
Javadoc is clear : if a model doesn't have any Node or first node doesn't have any NodePart, this method shouldn't be called at the first place. TBH, i never needed this (too specific) method and i'm not sure opener really needs it.

@JamesTKhan I propose to close this non-issue.

**Comment by JamesTKhan** [comment] 2024-02-01 16:45
Closing this one out, I agree with MGSX that the Javadoc explains the methods functionality.

**Closed by JamesTKhan** 2024-02-01 16:45 UTC
Labels: 3D
