### ISSUE TITLE
Faster batching of Array<Decal>

### ISSUE THREAD

**Issue by graham01** [libgdx/libgdx#3265] opened 2015-07-09 15:31 UTC
Been experimenting and having some performance issues with DecalBatch as mentioned [on the forum](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=19910). I modified the render() method of DecalBatch to directly draw an Array<Decal> to avoid add() and flush() methods. It does not solve my issue (still have poor performance with as little as 800 identical decals) but it does offer 5-15fps increase when benchmarking across 4 Android devices, so it could be useful for those wanting to batch a single Decal Array. 

Code as follows, it was just a very quick cut and paste of existing code so I am sure it is still open to some modification and optimisation. 

    public void renderDecalArray (Array<Decal> decals) {

        groupStrategy.beforeGroups();
        groupStrategy.beforeGroup(1, decals);
        ShaderProgram shader = groupStrategy.getGroupShader(1);
        // batch vertices
        DecalMaterial lastMaterial = null;
        int idx = 0;
        for (Decal decal : decals) {
            if (lastMaterial == null || !lastMaterial.equals(decal.getMaterial())) {
                if (idx > 0) {
                    flush(shader, idx);
                    idx = 0;
                }
                decal.material.set();
                lastMaterial = decal.material;
            }
            decal.update();
            System.arraycopy(decal.vertices, 0, vertices, idx, decal.vertices.length);
            idx += decal.vertices.length;
            // if our batch is full we have to flush it
            if (idx == vertices.length) {
                flush(shader, idx);
                idx = 0;
            }
        }
        // at the end if there is stuff left in the batch we render that
        if (idx > 0) {
            flush(shader, idx);
        }

        groupStrategy.afterGroup(1);
        groupStrategy.afterGroups();
    }

So where one would have;

    for(Decal d:decals){
        dBatcher.add(d);
    }
    dBatcher.flush();

It cans simply be replaced with;

   dBatcher.renderDecalArray (decals);

Hope this can be of some use!

**Comment by scientistnm** [comment] 2015-07-16 22:19
Any news on this one?

**Comment by xoppa** [comment] 2015-07-17 18:11
Not sure what the issue is. Looks like @graham01 wants to share his experiences (which is, of course, always appreciated). However, I'm afraid that reporting an issue is not the way to reach the right audience for that (the forum or wiki instead might be better suited for that).

If this is a contribution to `DecalBatch` then could you please [send a PR](https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md) instead? I'm sure more users will benefit from it in that case instead of having an issue report.

If this is indeed an actual issue report then please provide the information required to reproduce the issue.

I'm afraid that we won't be able to keep issues open just to share experiences.

**Comment by graham01** [comment] 2015-07-17 19:43
HI @xoppa , the above is not the solution to my problem, it just offers slightly better performance for a more limited case. 

I posted my issue/question on the forum (link in first post) with more details but it didn't get much response. I am guessing it is just to be expected since someone said there was no problem with my code. 

Honestly, I tried to send a PR, but the whole comparing master and gradle thing confused me. I know, I don't belong here...

**Comment by xoppa** [comment] 2015-07-17 20:06
Thanks! Just to be sure: Is there an actual issue with libgdx that you're reporting or should this issue be closed? If there's an issue then, as said, please include the [sscce](http://sscce.org) (if you already posted that *single class test* on the forum then it should be easy to copy it over here).

**Comment by graham01** [comment] 2015-07-17 20:46
Constructor:
gas = Assets.manager.get("Decals/gas.png", Texture.class);
gas.setFilter(Texture.TextureFilter.Linear, Texture.TextureFilter.Linear);
gas_spr = new Sprite(gas);
for(int i = 0; i < noOfGasParticles;i++){
    Decal gas = Decal.newDecal(particleSize,particleSize,new TextureRegion(gas_spr),false);
    float col = (70-Math.abs(300f- gas_radii[i]))/70f;
    Color tint = new Color(1.0f,0.3f,col,0.5f);
    gas.setColor(tint);
    gas.setBlending(GL20.GL_SRC_ALPHA, GL20.GL_ONE);
    gas_decals.add(gas);
}

Render Method:
int k = 0;
for(Decal d: gas_decals) {
    d.setPosition(gas_positions[k]);
    d.lookAt(cam.position,cam.up);
    DB.add(d);
    k++;
}
DB.flush();


I was hoping to have several thousand, however I am stuck at about 800, since on all testing devices the FPS drop from this is not too bad. 800+ and I am having major FPS drops, even with everything else removed (such as 3D models) and making it even more basic - standard blending, nearest mig/mag filter, not changing decal colour, not updating decal positions and directions every frame. My original gas.png is only 10x10px, but even making that 1x1 or 100x100 has absolutely no effect.

It's just in the original post by the author of DecalBatch, he did some benchmarking to show it was even faster than SpriteBatch. Although Mario and others pointed out some flaws in the results, I think they settled on it being just as good. 

All my other screens where I just have SpriteBatch, whatever I do and draw I get amazing performance and solid 60fps on most devices. I did some very small benchmarking myself on SpriteBatch a while ago, drawing a 200x200 Sprite in a grid 100*1000 with some pinch-to-zoom control on the camera and performance was still excellent, really hoped DecalBatch would perform the same.

**Comment by xoppa** [comment] 2015-07-17 20:53
Thanks. I guess that means there's an actual issue with libgdx you want report. Thanks for reporting an issue, it is highly appreciated. Unfortunately it looks like you didn't follow the link I referred to twice. Please include the information required to reproduce the issue. You might also want to have a look at: https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code.

**Comment by graham01** [comment] 2015-07-17 21:21
Don't thank me, I am wasting your time with my lack of understanding :( 

I though't the snippets I posted above were what you are asking for. I'll write up a runnable screen with just the necessary parts.

**Comment by xoppa** [comment] 2015-07-17 21:36
Okay, I'll go ahead and close this issue then. When you're ready then please open a new issue and make sure to include the required information (as I linked to before) as well as how (the actual steps you took) you've verified that this is indeed an issue with libgdx.

**Closed by xoppa** 2015-07-17 21:36 UTC
