### ISSUE TITLE
Different Preferences Mechanisms on different platforms

### ISSUE THREAD

**Issue by LeftHandFreeStudio** [libgdx/libgdx#5665] opened 2019-06-14 15:57 UTC
Preferences not working as expected on iOS.

#### Issue details
When I use a method Gdx.app.getPreferences("test"); to get Preferences object on Android/Desktop, every time I call it, I get the same preferences but on iOS every call gets me a new object like so:

Preferences test1 = Gdx.app.getPreferences("test");
Preferences test2 = Gdx.app.getPreferences("test");

test1.puInteger("test",1);
test1.flush();
int val = test2.getInteger("test");

value of val at this point is 0 on iOS and 1 on Desktop/Android

I think the implementations should behave equally.

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.9
roboVM 2.3.6

#### Please select the affected platforms
- [ ] Android
- [ x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment] 2019-06-14 17:22
The method `Gdx.app.getPreferences(String)` creates a new Preferences instance every time its called (both on Android and iOS). The different behaviour is not by design, it just happens that on Android the underlying SharedPreferences object that holds the data is shared if the name is the same).

`Gdx.app.getPreferences(String)` should only be called once to create the Preferences, keep a reference and use it everywhere else in the code. 

It would probably make sense it cached the Preferences objects by key/name, but I'm afraid changing that would break backwards compatibility. Maybe we could consider renaming it.

**Comment by LeftHandFreeStudio** [comment] 2019-06-14 17:40
Maybe it would be worth mentioning here
https://github.com/libgdx/libgdx/wiki/Preferences
just to make it clear?

**Comment by Tom-Ski** [comment] 2019-06-16 19:36
Sure, feel free to contibute. As this is already stated in the javadocs, closing this issue.

**Closed by Tom-Ski** 2019-06-16 19:36 UTC
