### ISSUE TITLE
Table.addActorAt breaks the Table

### ISSUE THREAD

**Issue by SomeTroglodyte** [libgdx/libgdx#7103] opened 2023-03-12 12:09 UTC
#### Issue details
`Table.addActorAt` is callable and shows the underlying JavaDoc suggesting it might do something useful - actually, it's just `Group.addActorAt` and _breaks_ the Table, because none of the Table-specific info is updated, specifically `cells`.

#### Suggestions
override it to `throw` some "not implemented" and make sure the JavaDoc shows just that
-or-
override and fully implement
-or-
Ignore me :zany_face:  - I just want to share the insight

#### Reproduction steps/code
Maybe later. Found as [bug in Unciv's TabbedPager widget](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/components/TabbedPager.kt#L624) - obviously I ran into a misunderstanding there and never tested that variant of its API.

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [ ] macOS

**Comment by HydrolienF** [comment] 2023-04-24 09:18
Table.addActor() also break table.
I think both should throw UnsupportedOperationException or call Table.add(Actor actor) that actually work.

**Comment by HydrolienF** [comment] 2023-04-24 09:27
Since Group methods to add actor can't be override and return a Cell we will need a new methode to add actor to a specifique location. Something as
```java
public <T extends Actor> Cell<T> addAt (int index, @Null T actor)
```

**Comment by HydrolienF** [comment] 2023-04-24 10:20
```java
public class Table extends WidgetGroup {
	@Override
	public void addActor (Actor actor) {
		add(actor);
	}
	@Override
	public void addActorAt (int index, Actor actor) {
		addAt(index, actor);
	}
	@Override
	public void addActorBefore (Actor actorBefore, Actor actor) {
		addBefore(actorBefore, actor);
	}
	@Override
	public void addActorAfter (Actor actorAfter, Actor actor) {
		addAfter(actorAfter, actor);
	}

	public <T extends Actor> Cell<T> add (@Null T actor) {
		// ... (already implemented)
	}

	public <T extends Actor> Cell<T> addAt(int index, @Null T actor) {
		// TODO add the actor to the stage at the specified index
		return null;
	}
	public <T extends Actor> Cell<T> addBefore(Actor actorBefore, @Null T actor) {
		// TODO add the actor to the stage before the specified actor
		return null;
	}
	public <T extends Actor> Cell<T> addAfter(Actor actorAfter, @Null T actor) {
		// TODO add the actor to the stage after the specified actor
		return null;
	}
}
```

Maybe something like that ?
It give 4 methods that return Cell as add(...) currently do.
It override the 4 Group methods to make sur Table can't be break by calling Group methods.
The override do add Actor as needed. (We can't override & return Cell)

**Comment by HydrolienF** [comment] 2023-04-24 10:24
For other class that extends WidgetGroup (that extends Group), it have been choose to throw exceptions when it was breaking it:
```java
/** @deprecated ScrollPane may have only a single child.
	 * @see #setActor(Actor) */
	@Deprecated
	public void addActor (Actor actor) {
		throw new UnsupportedOperationException("Use ScrollPane#setActor.");
	}
```

**Comment by mgsx-dev** [comment] 2023-04-24 10:48
> table.addActor(), table.addActorBefore(), table.addActorAfter() also break table. I think the 4 method should throw UnsupportedOperationException or call table.add(Actor actor) that actually work.

Definitely not, we use Table.addActor sometimes in order to add an actor out of the table layout flow, it's a pretty common use case actually. Any change to these methods would be an unwanted breakage in a lot of games.
These methods doesn't "break" Table, they have their specific usage.

**Comment by HydrolienF** [comment] 2023-04-24 12:01
OK, so we need to keep same behavior.
Instead of throwing exceptions or link to add(), we can add fiew lines in javadocs to warn user that it won't work as add() ?
```java
/** Adds an actor as a child of this group, removing it from its previous parent. If the actor is already a child of this
 * group, no changes are made.
* This method won't edit actor position or size.
* To add actor in table with table default behavior use {@link #add(Actor)}.
 */
@Override
public void addActor (Actor actor) {
    super.addActor (actor);
}
```

**Comment by mgsx-dev** [comment] 2023-04-24 12:18
no, it's already explained in the Table javadoc (at class level) and the other statement (won't edit actor position or size) is not so good, we should document what the methods does, not what the method doesn't do. And it would also prevent sub classes to change actor position and size.

I think we could close the issue now.

**Comment by HydrolienF** [comment] 2023-04-24 12:26
well OK

**Closed** 2023-04-24 12:29 UTC

**Comment by NathanSweet** [comment] 2023-04-24 17:41
Yep, I have apps that rely on adding an actor to a table without having the table constraints applied. It doesn't break anything, though it may be somewhat surprising if `addActor` is accidentally used when `add` was intended.

**Comment by raeleus** [comment] 2023-04-24 21:51
Window (just a very fancy table) is a good example of when using addActor() is more appropriate than add(). The title table is positioned in the top padding of background drawable.
