### ISSUE TITLE
Invalid default alpha blending in particle system

### ISSUE THREAD

**Issue by imcasper** [libgdx/libgdx#6223] opened 2020-10-14 09:39 UTC
Invalid particle blending (Can see in 3d particle editor: https://github.com/libgdx/libgdx/wiki/3D-Particle-Effects )

![изображение](https://user-images.githubusercontent.com/23495732/95970135-45eb8900-0e18-11eb-9d39-4a7da5d9346e.png)

By default, blending works like in the screenshot on the right.
(blending: GL_ONE, GL_ONE_MINUS_SRC_ALPHA)

I expect behavior like the screenshot on the left.
(blending: GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)

You can also see the problem on the default particle system (left -- good, right -- bad):
![изображение](https://user-images.githubusercontent.com/23495732/95970926-33be1a80-0e19-11eb-9222-8d4209cbf0f8.png)

for fix can change blendingAttribute in default constructor in class BillboardParticleBatch

version libgdx: 1.9.12

**Comment by mgsx-dev** [comment] 2020-10-14 11:43
@imcasper what make you think the default blending is wrong? default is a kind of additive blending, it's an arbitrary choice. You can change it in your code so default blending is not an issue. Maybe what you want is a way to change blending in particle editor, no?

**Comment by imcasper** [comment] 2020-10-14 15:57
From the user's point of view...
Ugly sharp edges (see top-right image) instead of a smooth transition.

Particle image:
 ![pre_particle](https://user-images.githubusercontent.com/23495732/96014061-9978c980-0e4e-11eb-9931-69fef1f6eb50.png)

In any case, the choice of blending will provide the necessary possibilities.

**Comment by mgsx-dev** [comment] 2020-10-14 17:11
This is the expected behavior with this default additive blending. Default gradient is not perfectly red, it's a bit orange which make it yellow-ish with additive mix. And the pink color is because of a transparent red color over the blue axis.

It's not a good idea to change Batch default blending, it would break existing code that depends on it. Current default blending is an arbitrary choice (and not a bad one IMO) so there is no reason to change it to another arbitrary mode.

Since blending mode can be changed both in the Batch and in the Editor (via my PR), i think the issue will be resolved once the PR get merged.

**Closed** 2020-12-04 11:31 UTC
Labels: 3D, tools
