### ISSUE TITLE
Gradle desktop:run hanging between 87 and 90% on Mac

### ISSUE THREAD

**Issue by rarnoldmobile** [libgdx/libgdx#5258] opened 2018-06-09 02:20 UTC
#### Issue details

When running a fresh project on Mac osx - the build will hang anywhere from 87% to 90%.  This behavior seems to happen with both java based projects and Kotlin projects.

No errors are logged, only the behavior of gradle reporting XX% Executing -and no further actions.

Happens in both ide environments, as well as command line.  It seems to consistently get to 87% for pure java projects, and 90% when the Kotlin option is selected in the setup jar.

Also reported here: https://github.com/libgdx/libgdx/issues/5240 by @burf2000 -a new issue was requested for this new error.

#### Reproduction steps/code
* create a project with the setup jar, with the options:
  *  Sub Projects: Desktop
  *  Extensions: Box2d
* generate project
* in terminal - attempt: ./gradlew desktop:run

#### Version of LibGDX and/or relevant dependencies
libgdx version: 1.9.8
java version: 1.8.0_171
grade wrapper version: 4.6

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by tommyettinger** [comment] 2018-06-09 19:40
This was noted a few times on IRC as well, always on MacOS (see https://echelog.com/logs/browse/libgdx/1528408800 ). oseph mentioned a memory message coming up repeatedly when gradlew is run with `--debug --info`:
`[22:32:41] <oseph> at the 87% hang point im seeing a lot of these "[DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 1398276096, Committed: 440401920}"`

Could a required download for a MacOS native lib be failing to complete? Keystore/certificate stuff maybe blocking a download?

**Comment by electronstudio** [comment] 2018-06-20 03:31
When LibGDX 1.9.8 was first released it had a working gdx-setup.jar.  At some point since then gdx-setup.jar was updated to a version that generates broken projects.  Since gdx-setup.jar has no version number you can't tell which one you have :-(

The problem is in the generated file desktop/build.gradle.  These lines are added:
`if(Os.isFamily(Os.FAMILY_MAC))`
 `jvmArgs += "-XstartOnFirstThread"`

The reason they were added is probably because they are required for LWJGL3.  However they break the desktop:run task.  Solution is to delete them.

**Closed** 2018-06-20 05:46 UTC

**Comment by richardpenman** [comment] 2021-07-08 20:55
I encountered this stall problem when following these instructions for lwjgl3:
https://github.com/libgdx/libgdx/wiki/Starter-classes-and-configuration#desktop-lwjgl3

Restoring to the default worked.
