### ISSUE TITLE
Persian support

### ISSUE THREAD

**Issue by siml173** [libgdx/libgdx#4413] opened 2016-11-09 12:00 UTC
why Libgdx doesn't support complex script like Persian?
can you add this feature for lots of programmers that put Libgdx away just for this reason?

**Comment by xoppa** [comment] 2016-11-09 12:26
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
Please follow the issue template as you were requested when opening this issue.
Although it's unclear what you mean, I guess this is a duplicate of #1589.

**Closed by xoppa** 2016-11-09 12:26 UTC

**Comment by arezaee** [comment] 2018-05-16 08:59
hi, I just want to say, somebody has done it:
https://github.com/CrowniAPIs/libGDX-RTL-Language

**Comment by ahmady173** [comment] 2018-05-16 09:01
thank you soooo much

**Comment by arezaee** [comment] 2018-05-16 09:06
hi, I just want to say , somebody has done it.
https://github.com/CrowniAPIs/libGDX-RTL-Language
