### ISSUE TITLE
TextArea StringIndexOutOfBoundsException thrown after clicking text

### ISSUE THREAD

**Issue by kotcrab** [libgdx/libgdx#3961] opened 2016-03-24 16:01 UTC
#### Issue details
There is some issue in `TextArea` that causes `StringIndexOutOfBoundsException` to be thrown. See reproduction steps.

#### Reproduction steps/code
1. Run standard libgdx's `TextAreaTest`
2. Move cursor to the very end of the text and start clicking repeatedly after last letter
3. After few clicks crash will occur, reproducible every time. From what I tested this doesn't happen in `TextField`.

[GIF](https://cloud.githubusercontent.com/assets/4594081/14022714/5de36ab2-f1e1-11e5-9b69-3482ecf9fc59.gif)

#### Version of LibGDX and/or relevant dependencies
Latest source

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.StringIndexOutOfBoundsException: String index out of range: 7
	at java.lang.String.charAt(String.java:646)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.wordUnderCursor(TextField.java:166)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.wordUnderCursor(TextField.java:175)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldClickListener.clicked(TextField.java:769)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldClickListener.touchUp(TextField.java:795)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

#### Please select the affected platforms
* Windows LWJGL2/LWJGL3

Others untested.

**Comment by xoppa** [comment] 2016-03-24 17:16
Duplicate of #3887

**Closed by xoppa** 2016-03-24 17:16 UTC
