### ISSUE TITLE
Creating Pixmap causes exception of UnsatisfiedLinkError

### ISSUE THREAD

**Issue by slangev** [libgdx/libgdx#6742] opened 2021-12-25 15:38 UTC
#### Issue details
Hi All,

I'm trying to create an Pixmap object for one my projects. However, when I try to do so I get UnsatisfiedLinkError. I'm running this code on a 2021 Macbook pro M1 system.

Thank you!

#### Reproduction steps/code
```java
package com.barebone.example;

import com.badlogic.gdx.graphics.Pixmap;

public class Testers {
    public static void main(String[] args){
        Pixmap frameBuffer = new Pixmap(500, 500, Pixmap.Format.RGBA8888);
    }
}
```

#### Version of libGDX and/or relevant dependencies
Gradle build
```
ext {
        gdxVersion = '1.10.0'
    }

project(":core") {
    apply plugin: "java"


    dependencies {
        implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
    }
}
```
Java version
```
java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode)
```

#### Stacktrace
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.nio.ByteBuffer com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.newPixmap(long[], int, int, int)'
        at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.newPixmap(Native Method)
        at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.<init>(Gdx2DPixmap.java:122)
        at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:137) 
        at com.barebone.example.Testers.main(Testers.java:7)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ x] macOS

**Comment by tommyettinger** [comment] 2021-12-25 22:34
This is to be expected; you're not using the framework's required structure. You don't have any dependency on a platform jar (needed for almost any desktop code to run) and don't have any backend, both of which are needed. Pixmap relies on native code being loaded, which is done by libGDX in its application lifecycle -- this only starts when an `Lwjgl3Application` or other application type is created. I can reproduce this "issue" on Windows 10, but it isn't a bug, just incorrect usage.

However, because you're on an M1 Mac, you would encounter other issues even if you fixed the structure. You should probably change `gdxVersion` from `'1.10.0'` to `'1.10.1-SNAPSHOT'`, and make sure you have the snapshot repository available (usually after `mavenCentral()`, and *not* in the `buildscript` section): 
```
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
```

I would also strongly recommend using [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff) for your project, because it works correctly with Java 17, and gdx-setup does not. Using a setup tool eliminates most of the possibility of an invalid structure like this being generated. You'll almost certainly want to use LWJGL3 if using the snapshot, since it should work with a native ARM64 JDK and not just via Rosetta (LWJGL2 may work via Rosetta, but never natively, and LWJGL3 must be version 3.3.0 or higher for it to really work, which the snapshot ensures).

Closing unless this can be reproduced on the libGDX snapshot, with a Gradle project produced by a setup tool, using the structure it generates. Merry Christmas!

**Closed by tommyettinger** 2021-12-25 22:34 UTC
