### ISSUE TITLE
Unnecessary casts in InputMultiplexer source

### ISSUE THREAD

**Issue by DeRealMorgan** [libgdx/libgdx#5765] opened 2019-08-20 11:52 UTC
The `InputMultiplexer `stores `InputProcessor`s with a `SnapshotArray<InputProcessor>`.

In all of the input events (KeyDown, KeyUp, ...) the `SnapshotArray `is used to return the contained `InputProcessor`s. Then the event is delegated to each of the Processors.

Example:
```
public boolean keyDown (int keycode) {
		Object[] items = processors.begin();
		try {
			for (int i = 0, n = processors.size; i < n; i++)
				if (((InputProcessor)items[i]).keyDown(keycode)) return true;
		} finally {
			processors.end();
		}
		return false;
	}
```

`processors.begin()` returns the contained `InputProcessor`s. They are generalized to an `Object[]` array only to be cast to a `InputProcessor` again in the for-loop.

This can and should be changed in all of the methods to this:
```
public boolean keyTyped (char character) {
        InputProcessor[] items = processors.begin();
        try {
            for (int i = 0, n = processors.size; i < n; i++)
                if (items[i].keyTyped(character)) return true;
        } finally {
            processors.end();
        }
        return false;
    }
```

Also a small note: As the `InputMultiplexer` is implementing the methods of the `InputProcessor` interface, all of these methods should be marked as `@Override` for readability.

**Comment by mgsx-dev** [comment] 2019-08-20 12:55
PR welcome :-)

**Comment by DeRealMorgan** [comment] 2019-08-20 13:33
> PR welcome :-)

@mgsx-dev is this reply meant for me? I do not want to clone the project to commit this then.

**Comment by MobiDevelop** [comment] 2019-08-20 14:11
Welp, if it doesn't matter enough to you and hasn't bothered anyone else, I guess we'll close this.

**Closed by MobiDevelop** 2019-08-20 14:11 UTC

**Comment by DeRealMorgan** [comment] 2019-08-20 14:17
@MobiDevelop It is not about bothering, it is about making libgdx better and I think it is quite sad that you apparently are not consequent enough in also reaching that goal.

**Comment by Darkyenus** [comment] 2019-08-20 14:35
We are all volunteers here and the current state of the project is that people work mostly on things that matter to them. Since this is not a bug report nor any significant improvement, nobody will work on this and it will sit in the issue tracker forever, which is pointless for such a small change, so it is better to just close it. If you cared enough about this change, you would make a PR for it - people on discord/IRC will be happy to help you with it if you encounter any problems.

---

Btw. the suggested change would not work: since the [`SnapshotArray` is initialized without a type](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/InputMultiplexer.java#L26), the returned array will indeed be of type `Object[]` and not `InputProcessor[]`, even if generics say otherwise (thanks to erasure). So the full change would also have to supply the `InputProcessor.class` to the `SnapshotArray` constructor.

**Comment by Anuken** [comment] 2019-08-20 15:25
> I do not want to clone the project to commit this then
Why not? As you said, it will *easily* help libgdx. Quite sad that you are not interested in making libGDX better.

**Comment by DeRealMorgan** [comment] 2019-08-20 16:44
I can in fact! I will do that. I just thought it would be easier for me to just open the issue, a developer will apply my suggestions and push, which will probably faster.

But yes I will do it myself then :D

**Comment by mgsx-dev** [comment] 2019-08-20 17:31
it sounds like a duplicate of https://github.com/libgdx/libgdx/pull/5311

**Comment by DeRealMorgan** [comment] 2019-08-20 19:23
Yes it it. I did not see that. So then this issue is pointless.
