### ISSUE TITLE
import package de native android  in package core

### ISSUE THREAD

**Issue by zhao-zilong** [libgdx/libgdx#4375] opened 2016-10-18 23:21 UTC
Hi All

when I created a libgdx project, I can not import android.os Bundle,  I can only create in android folder, but in folder core, I can not access the class in android, so, who has an idea?

**Comment by krukhlis** [comment] 2016-10-19 01:51
It's not a bug. This is exactly correct architecture.
All platform dependant and specific classes should stay under the corresponding platform's projects.
Regarding the question how to pass platform's specific implementation to core -- it's already clarified in wiki article: https://github.com/libgdx/libgdx/wiki/Interfacing-with-platform-specific-code
This issue should be closed as not a bug at all.
Please, use Libgdx forum to ask questions instead of using Git's issues( which should be used for bugs or enhancements) for this purpose.

**Closed** 2016-10-19 01:57 UTC
