### ISSUE TITLE
[desktop bug] setMaximized(true) don't work as intended.

### ISSUE THREAD

**Issue by HydrolienF** [libgdx/libgdx#7089] opened 2023-02-11 18:08 UTC
Please ensure you have given all the following requested information in your report.

#### Issue details
_Please provide the details of your issue_
On DesktopLauncher, I'm using a Lwjgl3ApplicationConfiguration to set frame size. To use the full screen I have done 
```java
Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
config.setMaximized(true);
new Lwjgl3Application(new Main(), config);
```

My issue is that it don't have the same result on Windows & on Linux.

On Windows (Windows 11), it update the window size (Gdx.graphics.getWidth() & Gdx.graphics.getHeigth()) while on Linux (Ubuntu 20.04) it keep defaults values (640 480) and only stretch render of the frame.

Example with a label with font size at 10.
Windows version :
![Capture d’écran (334)](https://user-images.githubusercontent.com/71718798/218273088-3a40cd1b-cebd-4154-85ac-026b47e81533.png)

Linux version : 
Ubuntu 20.04 :
![Ekrankopio de 2023-02-11 18-21-30](https://user-images.githubusercontent.com/71718798/218273111-365d89ec-14ab-4180-8f7b-eac737a99259.png)
Debian 11 :
![Capture d’écran 2023-02-11 190525](https://user-images.githubusercontent.com/71718798/218274074-fd477d9b-5533-43be-8765-999bbba893df.png)

I guess it's linux version that have an issues & Windows work as intended.

Textures and texts are pixelated & mouse position is shifted.

#### Reproduction steps/code
I have done a [SSCCE](http://sscce.org/) to make it easy to test at https://github.com/HydrolienF/setMaximizedIssue

#### Version of libGDX and/or relevant dependencies
Last release (1.11.0) and last version (at 93d19940877cfa10d1cf5e9e72800fc40a54da1d)

#### Please select the affected platforms
- [ ] Windows
- [x] Linux (Unbuntu 20.04.5 & Debian 11)
- [ ] macOS ?

I have test it on 2 differents Linux to be sur that It wasn't affecting only my computer, but I don't have a mac to test for it.

**Comment by tommyettinger** [comment] 2023-02-11 22:50
Usually you should override resize() in your ApplicationListener if it ever is meant to change window size. Your code only sets the Label's text once, in create(), so if the window does change size immediately after create() completes (but before render() is called), then the Label has no way of knowing that or changing its text to respond. This is tricky to debug for me on Linux, but I can probably do it.

**Comment by tommyettinger** [comment] 2023-02-11 22:58
Also, see https://github.com/HydrolienF/setMaximizedIssue/pull/1 for an example of the resize() implementation I had in mind.

**Comment by HydrolienF** [comment] 2023-02-12 10:01
Tanks @tommyettinger for triing to help. I've test it on Ubuntu.
Now it display the rigth window size (1920 1016) but text is still pixelated & bigger that expected.
![Ekrankopio de 2023-02-12 10-23-44](https://user-images.githubusercontent.com/71718798/218304523-0468b9f9-e68a-4772-bab4-46de509b40e5.png)

**Comment by HydrolienF** [comment] 2023-02-12 10:03
I have add log print to understand what append.
This is what I get on Linux : 
```java
[LOG] 2023-02-12 11:02:11.500 Create ApplicationAdapter
[LOG] 2023-02-12 11:02:11.501 Resize to 640 480
[LOG] 2023-02-12 11:02:11.505 Resize to 1920 1016
[LOG] 2023-02-12 11:02:11.505 Create Label by lazy
```

**Comment by HydrolienF** [comment] 2023-02-12 10:04
This is what I get on Windows :
```java
[LOG] 2023-02-12 10:55:05.086 Create ApplicationAdapter
[LOG] 2023-02-12 10:55:05.086 Resize to 1920 1057
[LOG] 2023-02-12 10:55:05.086 Create Label by lazy
```

**Comment by HydrolienF** [comment] 2023-02-12 10:07
I have try to Create label after the 2nd resize but it haven't fix it.

**Comment by tommyettinger** [comment] 2023-02-12 10:25
It probably has to do with these lines in create(): 
```java
		int width = Gdx.graphics.getWidth();
		int height = Gdx.graphics.getHeight();
		viewport = new FitViewport(width, height, new OrthographicCamera());
```
We now know that on Linux, width and height start at 640x480, so width and height are 640 and 480 there. But on Windows, they start at 1920x1057, and don't change again. This means the viewports have different world sizes, which is probably not what you want even if there wasn't an OS difference. Most games that use FitViewport would use an appropriate world size for their gameplay (like 8x8 for chess, since it is on an 8x8 square board), so that FitViewport can do its normal scaling that it does. If the world size depends on screen size, you probably want a ScreenViewport instead. ScreenViewport is pretty much the best option for GUIs, and since the screen is just text right now, it would look best for that. The default font with any scaling other than 100% will look pixelated or artifact-y in some way, but ScreenViewport doesn't scale it at all, so I think that's good here.

Also, I can reproduce the Linux case on Windows by changing 
```java
		config.setMaximized(true);
```
to
```java
		config.setWindowListener(new Lwjgl3WindowAdapter(){
			@Override
			public void created(Lwjgl3Window window) {
				super.created(window);
				window.maximizeWindow();
			}
		});
```
That makes it maximize slightly later.

**Comment by HydrolienF** [comment] 2023-02-12 11:00
Thanks !
With ScreenViewport & viewport.update(width, height, true) it Draw Text with the rigth size, at the rigth place.
![Ekrankopio de 2023-02-12 11-57-07](https://user-images.githubusercontent.com/71718798/218306925-274dfd31-a579-402c-81f8-2d158152b3c7.png)


I will have some other fix for my Screen to do
![Ekrankopio de 2023-02-12 12-00-00](https://user-images.githubusercontent.com/71718798/218307059-6addda68-54fd-494a-b1cd-b50df5e739b6.png)

**Comment by HydrolienF** [comment] 2023-02-12 11:05
Tanks for the workaround.
I still think that it will be better if Gdx.graphics.getWidth() & Gdx.graphics.getHeight() can be set to there max size before the first render of the frame.

**Comment by tommyettinger** [comment] 2023-02-17 09:31
Yeah, it would be good; any OS differences like this on desktop seem like trouble waiting to happen. I guess the initial cause of the bug is still here and unchanged, so this issue shouldn't be closed yet.

**Comment by HydrolienF** [comment] 2023-02-23 12:57
I think it's a GLFW issues because every step seem's to be OK :
```java
new Lwjgl3Application (ApplicationListener listener, Lwjgl3ApplicationConfiguration config)
```
call 
```java
createWindow(config, listener, 0);
```
that call
```java
createWindow(window, config, sharedContext);
```
that call
```java
createGlfwWindow(config, sharedContext);
```
that set GLFW_MAXIMIZED before creating the windows
```java
GLFW.glfwWindowHint(GLFW.GLFW_MAXIMIZED, config.windowMaximized ? GLFW.GLFW_TRUE : GLFW.GLFW_FALSE);
```
then create the window with config as param.

**Comment by HydrolienF** [comment] 2023-02-23 13:07
A fix can be to set config width & heigth before using it in Lwjgl3Application
```java
if (config.fullscreenMode != null) {
	GLFW.glfwWindowHint(GLFW.GLFW_REFRESH_RATE, config.fullscreenMode.refreshRate);
	windowHandle = GLFW.glfwCreateWindow(config.fullscreenMode.width, config.fullscreenMode.height, config.title,
		config.fullscreenMode.getMonitor(), sharedContextWindow);
} else {
	if(config.windowMaximized){
               // TODO set size to screen size
	}
	GLFW.glfwWindowHint(GLFW.GLFW_DECORATED, config.windowDecorated ? GLFW.GLFW_TRUE : GLFW.GLFW_FALSE);
	windowHandle = GLFW.glfwCreateWindow(config.windowWidth, config.windowHeight, config.title, 0, sharedContextWindow);
}
```

**Comment by HydrolienF** [comment] 2023-03-15 16:25
Setting size manually seems to be a patch of GLFW, so I will first try to get help there.

**Comment by crykn** [comment] 2023-07-25 18:43
Closing this, since it seems to be caused by GLFW.

**Closed by crykn** 2023-07-25 18:43 UTC
