### ISSUE TITLE
keyUp called when key is still pressed

### ISSUE THREAD

**Issue by bachtrong43** [libgdx/libgdx#3259] opened 2015-07-06 16:33 UTC
```javascript
public class DesktopLauncher {
	public static void main(String[] arg) {
		LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
		config.width = 480;
		config.height = 320;
		new LwjglApplication(new ApplicationListener() {
			public void resume() {

			}

			@Override
			public void resize(int width, int height) {

			}

			@Override
			public void render() {
				Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
			}

			@Override
			public void pause() {

			}

			@Override
			public void dispose() {

			}

			@Override
			public void create() {
				Gdx.input.setInputProcessor(new InputProcessor() {

					@Override
					public boolean touchUp(int screenX, int screenY,
							int pointer, int button) {
						return false;
					}

					@Override
					public boolean touchDragged(int screenX, int screenY,
							int pointer) {
						return false;
					}

					@Override
					public boolean touchDown(int screenX, int screenY,
							int pointer, int button) {
						return false;
					}

					@Override
					public boolean scrolled(int amount) {
						return false;
					}

					@Override
					public boolean mouseMoved(int screenX, int screenY) {
						return false;
					}

					@Override
					public boolean keyUp(int keycode) {
						System.out.println("keyup");
						return false;
					}

					@Override
					public boolean keyTyped(char character) {
						System.out.println("keytyped");
						return false;
					}

					@Override
					public boolean keyDown(int keycode) {
						System.out.println("keydown");
						return false;
					}
				});
			}
		}, config);
	}
}
```
When a key is pressed (not release yet):
```javascript
keydown
keytyped
keyup
keydown
keytyped
keyup
keydown
keytyped
keyup
keydown
keytyped
keyup
keydown
keytyped
keyup
....
```

Tested on iMac 2012, libgdx version 1.6.3

**Comment by Antag99** [comment] 2015-07-06 17:13
Couldn't reproduce on Linux, libgdx version 1.6.3.
```
keydown
keytyped
...
keytyped
keyup
```

**Comment by FyiurAmron** [comment] 2015-07-06 19:20
@bachtrong43 have you tried switching OS's autorepeat feature on/off? (http://belchak.com/2011/07/23/re-enabling-key-repeat-in-osx-lion/) To me it seems like a generic case of keyboard autorepeat turned on; the OS notices a held key and constantly sends up/down events to trigger repeated events. It's possible to circumvent this with input event filter, though.

**Comment by bachtrong43** [comment] 2015-07-07 01:19
Thanks @FyiurAmron , I'll check and try it later and let you know soon.

**Comment by NathanSweet** [comment] 2015-07-07 22:16
Windows:
```
keydown
keytyped
keytyped
keytyped
keytyped
keytyped
keytyped
keytyped
keyup
```

I'd say it's either an OS feature or an LWJGL bug, or both.

**Comment by MobiDevelop** [comment] 2015-07-11 04:44
Works correctly for me on OSX (Yosemite).

**Comment by MobiDevelop** [comment] 2015-07-13 13:14
Can't reproduce on any of the "big-3" operating systems, so it must be something on your end.

I'm going to close this one out.

**Closed by MobiDevelop** 2015-07-13 13:14 UTC
