### ISSUE TITLE
A Libgdx game overwrites the screen brightness of the F.lux software (color temperature) for a few seconds each time the application closes.

### ISSUE THREAD

**Issue by benbor** [libgdx/libgdx#4845] opened 2017-08-03 14:28 UTC
#### Issue details
In the process of debugging my application on the desktop (not full screen), I found a problem. A Libgdx game overwrites the screen brightness of the F.lux software (color temperature) for a few seconds each time the application closes. I do not have the strong knowledge in libgdx, and I can not fix it. I tried google it, but failed.

#### Reproduction steps/code
1. use f.lux software with custom color temperature
2. Create empty project.
3. Create `Desktop Application`   as described on [this wiki](https://github.com/libgdx/libgdx/wiki/Gradle-and-Intellij-IDEA#running-your-project) for desktop option. 
4. Run and close application.
Actual: application closed and color temperature reset to default value (to high value, which is broking my eyes) . After few seconds color temperature value is returned back.
Expected: application will be closed and color temperature will NOT be changed.

#### Version of LibGDX and/or relevant dependencies
MacBook Pro (Retina), Core i7, Interl Iris Pro 1536MB
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
Project versions (from `build.gradle` file)
```
        appName = "XXX"
        gdxVersion = '1.9.6'
        roboVMVersion = '2.3.1'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by RUSshy** [comment] 2017-08-03 14:49
i have same issue with redshift too, this doesn't happen with sfml/sdl/monogame, so it is a bug in libgdx, probably lwjgl

**Comment by Tom-Ski** [comment] 2017-08-03 15:01
The colour temperature is restored to the correct value after a few seconds?

**Comment by Tom-Ski** [comment] 2017-08-03 15:12
Can't really do anything from out side, its possibly something that can be fixed with lwjgl. Have you see https://github.com/jonls/redshift/issues/143 ?

**Comment by xoppa** [comment] 2017-08-03 19:30
Possible duplicate of or related to #4593

**Comment by benbor** [comment] 2017-08-04 08:36
> The colour temperature is restored to the correct value after a few seconds?
@Tom-Ski yes

@xoppa yes, my case is the same, except platform (macos + f.lux instead of ubuntu and redshift)

**Comment by snordgren** [comment] 2017-08-13 16:54
Reproduced on OS X with f.lux for the LWJGL 2 backend. The LWJGL 3 backend works perfectly though.

**Comment by benbor** [comment] 2017-08-21 09:47
@snordgren hi. Can you help me migrate my libdgx application to LWJGL3 backend? Any migration plans on links will help.

**Comment by piotr-j** [comment] 2017-08-26 22:38
Unless you do some fancy stuff, you add 3 to `Lwjgl` stuff in build.gradle and in `DesktopLauncher` and you should be fine. You can always generate new project with 3 and compare.

**Comment by benbor** [comment] 2017-08-28 13:50
@piotr-j my thanks.

**Comment by shatterblast** [comment] 2020-03-27 15:58
Close this, please?

**Closed** 2020-03-27 16:00 UTC
