### ISSUE TITLE
gdx-setup does not work on m1, gdx-liftoff does. Why?

### ISSUE THREAD

**Issue by qiurenbo** [libgdx/libgdx#6743] opened 2021-12-27 12:50 UTC
#### Issue details
Hello, great libgdx development team. I followed the manual on the official website and used gdx-setup to build my project on my macbook m1 and found that it did not work( Even though I used 1.10.1-SNAPSHOT). But gdx-liftoff works perfectly as mentioned in ISSUE #6726.  gdx-setup is outdated, right? If so, why is it still used on the official website?

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] macOS

**Comment by Frosty-J** [comment] 2021-12-27 19:28
It's on the official website because it's the official tool, though I do feel a link to it on the website would be a fair compromise. Contributions to either setup tool are welcome, or the website at https://github.com/libgdx/libgdx.github.io.

At what point does it fail, and with what error messages? It would be useful to attempt to fill in the reproduction steps and stack trace sections of the template blank.

* If you used the stable build of gdx-setup (I just use nightly due to how slow the release cycle is - it still defaults to libGDX 1.10.0, so no big difference) you must change the project to use LWJGL3 as instructed at https://libgdx.com/news/2021/07/devlog-7-lwjgl3#how-can-i-migrate. Since you're on macOS, the `-XstartOnFirstThread` part certainly shouldn't be ignored.
* If you're using Java 16 or 17, things won't work with gdx-setup. For best results with it, use Java 8 through 15 inclusive.

**Comment by tommyettinger** [comment] 2021-12-27 22:28
I'm curious what gdx-setup fails with on M1, though judging by the amount of issues we've had reported on M1 Macs on the Discord, I don't doubt that something is going to fail. I could probably fix gdx-setup so it uses Gradle 7.3.3 and libGDX 1.10.1 when it comes out, but to be perfectly honest, I don't feel like going through the hassle of a PR to gdx-setup when gdx-liftoff works today. Anyone is welcome to copy code and configuration from gdx-liftoff into gdx-setup. For the time being, I think that gdx-liftoff is a much better option to present to people just creating their first project, because it works on the current Java LTS release, can be made to work on M1 Macs (if you use 1.10.1-SNAPSHOT), and just in general has the nicer project layout that gdx-setup finally is starting to adopt in its nightly.

**Comment by obigu** [comment] 2021-12-28 22:01
The Gdx Setup tool and libGDX releases need to be in sync and we do our best to test and update Gdx Setup tool for each libGDX stable release. 
There are always two Gdx Setup jars available to download from the website (https://libgdx.com/dev/project-generation/), "Stable Release" and "Nightly Version". The stable release of Gdx Setup ensures it works with the latest stable libGDX version (currently is 1.10.0) and the "Nightly Version" has the latest changes and should work with latest SNAPSHOT (even though being in development there may be times there's issues).
Because libGDX 1.10.0 doesn't support M1 out of the box because that feature was merged at a later date, until the 1.10.1 release is made and we update the Stable Gdx Setup tool that works with it, you have to use the "Nightly Version" Gdx Setup with the latest libGDX SNAPSHOT (1.10.1-SNAPSHOT).
If you do that it should work. Closing this, if you still have an issue please fill the issue template and provide details on the error you're seeing, environment info such as Java version, IDE, etc... as well as the reproduction steps.

**Closed by obigu** 2021-12-28 22:01 UTC

**Comment by qiurenbo** [comment] 2021-12-29 00:43
Thanks for the answers, experts! I figured out the current progress of gdx-setup. Thank you again!
