### ISSUE TITLE
Particle Editor not rendering (black box) on MacOS

### ISSUE THREAD

**Issue by dariuspranskus** [libgdx/libgdx#6088] opened 2020-06-25 00:24 UTC
#### Issue details
I am trying to use the particle editor included in gdx-tools package. The window opens all controls are working, but there is no render output - the render area is always black. Sometimes it flickers but not too much. Resizing window or panels does not help.

No errors in console.

If I try to run a sample particle file in demo GDX project, then it works properly.

#### Reproduction steps/code
Generate a libgdx project including tools package, build and run the particle editor 

#### Version of LibGDX and/or relevant dependencies
1.9.10, 1.9.11-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

I am running MacOS Catalina 10.15.5 on 2019 Macbook Pro 13".

Thanks

**Comment by dariuspranskus** [comment] 2020-07-05 23:49
Could someone help me with this problem, please. I tried it on windows laptop, it is working fine, but on mac it is not rendering anything.

**Comment by NathanSweet** [comment] 2020-07-13 20:36
ParticleEditor is a Swing app that uses LwjglCanvas from LWJGL2. It could be LWJGL2 is too old and recent Mac updates have broken it. You could see if you can get anything at all using LwjglCanvas to run.

Otherwise I'm afraid I'm not a Mac person at all (for this exact reason, among many others).

**Comment by obigu** [comment] 2020-07-14 13:24
I've quickly tested latest build on a MacOS 10.15.5 and I confirm I can reproduce the issue.

**Comment by julienvillegas** [comment] 2020-07-14 22:05
Yes, I think this is linked to this issue I had raised some time ago..
[https://github.com/libgdx/libgdx/issues/5004](https://github.com/libgdx/libgdx/issues/5004)
I had created a self contained code showing the issue there.
I tried for some time to fix it but never found a way... if someone could find the solution that'd be great.

**Comment by dbchan** [comment] 2020-08-09 15:28
Same here. MacOS 10.15.6, with nightly build. Black rendering box, flicker when resize. About to give up on Flame but couldn't find an alternative..

**Comment by crykn** [comment] 2020-09-09 10:13
I think instead of trying to fix the current LwjglCanvas, we should wait for the lwjgl3-awt project to [publish their first Mac OS compatible build](https://github.com/LWJGLX/lwjgl3-awt/pull/23) and then port ParticleEditor to lwjgl3.

**Comment by Trurl101** [comment] 2020-10-17 14:52
Since the particle editor is broken on MacOs. Is there an alternative that exports to libgdx?

**Comment by tisoft** [comment] 2020-10-23 12:24
@Trurl101 You can try out my branch from #6247, which adds lwjgl3-awt support and contains a working ParticleEditor on Mac OS.

**Comment by dbchan** [comment] 2020-12-11 03:03
#6247 works for me! I use 3D so I use Flame, it renders OK but opening up a new texture file doesn't work (black sprite), only the default texture works. Not sure if it is just me..

**Comment by Trurl101** [comment] 2021-02-19 12:57
> @Trurl101 You can try out my branch from #6247, which adds lwjgl3-awt support and contains a working ParticleEditor on Mac OS.

I tried this. ParticleEditor starts fine and shows the default effect, but when I try to load an effect it the editor crashes (no matter which effect):
`
java.lang.IndexOutOfBoundsException: index can't be >= size: 2 >= 2
	at com.badlogic.gdx.utils.Array.get(Array.java:155)
	at com.badlogic.gdx.tools.particleeditor.ParticleEditor.getEmitter(ParticleEditor.java:178)
	at com.badlogic.gdx.tools.particleeditor.ParticleEditor$Renderer.render(ParticleEditor.java:494)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3AWTCanvas.render(Lwjgl3AWTCanvas.java:336)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3AWTCanvas$1.paintGL(Lwjgl3AWTCanvas.java:155)
	at org.lwjgl.opengl.awt.AWTGLCanvas.render(AWTGLCanvas.java:107)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3AWTCanvas$1.paint(Lwjgl3AWTCanvas.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3AWTCanvas$1.update(Lwjgl3AWTCanvas.java:131)
	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
	at sun.lwawt.LWRepaintArea.updateComponent(LWRepaintArea.java:47)
	at sun.awt.RepaintArea.paint(RepaintArea.java:232)
	at sun.lwawt.LWComponentPeer.handleJavaPaintEvent(LWComponentPeer.java:1311)
	at sun.lwawt.LWComponentPeer.handleEvent(LWComponentPeer.java:1195)
	at java.awt.Component.dispatchEventImpl(Component.java:4975)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by Chae4ek** [comment] 2022-01-27 11:57
I have a similar problem. When I try to open a file I get the following error:
> Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
        at com.badlogic.gdx.utils.Array.get(Array.java:155)
        at com.badlogic.gdx.tools.particleeditor.ParticleEditor.getEmitter(ParticleEditor.java:208)
        at com.badlogic.gdx.tools.particleeditor.ParticleEditor$Renderer.render(ParticleEditor.java:526)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
        at com.badlogic.gdx.utils.Array.get(Array.java:155)
        at com.badlogic.gdx.tools.particleeditor.ParticleEditor.getEmitter(ParticleEditor.java:208)
        at com.badlogic.gdx.tools.particleeditor.ParticleEditor.reloadRows(ParticleEditor.java:154)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel.emitterSelected(EffectPanel.java:137)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel$10.valueChanged(EffectPanel.java:368)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
        at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:670)
        at java.desktop/javax.swing.JTable.tableRowsInserted(JTable.java:4476)
        at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4412)
        at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
        at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:232)
        at java.desktop/javax.swing.table.DefaultTableModel.insertRow(DefaultTableModel.java:383)
        at java.desktop/javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:357)
        at java.desktop/javax.swing.table.DefaultTableModel.addRow(DefaultTableModel.java:368)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel.openEffect(EffectPanel.java:170)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel$5.actionPerformed(EffectPanel.java:315)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6401)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

I changed the `getEmitter()` method like this:
```java
public ParticleEmitter getEmitter () {
  Array<ParticleEmitter> emitters = effect.getEmitters();
  return effectPanel.editIndex >= emitters.size ? emitters.first() : emitters.get(effectPanel.editIndex);
}
```
For some reason it's rendering before the `effectPanel.editIndex` will change to 0, but it **will** later.
So with the above code the problem is gone, but it looks weird and sometimes I get another error when I open a file:
if I have 1 emitter:
>  Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class javax.swing.plaf.nimbus.DerivedColor$UIResource cannot be cast to class javax.swing.Painter (javax.swing.plaf.nimbus.DerivedColor$UIResource and javax.swing.Painter are in module java.desktop of loader 'bootstrap')
        at java.desktop/javax.swing.plaf.nimbus.NimbusStyle.getBackgroundPainter(NimbusStyle.java:722)
        at java.desktop/javax.swing.plaf.nimbus.SynthPainterImpl.paintBackground(SynthPainterImpl.java:100)
        at java.desktop/javax.swing.plaf.nimbus.SynthPainterImpl.paintPanelBackground(SynthPainterImpl.java:958)
        at java.desktop/javax.swing.plaf.synth.SynthPanelUI.update(SynthPanelUI.java:152)
        at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
        at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
        at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" com.badlogic.gdx.utils.GdxRuntimeException: #iterator() cannot be used nested.
        at com.badlogic.gdx.utils.Array$ArrayIterator.hasNext(Array.java:638)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel.openEffect(EffectPanel.java:168)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel$5.actionPerformed(EffectPanel.java:315)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6401)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

if I have more than 1 emitter:
> Exception in thread "AWT-EventQueue-0" com.badlogic.gdx.utils.GdxRuntimeException: #iterator() cannot be used nested.
        at com.badlogic.gdx.utils.Array$ArrayIterator.hasNext(Array.java:638)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel.openEffect(EffectPanel.java:168)
        at com.badlogic.gdx.tools.particleeditor.EffectPanel$5.actionPerformed(EffectPanel.java:315)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6401)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Anyway the editor is still working

**Comment by crykn** [comment] 2023-11-25 09:04
This is fixed by https://github.com/libgdx/gdx-particle-editor (#7285).

**Closed by crykn** 2023-11-25 09:04 UTC
Labels: bug, tools, LWJGL2
