### ISSUE TITLE
OpenAL startup crash (Windows XP related?)

### ISSUE THREAD

**Issue by ChetRippo** [libgdx/libgdx#3252] opened 2015-07-02 15:14 UTC
I have a Windows XP user reporting a crash when opening my game. Their log says this:

 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x1f27de7a, pid=1572, tid=2580

 JRE version: 7.0_15-b03
 Java VM: Java HotSpot(TM) Client VM (23.7-b01 mixed mode windows-x86 )
 Problematic frame:
 C [OpenAL32.dll+0xde7a] alProcessUpdatesSOFT+0x122f

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

Does LibGDX officially support this version of Windows?

**Comment by FyiurAmron** [comment] 2015-07-02 17:51
AFAIK, "officially" libGDX bases its support for desktop platforms on Java, LWJGL & OpenAL; all of them support XP (with Java, official support ended with AFAIR Java 7, note that newer Java still works with XP without significant problems, https://www.java.com/pl/download/faq/winxp.xml); from my experience, I've had no severe issues while developing on/for XP.

As with OpenAL, it suffers multiple init problems (the most well-known being probably https://github.com/libgdx/libgdx/issues/2578 due to the amount of people who encountered and described it), but I haven't seen OpenAL segfaulting on `alProcessUpdatesSOFT` on XP personally. I suppose the user's sound codec drivers or specific platform setup may be the guilty party.

Providing more information as to when the crash happens and/or providing the app for testing may prove helpful to the people willing to help you IMO.

**Comment by xoppa** [comment] 2015-08-18 18:37
Closing this. If there is actually an issue with libgdx then please include the required information to reproduce it.

**Closed by xoppa** 2015-08-18 18:37 UTC
