### ISSUE TITLE
Intermittent BitmapFontData.getGlyphs() crash, IOS only

### ISSUE THREAD

**Issue by rdamiano** [libgdx/libgdx#5346] opened 2018-08-14 19:58 UTC
This is an odd bug that has been around for months. I could never figure it out and at this point it's at the top of my app's crash list and I was wondering if it was a LibGDX error?

While the code is the same, this crash **only** occurs on my iOS app, not the Android version. There also doesn't seem to be any discernible reason or cause for it, so I can't even reproduce it unfortunately. It's occurred 65 times to 45 users over the past few days.

```
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

BitmapFont$BitmapFontData.java - Line 783
[J]com.badlogic.gdx.graphics.g2d.BitmapFont$BitmapFontData.getGlyphs(Lcom/badlogic/gdx/graphics/g2d/GlyphLayout$GlyphRun;Ljava/lang/CharSequence;IIZ)V

GlyphLayout.java
[J]com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(Lcom/badlogic/gdx/graphics/g2d/BitmapFont;Ljava/lang/CharSequence;IILcom/badlogic/gdx/graphics/Color;FIZLjava/lang/String;)V

GlyphLayout.java
[J]com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(Lcom/badlogic/gdx/graphics/g2d/BitmapFont;Ljava/lang/CharSequence;IILcom/badlogic/gdx/graphics/Color;FIZLjava/lang/String;)V

GlyphLayout.java 
[J]com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(Lcom/badlogic/gdx/graphics/g2d/BitmapFont;Ljava/lang/CharSequence;)V
```

(The line numbers aren't correct with Crashlytics so I removed them except for the last one, top.)

The crash occurs when setting the text on a GlyphLayout immediately after creating the object. I believe the offending line is in `BitmapFontData.getGlyphs()` line 783 of current LibGDX 1.9.9-SNAPSHOT

`Array<Glyph> glyphs = run.glyphs;`

Which again, throws a
`EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000`

Which kinda seems like a null pointer exception in IOS/RoboVM language.

I can't reproduce it but it's been plauging my iOS app (not the Android one) for months now and the code at this point of the programming is identical.

https://i.imgur.com/eJPtRB1.png

Using LibGDX 1.9.9-SNAPSHOT and RoboVM 2.3.4-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by crykn** [comment] 2020-08-28 16:28
Closing this, since there is no reproducable example and no other report of this same issue in the last 2 years. If the problem pops up again/is still an issue, we can reopen.

**Closed by crykn** 2020-08-28 16:28 UTC
