### ISSUE TITLE
CTRL+A cannot select all text after initial assignment or pasting the specified string

### ISSUE THREAD

**Issue by LuoiZQ** [libgdx/libgdx#7143] opened 2023-05-13 14:43 UTC
#### Issue details
Paste the text as follows
{JOLT=1;1.2;inf;0.3;dull lavender;light butter}There's a [/][@Medieval]STORM{RESET} on [@Future]the way[@], she's{WIND=3;2;0.2;0.2} blowin' on down{RESET}, whippin' her way through the [*]{FONT=Sans}whole dang[@][*] town! Sure as [/]I reckon[], if we [@Mono]meet our {HANG}fate{RESET}, this [light grey black][%150]storm[] will be there on clouds{SPIN=2;1;false}[%75] one{CLEARSIZE}{ENDSPIN} through {SPIN=1;8;false}[%200]eight[%]{ENDSPIN}!{SCALE=60.0}Uh-[_]huh[_].{ENDSCALE}{SCALE=120.0} All [~]right[~].{ENDSCALE}

![issue00](https://github.com/libgdx/libgdx/assets/78594251/163a6686-84ff-4a6d-9cfb-37defa1cc357)

#### Reproduction steps/code
```java
String ori = "{JOLT=1;1.2;inf;0.3;dull lavender;light butter}There's a [/][@Medieval]STORM{RESET} on [@Future]the way[@], " +
        "she's{WIND=3;2;0.2;0.2} blowin' on down{RESET}, " +
        "whippin' her way through the [*]{FONT=Sans}whole dang[@][*] town! " +
        "Sure as [/]I reckon[], if we [@Mono]meet our {HANG}fate{RESET}, " +
        "this [light grey black][%150]storm[] will be there on clouds{SPIN=2;1;false}[%75] one{CLEARSIZE}{ENDSPIN} through {SPIN=1;8;false}[%200]eight[%]{ENDSPIN}!\n" +
        "{SCALE=60.0}Uh-[_]huh[_].{ENDSCALE}{SCALE=120.0} All [~]right[~].{ENDSCALE}";
edit = new TextArea("", skin);
edit.setText(ori);
flexBox.addAsChild(mainArea, edit)
       .setHeight(300)
       .setMinWidthPercent(100)
       .setMargin(YogaEdge.TOP, 10)
       .setAlignSelf(YogaAlign.CENTER);
TextraLabel preview = createTypingLabel();
```

#### Version of libGDX and/or relevant dependencies
gdx-1.11.0

#### Stacktrace
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: index can't be >= size: 515 >= 512
	at com.badlogic.gdx.utils.FloatArray.get(FloatArray.java:131)
	at com.badlogic.gdx.scenes.scene2d.ui.TextArea.drawSelection(TextArea.java:262)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.draw(TextField.java:340)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:168)
	at dev.lyze.flexbox.FlexBox.draw(FlexBox.java:112)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment] 2023-05-13 20:41
Hehe, I recognize my sample text from TextraTypist. It's not showing the `[]` pairs, which mean "pop off last color from the stack of applied colors" in BitmapFont's markup syntax, and mean something subtly different in TextraTypist. Because `[]` has a meaning for BitmapFont, but `[light grey black]` does not, the `[]` are interpreted as markup, and not shown even though the selection still seems to measure off the original String's size. There's probably markup enabled on your BitmapFont; disable it for any BitmapFont used in a TextArea or TextField (you can create a copy that just has markup disabled, if you want). That's just `bmFont.getData().markupEnabled = false;` That will make the String you gave print as-is, including printing `[]` and allowing selection for them.

This is something I want to fix, somehow, in TextraTypist, but the TextArea/TextField code is quite complex.

**Comment by LuoiZQ** [comment] 2023-05-14 12:24
> @tommyettinger 
Yes, this sample is from TextraTypist.
I would like to build a Typist editor, but editing becomes rather cumbersome after superposing many TextraTypist tokens when using TextArea as the editing area. There is of course a scheme that does not show TextraTypist specific tokens in the editing area. But I think the following approach might be better. Is there any way to make the TypingLabel display and edit at the same time?

**Comment by tommyettinger** [comment] 2023-05-14 21:34
You may want to look at the TextraTypist Playground mode in [Skin Composer](https://github.com/raeleus/skin-composer), by raeleus (who can help out on the libGDX Discord, especially in the scene2d topic). It has a plain-text editor above a rich-text, typing, with-effects preview window below. Displaying effects while editing would not be very pleasant for users, since a typo could easily make text invisible, or move it off-screen with some effects. Styles (the `[*]` type of markup) could usually be displayed, though you might need to be careful with transparent or mostly-transparent colors... I think what makes sense is to always show the full, unedited String, but an editor could style `[*]bold text[*]` as `[*]`**bold text**`[*]` while still showing the tokens, at least if it used TextraTypist Font code.

This is now getting off-topic for the libGDX repo, and the issue with markup wrecking TextArea has been known for a long time ( https://github.com/libgdx/libgdx/issues/4576 ). You can post an issue in [TextraTypist's Issues](https://github.com/tommyettinger/textratypist/issues) if you want to discuss any steps you need from TextraTypist to get this working. I'm closing this as a duplicate of https://github.com/libgdx/libgdx/issues/4576 .

**Closed by tommyettinger** 2023-05-14 21:34 UTC
