### ISSUE TITLE
Add bulk operation support in TextureAtlas, for performance reasons

### ISSUE THREAD

**Issue by Blezyn** [libgdx/libgdx#5752] opened 2019-08-08 20:54 UTC
1. Usually the TextureRegion's' of a TextureAtlas are cached after calling findRegion()/findRegions().
2. Usually, if not everytime, every single TextureRegion inside a TextureAtlas will be queried.

At the moment the way a TextureAtlas finds a region is through brute force, which is ok. The problem is that eventually all the TextureRegion's' inside the TextureAtlas will be queried (as per 2.) with that brute force mechanism. 

In complexity terms:
Let `n` be the number of TextureRegion's' contained in the TextureAtlas.
Because all the TextureRegion's' will be queried, that means that we will have to call the findRegion()/findRegions() methods `n` times, so we get an `O(n^2)` time complexity, especially if all of them are queried in a single point in the application and not in distirbuted points. Even if not all the TextureRegion's' will be used, quering `k` of them, takes `O(k * n)` time.

Solution:
Add bulk operations to query multiple TextureRegion's' at once, with the use of a Hash Map. The time complexity now drops to `O(n)` for the average case.

e.g. I provide a Hash Set with all the names of the TextureRegion's' I want. I get back a Hash Map with all the TextureRegion's' (potentially inside Array's'), keyed by their name.

How it works:
Use brute force to pass through all the AtlasRegion's' of the TextureAtlas again, but now check if the name of the current AtlasRegion's is contained in the given Hash Set with the names (in `O(1)` time for the average case). If it is not contained continue, otherwise add it to a Hash Map with key its name. Mutliple AtlasRegion's with the same name, but different index can be found aswell using Array's'.

Backwards compatibility will not be broken, only the addition of 1 or more methods will be needed. Nothing needs to be changed.

**Comment by Darkyenus** [comment] 2019-08-08 22:03
I do believe that this is by design, since you are supposed to cache the results of the `findRegion` methods yourself, as [noted in documentation](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java#L310). This makes sense, because you typically don't want to lookup textures on each frame, not even through a hash map. You can do so yourself, if you want to, but I'm not sure if it is a good idea to encourage that through the API design.

**Comment by Blezyn** [comment] 2019-08-08 23:09
As you said, sorting regions Array will improve the performance of findRegion() and findRegions(). The problem is that now the time complexity of addRegion() method will increase from `O(1)` to `O(n)` in order to keep the regions Array sorted. Maybe a binary search tree could be used here, dropping the `O(n)` of findRegion() to `O(log(n))` and increasing the `O(1)` of addRegion() to `O(log(n))`. A fair trade in my opinion. But again special care must be taken for AtlasRegion's' with same name but different index.

That being said, I opened this issue not to change something in regions Array, but to add a bulk operation in TextureAtlas, I am Not saying to change regions Array, even though that might be a good idea, but will have an implementation complexity, nothing too big I think.

What I propose is this: Suppose that TextureAtlas contains this method:

```java
public Map<String, Array<TextureAtlas.AtlasRegion>> findRegions(Set<String> names) {
    Map<String, Array<TextureAtlas.AtlasRegion>> map = new HashMap<>(names.size());
    for (int i = 0, n = regions.size; i < n; i++) {
        TextureAtlas.AtlasRegion region = regions.get(i);
        if (!names.contains(region.name)) {
            continue;
        }

        Array<TextureAtlas.AtlasRegion> matched = map.get(region.name);
        if (null == matched) {
            matched = new Array(TextureAtlas.AtlasRegion.class);
            map.put(region.name, matched);
        }
        matched.add(region);
    }
        
    return map;
}
```

This method runs in `O(n)` time (if you go with HashMap and HashSet implementations) and you get back as many AtlasRegion's' as you want, compared to the current findRegions() which takes `O(k * n)` time or `O(n^2)` if you ask for everything. Nothing needs to be removed, nothing needs to be changed. Just the addition of the described method.
In the described method I am using the Java collections, which may and possible are creating a lot of garbage. I think it's trivial to swap them with the libGDX collections. I used them as such for brevity.

**Comment by Darkyenus** [comment] 2019-08-09 10:25
> time complexity of addRegion() method will increase from O(1) to O(n) in order to keep the regions Array sorted

Not if the sorting is lazily done on the first query (via some `dirty` flag), then it will incur a O(n log n) pre-sort penalty, but will speed up lookups:
- Now:
    - N * O(1) to add regions + N * O(n) to lookup regions (I'm assuming that most users will lookup each region once) = O(n^2)
    - Memory: single Array
- With sorted `regions`:
    - N * O(1) adding + O(n log n) sorting (not sure whether texturepacker already produces sorted atlases, but if it did, this could go down to O(n)) + N * O(log n) lookups = O(n log n)
    - Memory: single Array
- With `Map<String, Array<AtlasRegion>>` backed `regions:
    - N * O(1) to add regions + N * O(ni log ni) sorting of `Array` by indices + N * O(log ni) lookups (ni here depends on the amount of indices per name, still significant for animations) = O(n * ni log ni) (I think? I'd have to make a better analysis, but basically the worst case is still O(n log n))
    - (Without sorted `Array`s by indices) N * O(1) adding + N * O(ni) lookups = O(n * ni)
    - Memory: `ObjectMap` + N * `Array`
    - This will probably be the fastest option if someone would want to lookup regions very often, but as I said earlier, that is not how the `TextureAtlas` should be used.

---

Btw. why `Map<String, Array<TextureAtlas.AtlasRegion>> findRegions(Set<String> names)`? Wouldn't something like `Map<String, Array<TextureAtlas.AtlasRegion>> toMap()` be better, since the HashMap already has O(1) lookups?

**Comment by intrigus** [comment] 2019-08-09 13:24
Are there any actual performance problems in production code with the current method?
I.e. is it worth it to make the code more complex?

**Comment by Blezyn** [comment] 2019-08-09 13:30
Now, I understand what you meant with the lazy sorting. Yes, probably a good solution for the average case, as we first add everything and then we query, but I think the amortized complexity of something like that (using a dirty bit) is `O(n^2 * log(n))`, if an unorthodox combination of additions and lookups is being performed, which is highly unlikely to occur and probably pointless and unpractical. So, the lazy sorting is a good design, with `O(n * log(n))` time complexity as you said, for the first lookup and `O(k * log(n))` for the succeeding queries.

> Btw. why Map<String, Array<TextureAtlas.AtlasRegion>> findRegions(Set<String> names)? Wouldn't something like Map<String, Array<TextureAtlas.AtlasRegion>> toMap() be better, since the HashMap already has O(1) lookups?

I don't quite understand your question, so I will try to answer what I assume you ask.
The implementation I described above is for the current TextureAtlas, with the Array regions. We provide it with the names we want to query (could be all the current names of the TextureAtlas or a subset of them), in a Set for `O(1)` lookups and it returns us all the AtlasRegion's' inside a Map to access them by their name in `O(1)` time.

Or you are asking why I named it `findRegions` and not `toMap`? The name is a placeholder.
Or you are asking why I give a Set with the names? The method must know what AtlasRegion's' we want, to allow as to query a subset of them, but if we want all of them, then yes, no need to provide a Set with the names, your method signature is just fine, I just thought, giving a Set with the names is more generic.

I really liked your analyses on the complexities. As you said the `Map<String, Array<AtlasRegion>>` is probably the fastest in every aspect (at least asymptotically and for the average case), with a little constant trade off in memory, which I think is not a big deal, since they are all pointers and do not actually allocate memory in the size of the assets.

Summing it up, give or take, and the more I think about it, what I suggest is probably an overkill. The current implementation is just fine and the fact that we have access to regions Array, through the public method getRegions(), allows us to do the extra work if we really want it, in our projects.

**Comment by Blezyn** [comment] 2019-08-09 13:49
@intrigus 

> Are there any actual performance problems in production code with the current method?

As far as I know, there is no problem. It is all theoretical. If you have 10.000 TextureRegion's' for your application, which could arise in a medium to large size game with animations, then in order to query all of them, there must be performed around 10.000^2 = 100.000.000 steps, which again is probably fine and will not take at max a few seconds (if not milliseconds?) to be performed. Speaking theoretically large games are quite possible, and _could_ contain more TextureRegion's'. I don't think they would tap at 100.000 TextureRegion's', but let's use it as our ceiling. That would give us around 10.000.000.000 query steps, which could be a performance issue.

> I.e. is it worth it to make the code more complex?

Probably not. The way TextureAtlas works can be optimised, in many ways, as we analyzed above, reducing the 100.000.000 steps to 132.877 steps or even 10.000 steps and that's why I made this issue, but again as long as no one had any performance issue here, there is no need to change it.

**Comment by Darkyenus** [comment] 2019-08-10 09:41
I agree.

Just a clarification on why I suggested `toMap` over `findRegions` (it is indeed not about the name, but about not prividing the `Set` of names): By using that method, it is assumed that the user will want to query the returned `Map`. Since the queries should always be O(1), no matter the size of the `Map` (at least theoretically), it shouldn't matter whether you keep around multiple maps or just one, so why complicate the `Map` creation.

It would be interesting to see some benchmarks for this code from a real game, because without that, this is all just a plain speculation. (For example, introducing more pointer indirection may cause worse cache locality, which would make sorted `Array` faster than `Map<String, Array>`. Or maybe the opposite, since the `Map` lookup will, in theory, go directly to the correct index, without any jumping around. Or maybe it is all pointless, because most games use so little textures, that the lookup times are practically zero and those with more textures use custom lookup mechanisms...)

**Comment by MrStahlfelge** [comment] 2020-09-06 14:10
I think there's nothing to add to the discussion any more, and there are no problems known, so I am closing this. Feel free to open a PR with Texture Atlas improvements.

**Closed by MrStahlfelge** 2020-09-06 14:10 UTC
