### ISSUE TITLE
3d model animation plays in desktop and 1.9.5 HTML5/GWT, not 1.9.6 or snapshot HTML5/GWT

### ISSUE THREAD

**Issue by cjeffery** [libgdx/libgdx#4789] opened 2017-06-23 15:22 UTC
Hi, I have a 3D Maya animation (converted to .g3dj) that plays in 1.9.5, but in 1.9.6 and 1.9.7 snapshot it plays in desktop but no longer loads or plays in HTML5/GWT.  A toy version of the correct behavior can be viewed at http://www2.cs.uidaho.edu/~jeffery/testfbx/ and shows a book. Animation plays when you press the space bar. I want to move up to current code but when I do, the result is black screen with refresh button but no libGDX loading bar.

Source code that demonstrates the problem is at http://www2.cs.uidaho.edu/~jeffery/testfbx.zip, that is a whole testfbx/ libGDX application directory hierarchy for easy completeness but it is a bit fat.

**Comment by Darkyenus** [comment] 2017-06-23 18:44
This is most likely a problem with GWT, not with animation or rendering. That said, this is not a [good issue report](https://github.com/libgdx/libgdx/wiki/Getting-Help).

**Comment by cjeffery** [comment] 2017-06-27 20:07
I agree with your first sentence, although I would not know if it was a GWT bug, or a bug with libGDX 1.9.6's (and newer) use of GWT. I am a libGDX programmer, not a GWT programmer. Does switching from 1.9.5 to 1.9.6 switch which version of GWT is used? I am sorry that the multiple hours that I spent reducing my problem down to simple demonstrable form does not meet your requirements, thanks a lot for the help.

**Comment by Tom-Ski** [comment] 2017-11-01 16:40
I've tested your code against 1.9.6 and can't reproduce.  The book pages were black, but that is due to your filtering modes and texture sizes.

Tested on Windows 64bit 
Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Firefox 56.0.2 (64-bit)
https://pix.asidik.com/tomski-HcjZ0w.mp4

The reason for @Darkyenus's comment is because you have ignored the issue template, which can be vital in order to reproduce issues.  Submitting a minimal example to github rather than a zip is also preferable so people can see what they are going to be downloading. Will close this out, feel free to open if you can provide more info as to reproduction steps.

**Closed by Tom-Ski** 2017-11-01 16:40 UTC
