### ISSUE TITLE
label white text picks up surrounding colors 

### ISSUE THREAD

**Issue by aboudaladdin** [libgdx/libgdx#5367] opened 2018-09-10 04:15 UTC
![label picks sprite color](https://user-images.githubusercontent.com/15913543/45276155-daa88d80-b4c0-11e8-8a3b-a80caa2cc662.png)

#### Issue details
label class from scene2d have problem when updating its text 
while changing another sprite color from color.white to any color

here i make an assignment to a new color = color.white which is a mistake 
but it didn't appear to make a problem when i used a TextArea instead of the label class

i don't get the part of color.white that can be changed by assignment while its stated static in its Color class
*public static final Color WHITE = new Color(0xffffffff);

*my mediocre solution : 
was to change the layout in the label class  
instead of using Color.WHITE in its function terms layout.setText 
i initialized a new color(1,1,1,1) and this solved it.
#### Reproduction steps/code

[label_color_problem.zip](https://github.com/libgdx/libgdx/files/2365099/label_color_problem.zip)

#### Version of LibGDX and/or relevant dependencies
gdx 1.9.8

#### Please select the affected platforms
 only tested 
- [ ] Windows

**Comment by Darkyenus** [comment] 2018-09-10 08:45
This is not an issue with libGDX, so next time [use IRC or forums instead](https://github.com/libgdx/libgdx/wiki/Getting-Help).

The problem is in your code:
```java
Color s_color = Color.WHITE;
s_color.set(MathUtils.random(.5f,1.0f),MathUtils.random(.5f,1.0f),MathUtils.random(.2f,.5f),1);
```
this changes what color the constant `Color.WHITE` contains. Doing that will break many parts of libGDX, which assume that these constants don't ever change. Your problem could be very easily fixed by using a different `Sprite.setColor()` overload, i.e.:
```java
null_sprite.setColor(MathUtils.random(.5f,1.0f),MathUtils.random(.5f,1.0f),MathUtils.random(.2f,.5f),1);
```

**Closed** 2018-09-10 15:17 UTC
