### ISSUE TITLE
[Android] Android requries new "FileProvider" means of accessing external files

### ISSUE THREAD

**Issue by BenMcLean** [libgdx/libgdx#5633] opened 2019-05-16 00:50 UTC
#### Issue details
As documented [here](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en) (which I found [here](https://stackoverflow.com/a/38858040)), Android 24 and above require using the [FileProvider](https://developer.android.com/reference/android/support/v4/content/FileProvider) class and "content:" based URIs instead of "file:" based URIs to access external files. The old way of accessing external files won't work.

If this isn't done, and there's an attempt to access external files the way I believe libGDX currently does, Android throws a "android.os.FileUriExposedException"

I ran across this when I was attempting to update [this code here](https://github.com/BenMcLean/gdx-nativefilechooser/blob/master/android/src/main/java/net/spookygames/gdx/nativefilechooser/android/AndroidFileChooser.java) to enable using Android's native file chooser to load user files. The way the code is at the moment has the exception being thrown by code that doesn't actually touch libGDX, but on searching around in libGDX, I am seeing no mention of ever fixing this in any commit, and it's something that would need to be fixed in all Android apps which access external files, therefore I figure that it cannot have been fixed in libGDX. Maybe I'm wrong, but definitely something to look into.

If I was to implement FileProvider, I'm not seeing a clear way to presenting the files it gets in the form of a libGDX FileHandle, so I think that's the libGDX-relevant part of this. That's going to be necessary to access external files in Android from now on AFAIK, so at the absolute bare minimum, the [wiki needs updating](https://github.com/libgdx/libgdx/wiki/File-handling) to deal with this change in Android.

And by the way, this is definitely not a problem on desktop or any other platform AFAIK. Just Android.

#### Please select the affected platforms
- [X] Android

**Comment by PokeMMO** [comment] 2019-05-16 06:14
FileProvider is used to share files from your app to other apps. FileHandle.External should work fine to access files on the SDCard, but you may have to request the `READ_EXTERNAL_STORAGE` permission.

What type of file are you trying to load?

**Comment by BenMcLean** [comment] 2019-05-16 12:01
> What type of file are you trying to load?

[Voxel models](https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox-extension.txt).

I'll try what you said, but I think the docs that I linked contradict what you're saying. I could be wrong though, being new to this.

**Comment by obigu** [comment] 2019-05-16 12:12
The issue you describe doesn't seem to be related to libGDX except from the fact that the wiki could be updated to explain how to deal with external files on Android. 
If you believe it is, please provide a SSCCE that reproduces the bug.

**Comment by PokeMMO** [comment] 2019-05-16 12:19
I'd also recommend taking a look at https://github.com/hedzr/android-file-chooser

**Comment by MobiDevelop** [comment] 2019-05-16 23:38
As noted, FileProvider is for providing files, and should not be involved in reading the external storage. That said, using an intent to let another app find files for you will require you to play the content uri game.

**Comment by BenMcLean** [comment] 2019-05-16 23:42
How to turn a content: URI into a LibGDX FileHandle?

**Comment by MobiDevelop** [comment] 2019-05-16 23:52
The easiest way is to use a ContentResolver to open an input stream, and copy to a file that you control - since you may not have perpetual access to the "file" they chose. Then just use that file for the handle.

I put file in quotes above because (like FileHandle itself) a content uri can refer to any content which may or may not actually be a file.

**Comment by funkyfourier** [comment] 2019-05-20 13:54
Is this related to deprecation of `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions in Android Q?

**Comment by EtK2000** [comment] 2019-06-16 18:43
Requesting this to be closed as it seems to be unrelated to LibGDX.

**Comment by MrStahlfelge** [comment] 2019-06-25 13:45
It's even more easy. On Android (and iOS), you should completely skip accessing external files. Most games are interested in importing and exporting data, and this can be achieved by the Storage Access Framework on Android and UIDocumentPicker on iOS. Both return (in case of import) an InputStream to work with. Easy, and no need to add scary permissions and tinker with runtime permissions.

**Comment by noblemaster** [comment] 2019-09-17 03:09
I don't think we need to provide "FileProvider" support. That said, the general topic is still valid. Starting with Android 10, `FileType.External` is not working anymore on Android. I propose we change the `AndroidFile`'s `sdcard `path from:

> sdcard = Environment.getExternalStorageDirectory().getAbsolutePath() + "/";

to:

> sdcard = context.getExternalFilesDir(null) + "/";

`context` is the Android context. Probably the `sdcard `path can be passed into `AndroidFiles `while it is being constructed.

This isn't the best solution. However, the old path does NOT work at all. At least for the new path, the file access works and the data is on the SD card, albeit private to the app.

References:
https://developer.android.com/training/data-storage/files/external
https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String)

**Comment by MrStahlfelge** [comment] 2020-08-03 08:24
> This isn't the best solution.

I think it actually is the best solution. It achieves everything a game needs external storage for, with a one line change in the backend code and zero changes in games codes.

**Closed** 2020-08-19 23:34 UTC
