### ISSUE TITLE
MapProperties.get(String key, Class<T>) always return String under <properties> tag

### ISSUE THREAD

**Issue by sonirico** [libgdx/libgdx#4167] opened 2016-06-23 22:59 UTC
Please ensure you have given all the following requested information in your report.

#### Issue details
_Please provide the details of your issue_

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MobiDevelop** [comment] 2016-06-23 23:07
Based on the title... There is a PR open to change the loader to be aware of typed properties coming from tmx files. When that is merged, this won't be an issue anymore.

Next time, please fill out the issue template.

**Closed by MobiDevelop** 2016-06-23 23:07 UTC

**Comment by sonirico** [comment] 2016-06-23 23:09
Ups! I must have clicked unawarely the "comment" button. Sorry for that. I am still writting the issue, so I will probably open a new one with the same title.

**Comment by MobiDevelop** [comment] 2016-06-23 23:11
Please don't open a new issue if the issue is that typed properties from tmx files are all treated as strings, we are already aware.

**Comment by sonirico** [comment] 2016-06-23 23:14
Oh, ok. Could you please link me to the related issue - if there is any - in order to keep myself informed about the incoming updates? Thanks!
