### ISSUE TITLE
Metal port since Apple is deprecating OpenGL

### ISSUE THREAD

**Issue by riho** [libgdx/libgdx#5251] opened 2018-06-05 17:11 UTC
#### Issue details
Apple announced that they're pulling OpenGL support ([link](https://developer.apple.com/macos/whats-new/) and [link](https://developer.apple.com/ios/whats-new/)). What would that mean for Mac and iOS support in LibGDX going forward? Since Vulkan support is off the table (#3344), would Metal support be unfeasible for the same reasons?

- [ ] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by badlogic** [comment] 2018-06-05 17:14
We don't know when Apple is actually removing OpenGL. Metal is not feasible
for the same reasons as Vulkan: all of libGDX is based on OpenGL. We'd have
to essentially rewrite large parts of it. If someone wants to try that in a
fork, I'll be happy to check it out. Could be build on top of Sokol or bgfx.

**Comment by barkholt** [comment] 2018-06-05 20:51
Could we, when necessary, rely on a software implementation of OpenGL on top of Metal or Vulkan?

Something like what these projects have attempted?
https://github.com/doitsujin/dxvk (implements DirectX using Vulkan).
https://moltengl.com/moltengl/
https://github.com/g-truc/glo

**Comment by badlogic** [comment] 2018-06-05 21:47
We could, and especially for our 2D use cases something like MoltenGL would
do just fine. Another alternative would be ANGLE, which I'm sure will have
Metal support soonish. If not, then ANGLE serves as a good canary for when
Google thinks it's time to switch from OpenGL to Metal to implement WebGL.

**Comment by julienvillegas** [comment] 2018-06-12 12:17
@noblemaster, in regards to your point about Molten and converting shaders : "_(2) convert shader code to Metal. Mapping the function calls is probably the easy part. The shader code is harder to do but not impossible._"

According to MoltenGL product factsheet:
"_MoltenGL will automatically convert your GLSL shaders to their MSL equivalents. This can be done transparently at run time, using the Runtime Shader Conversion feature of MoltenGL, or at development time using the offline MoltenGLShaderConverter development tool, provided with MoltenGL._"

So that´s quite good for us..  That said Molten is not free.. $149 per user. so I am not sure it would even be an option-

**Comment by noblemaster** [comment] 2018-06-12 15:20
Yes, MoltenGL is definitely an interesting option. Given it costs $99/year to release on iOS, I think the 1x $149.- isn't that much of a problem. I am just wondering how easy it will be integrate into the libGDX iOS backend?

**Comment by NathanSweet** [comment] 2018-08-30 22:16
@Stellarspace He said, "We don't know when Apple is actually removing OpenGL.", which is true. Your example doesn't change that.

**Comment by Whiteseeker** [comment] 2018-10-05 12:07
Maybe one day https://github.com/google/angle will help ^^

**Comment by kakashidinho** [comment] 2019-10-18 19:29
It might be a little late but I'm adding Metal support to ANGLE. It will eventually be in the official ANGLE repo, however currently the integration process is quite slow due to their code review process. ANGLE already merged my skeleton Metal backend code. However the full implement is still not merged yet. The full implementation is still in my own repo here https://github.com/kakashidinho/metalangle 

The current implementation status is basically completed for ES 2.0 level. It passed ANGLE's built-in  tests. If anyone interested in trying to use it with libgdx, it will be much appreciated. I will need a large project like libgdx to use it to see how it performs as well as potential bugs.

**Comment by kakashidinho** [comment] 2019-10-19 03:11
I’m trying to test libgdx with ANGLE metal port. I saw libgdx has an es 3.0 module for ios. Is it required atm?

**Comment by noblemaster** [comment] 2019-10-19 04:30
I don't think ES 3.0 is that important(?). I am using ES 2.0 myself. If you can test integration, that would be great :)  👍

**Comment by davidgiga1993** [comment] 2020-04-18 17:20
Is there any update on this? An angle backend for libgdx would be very nice! I'm happy to test some ports.

**Comment by kakashidinho** [comment] 2020-04-18 22:46
Although I am not familiar with libgdx much, but I think libgdx needs RoboVM/MOE to setup the GL views and contexts. So in order to integrate with angle, a RoboVM/MOE binding has to be made for angle first.

**Comment by davidgiga1993** [comment] 2020-04-19 10:47
I'm currently integrating EGL in the lwjgl3 backend of libgdx using angle. I'm not sure what exactly needs to be done for robovm to work with angle

**Comment by kakashidinho** [comment] 2020-04-19 12:00
I think lwjgl3 (EGL) backend can be used directly on macOS. iOS though needs robovm binding.

**Comment by davidgiga1993** [comment] 2020-04-19 13:59
OSX will also deprecate openGL sooner or later, so it makes sense to switch to angle for the desktop version as well. I've got a working POC for lwjgl3 using angle in my fork: https://github.com/davidgiga1993/libgdx/tree/google-angle/glestest/src/main/java/com/mygdx/game

**Comment by NathanSweet** [comment] 2020-04-20 13:24
Let's hope Mac users will abandon OS X once all their OpenGL apps stop working.

**Comment by obigu** [comment] 2020-04-20 13:53
This looks promising, Google ANGLE seems right now the best approach to protect libGDX against future OpenGL deprecations. We already have a working POC on lwjgl, on Android it should be straightforward being a Google project (and it will be part of Android 11) and we can expect a Metal backend will be ready before Apple drops support. It also has @badlogic blessing (at least in 2018) which is always great :).
@kakashidinho I'm interested on this, if you want, for RoboVM/MobiVM bindings we can start a discussion in MobiVM Gitter channel (https://gitter.im/MobiVM/robovm) to see what it would trake.

**Comment by kakashidinho** [comment] 2020-04-20 16:02
I'm not sure if this is the place to ask for robovm issues. But currently I'm not even able to run the `gdx-tests-iosrobovm` module with default `gdx-backends-robovm` backend. It keeps saying:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
	at com.badlogic.gdx.graphics.glutils.VertexBufferObject.<init>(VertexBufferObject.java:69)
	at com.badlogic.gdx.graphics.Mesh.makeVertexBuffer(Mesh.java:145)
```

**Comment by obigu** [comment] 2020-04-20 16:13
@kakashidinho Please ask the question in the Gitter channel I've linked on my previous comment for RoboVM related stuff. Thanks!

**Comment by kakashidinho** [comment] 2020-04-20 16:16
Thanks, I will ask there also. Just that I'm not sure whether this is robovm issue or libgdx's configurations issue.

**Comment by crykn** [comment] 2020-10-05 15:24
Hey @kakashidinho, sorry to bug you, but have you ever gotten the ANGLE stuff working for iOS?

**Comment by kakashidinho** [comment] 2020-10-06 07:22
> Hey @kakashidinho, sorry to bug you, but have you ever gotten the ANGLE stuff working for iOS?

No, I encountered some errors when compiling lingdx + robovm for iOS which I haven’t managed to find the root cause yet.

**Comment by davidgiga1993** [comment] 2021-05-05 17:40
Anything working with metal? I somehow have the feeling that apple will deprecate openGL faster now that they have full control over the chips used by all their devices

**Closed** 2022-05-12 19:34 UTC
Labels: desktop
