### ISSUE TITLE
Error on startup in NixOS

### ISSUE THREAD

**Issue by ChetRippo** [libgdx/libgdx#2971] opened 2015-03-23 03:18 UTC
Hi,

A steam user for my game just reported this exception whenever he starts it up:

Exception in thread "LWJGL Application"
java.lang.ExceptionInInitializerError at
com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:446)
at
com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:118)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0 at
org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:954)
at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738) at
org.lwjgl.opengl.Display.<clinit>(Display.java:138) ... 2 more AL lib:
(EE) alc_cleanup: 1 device not closed 

This is on NixOS 64-bit. Does LibGDX support this OS?

**Comment by sinistersnare** [comment] 2015-03-23 04:33
Im pretty sure a better question would be, does java or lwjgl support nixos?

**Comment by xoppa** [comment] 2015-03-23 08:46
Probably duplicate of #2743

**Closed** 2015-03-23 08:46 UTC
