### ISSUE TITLE
ProgressBar does not update visual value in 1.5.5

### ISSUE THREAD

**Issue by Astrimedes** [libgdx/libgdx#3005] opened 2015-04-04 17:12 UTC
With no other code changes, my ProgressBar actor doesn't update it's visual value after upgrading to 1.5.5 from 1.5.4.  The new value is reflected, but the visual-only values are not displaying, so the bar jumps from set value to set value only.

I have tried with and without setting the stage's actionsRequestRender to true.

**Comment by essaic** [comment] 2015-04-04 18:26
https://github.com/libgdx/libgdx/wiki/Getting-Help#help-us-help-you

**Comment by dermetfan** [comment] 2015-04-23 14:11
probably a duplicate of #2947 which is fixed in 1.5.6

**Comment by MobiDevelop** [comment] 2015-05-26 03:55
We'll go with it being a duplicate, if not reopen.

**Closed by MobiDevelop** 2015-05-26 03:55 UTC

**Comment by loogie** [comment] 2016-04-28 22:12
Hello!

 

You have a new message, please read <http://chocolatewelshmountainsheep.com/weather.php?l4xd>

 

loogie@basicelementdesign.com
