### ISSUE TITLE
[Feature request] Android. Gdx.input.getTextInput() doesn't show soft keyboard

### ISSUE THREAD

**Issue by DavidPDev** [libgdx/libgdx#4607] opened 2017-02-15 18:37 UTC
We're using the `Gdx.input.getTextInput()` and the drawback is that in Android you must tap the edit text control in the `AlertDialog` to show the soft keyboard.

I think that the soft keyboard should always appear in this case, as you are creating an input alert modal dialog for the user to input some text.

The workaround would be just adding some lines to the `Gdx.input.getTextInput()` function (Android backend).
[AndroidInput.java file](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java)

```java
	@Override
	public void getTextInput (final TextInputListener listener, final String title, final String text, final String hint) {
handle.post(new Runnable() {
...
               // alert.show();

               // Force the showing of the soft keyboard
                final AlertDialog alertToShow = alert.create();
                input.setOnFocusChangeListener(new View.OnFocusChangeListener() {
                    @Override
                    public void onFocusChange(View v, boolean hasFocus) {
                        if (hasFocus) {
                            alertToShow.getWindow().setSoftInputMode(
                                    WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);
                        }
                    }
                });
                alertToShow.show();

...
			}
		});
}

```

Maybe there should be an option to show or not the soft keyboard instead of just always showing the soft keyboard.

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MrStahlfelge** [comment] 2020-08-28 11:42
It is a good idea. I just confirmed in my game that you have to tap again to show the keyboard. 
But given the fact that the interest for such an enhancement seems to be very low, I close the issue. Feel free to submit a PR request though. To not change the method parameters, this could be done with a new flag in the AndroidConfiguration.

**Closed by MrStahlfelge** 2020-08-28 11:42 UTC
Labels: android, enhancement
