### ISSUE TITLE
xoffset set to minus padding value for all letters

### ISSUE THREAD

**Issue by wrobelp** [libgdx/libgdx#3994] opened 2016-04-07 05:24 UTC
I'm using Hiero to create Distant Field fonts for Java.
When I create the font all the values of xoffset are -8 when I set padding 8.
#### Issue details

I loading from File. The problem is for all files I've tried.
The problem occurs on Java version. For FreeType version it's working well.

I creating Distant Fields, but I think problem occurs for any Java version settings. I can test it.

I tried to debug it. The Glyphs are created ok when switching to FreeType, but they're NOT reloaded/creted when switching to Java and change somewhere along the way. Cause later when saving to file values in Glyphs are all the same.

I also tried using latest nightly but same problem occurs.
#### Reproduction steps/code

Load font from .ttf file. Choose Java, add Distant Fileds, delete Color. Set up padding. Saving to BMP.
#### Version of LibGDX and/or relevant dependencies

I use newest runnable-hiero.jar v5

For now I'm using two .fnt files to load one font - one for xoffsets and one for all other data.
#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

Thank You for Your Tools :)

**Comment by Tom-Ski** [comment] 2016-04-07 07:45
Im guessing you are using Hiero?!? Please don't delete the issue template, fill it out so we can fully understand what the issue you are reporting is.

**Comment by wrobelp** [comment] 2016-04-07 09:34
Is it enough information?

**Comment by cheapbrain** [comment] 2016-04-13 16:37
I'm having the same issue with hiero, and after some testing I can confirm that the issue is caused by selecting the java rendering system.

**Comment by badlogic** [comment] 2016-12-04 14:06
Related to #4106

**Comment by NathanSweet** [comment] 2016-12-04 15:47
Looks fixed by #4282, if not will reopen.

**Closed by NathanSweet** 2016-12-04 15:47 UTC
Labels: tools
