### ISSUE TITLE
Animations are not played in some cases with bones

### ISSUE THREAD

**Issue by ssebastian** [libgdx/libgdx#3000] opened 2015-04-02 16:14 UTC
Platform: Android
Libgdx version: 1.5.5

Used fbx-conf command: "./fbx-conv-lin64 -f [fibFile] [g3dbFile]"

broken.g3dj: http://pastebin.com/NtWG8VN9
Output:
```
INFO:     FBX to G3Dx converter, version 0.01.0000 x64 (pre-release)
STATUS:   Loading source file
WARNING:  [Cube] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Armature] Node uses RrSs mode, transformation might be incorrect
WARNING:  [ArmUp_L] Node uses RrSs mode, transformation might be incorrect
WARNING:  [ArmDown_L] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Hand_L] Node uses RrSs mode, transformation might be incorrect
WARNING:  [ArmUp_R] Node uses RrSs mode, transformation might be incorrect
WARNING:  [ArmDown_R] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Hand_R] Node uses RrSs mode, transformation might be incorrect
WARNING:  [LegUp_R] Node uses RrSs mode, transformation might be incorrect
WARNING:  [LegDown_R] Node uses RrSs mode, transformation might be incorrect
WARNING:  [LegUp_L] Node uses RrSs mode, transformation might be incorrect
WARNING:  [LegDown_L] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Body] Node uses RrSs mode, transformation might be incorrect
STATUS:   [shape(Cube)] Triangulating FbxMesh geometry
WARNING:  Mesh contains vertices with zero bone weights.
STATUS:   Converting source file
STATUS:   Closing source file
STATUS:   Exporting to G3DJ file: /home/marina/Dokumente/201415-ba-nischwitz/Battles of Famato/android/assets/models/example/broken.g3dj
STATUS:   Closing exported file
```
working.g3dj: http://pastebin.com/7KybE2gv
Output:
```
INFO:     FBX to G3Dx converter, version 0.01.0000 x64 (pre-release)
STATUS:   Loading source file
WARNING:  [Cube] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Armature] Node uses RrSs mode, transformation might be incorrect
WARNING:  [ArmUp_L] Node uses RrSs mode, transformation might be incorrect
WARNING:  [ArmDown_L] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Hand_L] Node uses RrSs mode, transformation might be incorrect
WARNING:  [ArmUp_R] Node uses RrSs mode, transformation might be incorrect
WARNING:  [ArmDown_R] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Hand_R] Node uses RrSs mode, transformation might be incorrect
WARNING:  [LegUp_R] Node uses RrSs mode, transformation might be incorrect
WARNING:  [LegDown_R] Node uses RrSs mode, transformation might be incorrect
WARNING:  [LegUp_L] Node uses RrSs mode, transformation might be incorrect
WARNING:  [LegDown_L] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Body] Node uses RrSs mode, transformation might be incorrect
STATUS:   [shape(Cube)] Triangulating FbxMesh geometry
WARNING:  Mesh contains vertices with zero bone weights.
STATUS:   Converting source file
STATUS:   Closing source file
STATUS:   Exporting to G3DJ file: /home/marina/Dokumente/201415-ba-nischwitz/Battles of Famato/android/assets/models/example/working.g3dj
STATUS:   Closing exported file
```

# What went wrong:
All skinned vertices ("models/example/broken.g3db") are at the wrong position and do not animate. The "models/example/working.g3db" looks correct when rendered without the broken one. The only difference is that the cloak has an additional texture assigned in "models/example/broken.g3db". 

It seems that the a_boneWeight attributes are not passed to the shader correctly.

How to reproduce:

- Use the following code:

```java
public class Screen implements ApplicationListener {

    private Camera camera;
    private ModelBatch modelBatch;
    private Environment environment;
    private ModelInstance workingInstance;
    private ModelInstance brokenInstance;
    private AnimationController workingController;
    private AnimationController brokenController;

    @Override
    public void create() {
        camera = new PerspectiveCamera(67, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
        camera.position.set(3f, 2f, 5f);
        camera.lookAt(0f, 0f, 0f);
        camera.near = 0.1f;
        camera.far = 100.0f;
        camera.update();

        modelBatch = new ModelBatch();

        environment = new Environment();

        environment.set(new ColorAttribute(ColorAttribute.AmbientLight, 1f, 1f, 1f, 1.0f));
        DirectionalLight dirLight = new DirectionalLight();
        dirLight.set(Color.WHITE, 0f, -1f, 0f);
        environment.add(dirLight);

        final UBJsonReader reader = new UBJsonReader();
        final G3dModelLoader loader = new G3dModelLoader(reader);
        final Model workingModel = loader.loadModel(Gdx.files.internal("models/example/working.g3db"));
        final Model brokenModel = loader.loadModel(Gdx.files.internal("models/example/broken.g3db"));

        workingInstance = new ModelInstance(workingModel);
        brokenInstance = new ModelInstance(brokenModel);

        workingInstance.transform.translate(1f, 0f, 0f);
        brokenInstance.transform.translate(-1f, 0f, 0f);

        workingController = new AnimationController(workingInstance);
        brokenController = new AnimationController(brokenInstance);

        workingController.setAnimation("wave", -1);
        brokenController.setAnimation("wave", -1);

        Gdx.input.setInputProcessor(new CameraInputController(camera));
    }

    @Override
    public void resize(int width, int height) {
        camera.viewportHeight = height;
        camera.viewportWidth = width;
    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(0.5f, 0.5f, 0.5f, 0);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
        workingController.update(Gdx.graphics.getDeltaTime());
        brokenController.update(Gdx.graphics.getDeltaTime());
        modelBatch.begin(camera);
        //modelBatch.render(workingInstance, environment);
        modelBatch.render(brokenInstance, environment);
        modelBatch.end();
    }

    @Override
    public void pause() {

    }

    @Override
    public void resume() {

    }

    @Override
    public void dispose() {
        modelBatch.dispose();
    }
}
```

- Download the models http://www.file-upload.net/download-10501007/example.zip.html
- Add the models to the assets
- Run the application. You can see the model is just lies (no animation) while the cloak is floting.
![device-2015-04-02-211028](https://cloud.githubusercontent.com/assets/2109450/6971440/c4d8c4fc-d97c-11e4-9f2d-01148f0fac93.png)
- Change the render function as follows:
```java
    @Override
    public void render() {
        Gdx.gl.glClearColor(0.5f, 0.5f, 0.5f, 0);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
        workingController.update(Gdx.graphics.getDeltaTime());
        brokenController.update(Gdx.graphics.getDeltaTime());
        modelBatch.begin(camera);
        modelBatch.render(workingInstance, environment);
        //modelBatch.render(brokenInstance, environment);
        modelBatch.end();
    }
```
- Run the application. You see a correct rendered model.
![device-2015-04-02-211251](https://cloud.githubusercontent.com/assets/2109450/6971480/122142de-d97d-11e4-9038-42e7fe36466b.png)
- Next, change the render method as follows:
```java
    @Override
    public void render() {
        Gdx.gl.glClearColor(0.5f, 0.5f, 0.5f, 0);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
        workingController.update(Gdx.graphics.getDeltaTime());
        brokenController.update(Gdx.graphics.getDeltaTime());
        modelBatch.begin(camera);
        modelBatch.render(workingInstance, environment);
        modelBatch.render(brokenInstance, environment);
        modelBatch.end();
    }
```
- Run the application. Both models lay while the cloaks are floting.
![device-2015-04-02-211615](https://cloud.githubusercontent.com/assets/2109450/6971547/86850ba6-d97d-11e4-90ae-64f9a22c9bd7.png)
- Change the render method as follows:
```java
    @Override
    public void render() {
        Gdx.gl.glClearColor(0.5f, 0.5f, 0.5f, 0);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
        workingController.update(Gdx.graphics.getDeltaTime());
        brokenController.update(Gdx.graphics.getDeltaTime());
        modelBatch.begin(camera);
        modelBatch.render(brokenInstance, environment);
        modelBatch.render(workingInstance, environment);
        modelBatch.end();
    }
```
- Run the application. Both models are waving. The brokenModel is missing its cloak.
![device-2015-04-02-211800](https://cloud.githubusercontent.com/assets/2109450/6971785/4decdcb8-d97f-11e4-9fdf-f877d5111950.png)

**Comment by xoppa** [comment] 2015-04-02 16:32
Please pastebin the g3dj (textual) files instead of g3db (binary) files. Also, could you include the fbx-conv command you've used and its output? How did you verify that this is indeed an issue with libgdx?

**Comment by ssebastian** [comment] 2015-04-02 19:31
I updated the issue description.

For me it really looks like a bug in the default shader since the animation also works fine with the depth shaders. Also the models do not change just because I change the render order.

**Comment by xoppa** [comment] 2015-04-02 19:56
> WARNING:  Mesh contains vertices with zero bone weights.

The default shader doesn't support a skinned mesh without bones attached to it. If you look at both your models you'll see that they contain vertices with all zero bone weights. I'm surprised that it renders anything at all. It depends on how the driver deals with it I guess. Anyways, this is not an issue of libgdx, it is by design. Duplicate of #1346.

**Closed by xoppa** 2015-04-02 19:56 UTC

**Comment by ssebastian** [comment] 2015-04-02 21:33
In my point of view the default shader should somewhere indicate that it does not support non attached vertices. Since it depends on the shader whether not attached vertices are supported, I think that the warning in the fbx-conv is not sufficient. Also I cannot find in the documentation (javadoc) that the shader does not support it. Furthermore good error messages (exceptions) are an indicator for good code quality. If it is not supported it should stop since it is breaking other models resulting in that it is hard to find the real problem.

**Comment by xoppa** [comment] 2015-04-02 22:33
> Since it depends on the shader whether not attached vertices are supported

You probably misunderstood the comment in that other issue. It is common to assume that blend weights are normalized, that's not specific to the default shader. Just like it's assumed that color values are in the 0 - 1 range.

> Furthermore good error messages (exceptions) are an indicator for good code quality

I'm afraid that we won't update the default shader to check each frame, each vertex of each skinned mesh whether the blend weights are normalized. I hope that you understand that really wouldn't be good quality. Obviously, we also can't just "stop" (not sure what you expect from that) in the shader.

Also, you were presented with a warning message and you decided to ignore it. I don't see why adding another warning would help.

> resulting in that it is hard to find the real problem.

Fbx-conv literally warned you about the real problem.

I agree with you that it might help to improve the documentation. In this case I think that the issue might be that you expected it to work in the first place. Would you mind to contribute this to the documentation, preferable with some instructions on how to create a valid model? This page would be a good place: https://github.com/libgdx/libgdx/wiki/Importing-Blender-models-in-LibGDX. I don't know modelling, but I guess that there should be some method while modelling to make sure that each skinned vertex is attached to at least one bone. If you think that I would help to also update the javadocs then please consider sending a pull request for that.

**Comment by ssebastian** [comment] 2015-04-07 19:49
> I'm afraid that we won't update the default shader to check each frame, each vertex of each skinned mesh whether the blend weights are normalized.

Of course that would be a bad idea. 

Unfortunately computer graphics is not my main subject. But as far as I can see the DefaultShader sets (in the init method) the location of the a_boneWeights to -1 if not all vertices have weights. If the renderable passed to the init is correct, then the animation works, otherwise not. I am not sure, but if the shader knows that there are missing weights at that point, this would be a good place to "stop". With "stop" I mean for instance throwing an GdxException("Mesh contains vertices with zero bone weights. It is common to assume that blend weights are normalized......"). 

> Also, you were presented with a warning message and you decided to ignore it. I don't see why adding another warning would help.

Yes, I should not have had ignored that warning. Unfortunately I did not see the output of fbx-conf. But that is my problem. When I updated the issue description I saw this warning but I did not know that this is the cause of this issue. Did you tried to google this warning? Right now you can find exactly two links. One is the source code of fbx-conf and the other one is unrelated to this problem. If you are not aware of this "common assumption" you do not know what that actually means. Perhaps extending the warning with "It is common to assume that blend weights are normalized. The model might not be rendered correctly" or something like that could also help.

> Fbx-conv literally warned you about the real problem.

fbx-conf is not libgdx. It would be also possible that one is using libgdx without using fbx-conf. So I feel like a warning in that tool is not equivalent to a warning/error in libgdx. 

Another idea would be that you check the constraints in the model loader. If you think that it is too time consuming it might be an idea to invent a "strict mode" that developers can enable while developing/debugging the application and diable in production.
