### ISSUE TITLE
Missing classes from documentation

### ISSUE THREAD

**Issue by Arcfej** [libgdx/libgdx#6027] opened 2020-04-28 14:48 UTC
I hope I supposed to open an issue and not do something else.

I tried to search for the Lwjgl3ApplicationConfiguration and its related classes' documentation online but couldn't find it here: https://libgdx.badlogicgames.com/ci/nightlies/docs/api/

**Comment by crykn** [comment] 2020-04-28 19:58
Duplicate of #4667, but nonetheless a valid point.

**Comment by kudo-lee** [comment] 2020-06-18 08:03
> [＃4667](https://github.com/libgdx/libgdx/issues/4667)重复，但仍然有效。

Yes

**Comment by NathanSweet** [comment] 2020-07-17 20:05
Duplicate of: #4667

**Closed by NathanSweet** 2020-07-17 20:05 UTC
