### ISSUE TITLE
Minimal JRuby libGDX game crashing

### ISSUE THREAD

**Issue by jrab89** [libgdx/libgdx#6473] opened 2021-03-29 22:46 UTC
#### Issue details
I'm trying to get a minimal libGDX game working with JRuby. I'm using [jbundler](https://github.com/mkristian/jbundler) to resolve and install Java dependencies. However, my game crashes with the error message `Couldn't load shared library 'libgdx64.dylib' for target: Mac OS X, 64-bit`

Jarflie
```ruby
jar 'com.badlogicgames.gdx:gdx', '1.9.4'
jar 'com.badlogicgames.gdx:gdx-backend-lwjgl', '1.9.4'
jar 'com.badlogicgames.gdx:gdx-platform', '1.9.4'
```

hello_libgdx_from_jruby.rb
```ruby
require 'jbundler'

java_import 'com.badlogic.gdx.ApplicationAdapter'
java_import 'com.badlogic.gdx.backends.lwjgl.LwjglApplication'
java_import 'com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration'

class HelloLibgdxFromJruby < ApplicationAdapter
end

LwjglApplication.new(HelloLibgdxFromJruby.new,
                     LwjglApplicationConfiguration.new)
```

#### Reproduction steps/code

```
$ jgem install jbundler
Successfully installed jbundler-0.9.3
Parsing documentation for jbundler-0.9.3
Done installing documentation for jbundler after 1 seconds
1 gem installed
$ jbundle install
Jar dependencies are up to date !

jbundler provided classpath:
----------------

jbundler runtime classpath:
---------------------------
/Users/jeff.rabovsky/.m2/repository/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
/Users/jeff.rabovsky/.m2/repository/org/yaml/snakeyaml/1.26/snakeyaml-1.26.jar
/Users/jeff.rabovsky/.m2/repository/com/badlogicgames/jlayer/jlayer/1.0.1-gdx/jlayer-1.0.1-gdx.jar
/Users/jeff.rabovsky/.m2/repository/org/lwjgl/lwjgl/lwjgl_util/2.9.2/lwjgl_util-2.9.2.jar
/Users/jeff.rabovsky/.m2/repository/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-windows.jar
/Users/jeff.rabovsky/.m2/repository/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
/Users/jeff.rabovsky/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.9.4/gdx-platform-1.9.4.jar
/Users/jeff.rabovsky/.m2/repository/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
/Users/jeff.rabovsky/.m2/repository/com/badlogicgames/gdx/gdx/1.9.4/gdx-1.9.4.jar
/Users/jeff.rabovsky/.m2/repository/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
/Users/jeff.rabovsky/.m2/repository/com/badlogicgames/gdx/gdx-backend-lwjgl/1.9.4/gdx-backend-lwjgl-1.9.4.jar
/Users/jeff.rabovsky/.m2/repository/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-osx.jar
/Users/jeff.rabovsky/.m2/repository/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
/Users/jeff.rabovsky/.m2/repository/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
/Users/jeff.rabovsky/.m2/repository/jline/jline/2.14.6/jline-2.14.6.jar
/Users/jeff.rabovsky/.m2/repository/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-linux.jar
/Users/jeff.rabovsky/.m2/repository/org/lwjgl/lwjgl/lwjgl/2.9.2/lwjgl-2.9.2.jar

jbundler test classpath:
------------------------
        --- empty ---

jbundle complete !
$ jruby hello_libgdx_from_jruby.rb
Unhandled Java exception: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx64.dylib' for target: Mac OS X, 64-bit
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx64.dylib' for target: Mac OS X, 64-bit
                 load at com/badlogic/gdx/utils/SharedLibraryLoader.java:119
                 load at com/badlogic/gdx/utils/GdxNativesLoader.java:33
                 load at com/badlogic/gdx/backends/lwjgl/LwjglNativesLoader.java:47
               <init> at com/badlogic/gdx/backends/lwjgl/LwjglApplication.java:79
               <init> at com/badlogic/gdx/backends/lwjgl/LwjglApplication.java:67
          newInstance at java/lang/reflect/Constructor.java:423
    newInstanceDirect at org/jruby/javasupport/JavaConstructor.java:301
          newInstance at org/jruby/RubyClass.java:925
                 call at org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1
     invokeOther6:new at hello_libgdx_from_jruby.rb:10
               <main> at hello_libgdx_from_jruby.rb:10
  invokeWithArguments at java/lang/invoke/MethodHandle.java:627
            runScript at org/jruby/Ruby.java:1205
          runNormally at org/jruby/Ruby.java:1128
          runNormally at org/jruby/Ruby.java:1146
          runFromMain at org/jruby/Ruby.java:958
        doRunFromMain at org/jruby/Main.java:400
          internalRun at org/jruby/Main.java:292
                  run at org/jruby/Main.java:234
                 main at org/jruby/Main.java:206

Caused by:
com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: libgdx64.dylib
             readFile at com/badlogic/gdx/utils/SharedLibraryLoader.java:127
             loadFile at com/badlogic/gdx/utils/SharedLibraryLoader.java:280
                 load at com/badlogic/gdx/utils/SharedLibraryLoader.java:115
                 load at com/badlogic/gdx/utils/GdxNativesLoader.java:33
                 load at com/badlogic/gdx/backends/lwjgl/LwjglNativesLoader.java:47
               <init> at com/badlogic/gdx/backends/lwjgl/LwjglApplication.java:79
               <init> at com/badlogic/gdx/backends/lwjgl/LwjglApplication.java:67
         newInstance0 at sun/reflect/NativeConstructorAccessorImpl.java:-2
          newInstance at sun/reflect/NativeConstructorAccessorImpl.java:62
          newInstance at sun/reflect/DelegatingConstructorAccessorImpl.java:45
          newInstance at java/lang/reflect/Constructor.java:423
    newInstanceDirect at org/jruby/javasupport/JavaConstructor.java:301
                 call at org/jruby/java/invokers/ConstructorInvoker.java:100
                 call at org/jruby/java/invokers/ConstructorInvoker.java:194
         cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:407
                 call at org/jruby/runtime/callsite/CachingCallSite.java:215
                 call at org/jruby/java/proxies/ConcreteJavaProxy.java:60
         cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:407
                 call at org/jruby/runtime/callsite/CachingCallSite.java:215
          newInstance at org/jruby/RubyClass.java:925
                 call at org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1
                 call at org/jruby/internal/runtime/methods/JavaMethod.java:371
                 call at org/jruby/java/proxies/ConcreteJavaProxy.java:165
         cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:396
                 call at org/jruby/runtime/callsite/CachingCallSite.java:205
     invokeOther6:new at hello_libgdx_from_jruby.rb:10
               <main> at hello_libgdx_from_jruby.rb:10
  invokeWithArguments at java/lang/invoke/MethodHandle.java:627
                 load at org/jruby/ir/Compiler.java:89
            runScript at org/jruby/Ruby.java:1205
          runNormally at org/jruby/Ruby.java:1128
          runNormally at org/jruby/Ruby.java:1146
          runFromMain at org/jruby/Ruby.java:958
        doRunFromMain at org/jruby/Main.java:400
          internalRun at org/jruby/Main.java:292
                  run at org/jruby/Main.java:234
                 main at org/jruby/Main.java:206
```

#### Version of LibGDX and/or relevant dependencies
* libGDX 1.9.4
* java 1.8.0_172
* jruby 9.2.14.0
* macOS 10.14.6

#### Stacktrace
See above

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by tommyettinger** [comment] 2021-03-30 00:15
1.9.4 is quite old, but the problem is unrelated. You are not depending on the necessary classifier of the platforms jar; you probably need some way of adding the classifier `natives-desktop` to your dependency `jar 'com.badlogicgames.gdx:gdx-platform', '1.9.4'`. How you do this is up to you, and you'll be the one reading JRuby's docs to find out how to do this. This is not a bug in libGDX, so I'm closing. You can request help like this [on the Discord](https://discord.gg/8TC7H2v), but the issue tracker is not a help form.

**Closed by tommyettinger** 2021-03-30 00:15 UTC

**Comment by jrab89** [comment] 2021-03-30 03:10
Adding the classifier fixed it. Thanks for your help!
