### ISSUE TITLE
Not rendering after screen resize

### ISSUE THREAD

**Issue by FEDE0D** [libgdx/libgdx#2664] opened 2014-12-21 05:53 UTC
The screen doesn't render any graphics after you risize using Gdx.graphics.setDisplayMode().
This only happens if you are drawing nothing into the screen, only using glClear to show a background color.

Using the source example for a new libgdx project
``` java
public class MyGdxGame extends ApplicationAdapter {
	SpriteBatch batch;
	Texture img;
	
	@Override
	public void create () {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");
		
		Gdx.graphics.setDisplayMode(800, 600, false); //<- Change display mode
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
//		batch.draw(img, 0, 0); //<- do not render anything besides the glClear
		batch.end();
	}
}
```
Using the above code will show an empty window with no rendering. If you uncomment the batch.draw() line, the background will render again.

notes: I'm on Linux 32 using the latest stable release.

**Comment by MobiDevelop** [comment] 2015-01-24 05:01
Works correctly for me with Fedora 21.

**Comment by badlogic** [comment] 2015-02-02 17:27
Closing this as we can't reproduce it.

**Closed by badlogic** 2015-02-02 17:27 UTC
