### ISSUE TITLE
Sound setPitch() doesn't work on Android

### ISSUE THREAD

**Issue by jfnogueira** [libgdx/libgdx#4041] opened 2016-04-20 02:56 UTC
Sound 
[engine.zip](https://github.com/libgdx/libgdx/files/227149/engine.zip)

Sound engineSound = Gdx.audio.newSound(Gdx.files.internal("data/engine.wav"));
long soundId = engineSound.loop();
float pitch = 0.5f + ((velX / maxVelocity) * 0.5f);
engineSound.setPitch(soundId, pitch);
	
The above code does not change sound pitch on Android, but it works perfectly on desktop.

libgdx ver 1.7.1
Android ver 6.0.1

**Comment by intrigus** [comment] 2016-04-20 06:43
Please don't defeat the issue template.

**Comment by Tom-Ski** [comment] 2016-04-20 15:07
Please post a self contained executable example that reproduces the error.  Try not to play sounds as soon as you have used newSound also, it may not be fully loaded by then.

**Comment by jfnogueira** [comment] 2016-04-21 02:52
[setPitch.zip](https://github.com/libgdx/libgdx/files/229114/setPitch.zip)

Example attached. On desktop the sound object loops continuously while cycling its pitch. However, on Android the sound object loops but fails to change pitch.

**Comment by madpew** [comment] 2016-04-21 12:04
Not sure if it's the same problem, but I had an issue a while ago where I stumbled over the supported range in the pitch-implementations. Android has a smaller supported range for setPitch:

pitch < 0.5 and > 2 works on desktop but fails on android.

**Comment by jfnogueira** [comment] 2016-04-21 12:41
Thanks madpew. I think the cause is different though as the pitch multiplier used in this case is between 0.5 and 1.0.

**Comment by intrigus** [comment] 2016-04-21 16:07
@jfnogueira This is not a self contained executable example that reproduces the error.
We need the source of the example.

**Comment by MobiDevelop** [comment] 2016-05-03 00:29
Unable to reproduce, since you've been unable to provide an SSCCE, I'm going to close this out.

**Closed by MobiDevelop** 2016-05-03 00:29 UTC
Labels: android, need more info

**Comment by balazon** [comment] 2016-05-19 22:20
I created a simple example that's supposed to play a sound with 1.0 pitch and ~1.5 pitch alternating at each click, and on desktop this works, but on android even at relatively long intervals between clicks the sound that is played will be the wrong pitch quite often. Could you investigate the issue?
[test.zip](https://github.com/libgdx/libgdx/files/273574/test.zip)

**Comment by intrigus** [comment] 2016-05-20 00:26
Could you please provide a http://sscce.org ?
Some information about your device and android version would also be good.

**Comment by balazon** [comment] 2016-05-20 10:05
Here you go (although I couldn't make the desktop version compilable without opening it first in IDEA and setting the working directory to android/assets, but opening it in IDEA makes it much larger, so i didn't, however the android version is compilable)
Device: Sony xperia z1 compact (D5503, android 5.1.1, API 22)
I also tried this with an nvidia shield tablet (6.0.1, API 23), and a nexus 5(6.0.1, API 23), but the problem only occured on the xperia.

In the manifest the android versions are:
<uses-sdk android:minSdkVersion="8" android:targetSdkVersion="23" />
(But that can be seen in the zip too)

I also tried to build with targetSdkVersion 22 for the xperia, but no change.

Let me know if you need any more information
[test_clean.zip](https://github.com/libgdx/libgdx/files/274282/test_clean.zip)

**Comment by MobiDevelop** [comment] 2016-05-20 15:06
Your test works on my devices. I'm afraid we are not able to investigate device specific issues.

Only thing I saw that's suspect is this on the log:
`05-20 07:59:35.240 16857-16893/com.mygdx.game W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 4, track 66075 Hz, output 48000 Hz
`

Perhaps try a different sample rate (44.1k or 48k would be good standard options).

**Comment by balazon** [comment] 2016-05-21 11:26
Actually the audio file in the zip has a sample rate of 44.1 kHz, so how would i try a different sample rate?

**Comment by shoaibakram-regexsoft** [comment] 2017-02-20 04:56
Hi Anyone succeed in this issue (#pitch not working on android)...?

**Comment by balazon** [comment] 2017-02-20 09:47
I think I worked around the issue by creating all the pitch transformed sounds I needed in audacity, then playing back those with 1.0 pitch. Later I used midi to play the sounds (piano), but that might not be applicable to your app

**Comment by shoaibakram-regexsoft** [comment] 2017-02-20 11:22
Actually I have an array of coins and I need to increase pitch of sound as user collect coins in an array... but it didn't works correctly I have also changed its value between 0.1 to 0.5 but didn't succeed ... :(
