### ISSUE TITLE
libGDX 1.5.0 no audio for iPhone 5 but works for iPhone4s and simulato5

### ISSUE THREAD

**Issue by b-wojtowicz** [libgdx/libgdx#2636] opened 2014-12-09 22:42 UTC
Hello everyone,

I set up fresh sample project from libgdx 1.4.1 using generator. I added simple code:
```java
Music music;
...
create() {
  ...
  music = Gdx.audio.newMusic(new FileHandle("test.m4a"));
  music.play();
```

Here is the full sample project:
[Sample project](https://github.com/b-wojtowicz/libgdx-issue-report-no-sound-iphone5)

When launching this project on iPhone 5, there is no sound/music, but works for iPhone 4s and simulator.

Let me know if you need more info.

Best regards,
Bart

**Comment by tjcelaya** [comment] 2015-01-28 18:27
I'd like to add that I'm using the same file format and can't get any sound through the speaker, but sound does work through the headphone port in case that's helpful in any way.

**Comment by Tom-Ski** [comment] 2015-08-19 09:57
I can't reproduce this issue on my device. As this issue seems to be dead in the water since January I'm going to close this out.  If someone reproduce this, please reopen reopen with a provided test case along with the offending sound file. https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code

**Closed by Tom-Ski** 2015-08-19 09:57 UTC
Labels: bug, ios, need more info
