### ISSUE TITLE
Particle Editor open test.p failed

### ISSUE THREAD

**Issue by wangdong20** [libgdx/libgdx#7199] opened 2023-07-29 08:34 UTC
#### Issue details
I am using the particle editor to open test.p from the data folder, it prompt error open effect.

#### Reproduction steps/code
1. Open Particle Editor from gdx-1.9.4.jar
2. Open test.p in Particle Editor, error prompt.

#### Version of libGDX and/or relevant dependencies
1.9.4

#### Stacktrace
```java
java.lang.RuntimeException: Error parsing emitter: simple
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter.load(ParticleEmitter.java:970)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter.<init>(ParticleEmitter.java:94)
	at com.badlogic.gdx.graphics.g2d.ParticleEffect.loadEmitters(ParticleEffect.java:157)
	at com.badlogic.gdx.tools.particleeditor.EffectPanel.openEffect(EffectPanel.java:151)
	at com.badlogic.gdx.tools.particleeditor.EffectPanel$5.actionPerformed(EffectPanel.java:312)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: No enum constant com.badlogic.gdx.graphics.g2d.ParticleEmitter.SpawnShape.false
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter$SpawnShape.valueOf(ParticleEmitter.java:1406)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter$SpawnShapeValue.load(ParticleEmitter.java:1391)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter.load(ParticleEmitter.java:933)
	... 40 more
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] macOS

**Comment by crykn** [comment] 2023-07-29 09:18
Duplicate of #5342. And you should definitely try a more recent version of the particle editor instead of one that is nearly 7 years old...

**Closed by crykn** 2023-07-29 09:18 UTC

**Comment by wangdong20** [comment] 2023-07-29 10:35
> Duplicate of #5342. And you should definitely try a more recent version of the particle editor instead of one that is nearly 7 years old...
> 
> **Edit:** the download link can be found here: https://libgdx.com/dev/tools/

The most recent version of particle editor I tried on my Mac, it doesn't work. #7183

**Comment by raeleus** [comment] 2023-07-29 13:40
A resolution is in development, but I don't have an ETA for you. Sorry!
