### ISSUE TITLE
gdx-setup v1.6 ExtendViewport is broken

### ISSUE THREAD

**Issue by barsunduk** [libgdx/libgdx#3163] opened 2015-05-23 23:35 UTC
scaling to window size is broken.
there is an example of this bug:

<a href='http://hostingkartinok.com/show-image.php?id=a41783a5d7577cbd0a6bbe5ef3f4bb13' title='хостинг фотографий'><img src='http://s7.hostingkartinok.com/uploads/images/2015/05/a41783a5d7577cbd0a6bbe5ef3f4bb13.jpg' /></a>

**Comment by MobiDevelop** [comment] 2015-05-23 23:52
https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by MobiDevelop** [comment] 2015-05-26 03:52
Since you provided no code (or any other useful information), we're going to have to close this. If you find time to give code to reproduce the issue please do so and we'll reopen.

**Closed by MobiDevelop** 2015-05-26 03:52 UTC
