### ISSUE TITLE
SelectBox text style problem on 1.5.6

### ISSUE THREAD

**Issue by jpalaciosdev** [libgdx/libgdx#3047] opened 2015-04-23 16:06 UTC
Hi,
I'm having problems with the text displayed in SelectBox widgets.
After the update to 1.5.6, the text is shown always in white color. The color assigned to SelectBox$SelectBoxStyle.fontColor is not used (?) to render the text.
Also, color modifications through actions are not applied anymore to the text. For example, this is a fadeout of a dialog containing a SelectBox (the "play" button is in the background):
![action](https://cloud.githubusercontent.com/assets/10498177/7301404/0d5944f8-e9d2-11e4-9b83-c6722b6471b9.png)

**Comment by NathanSweet** [comment] 2015-04-23 23:49
Duplicate of #3039

**Closed by NathanSweet** 2015-04-23 23:49 UTC
