### ISSUE TITLE
Randomly High Frame Times

### ISSUE THREAD

**Issue by merc37** [libgdx/libgdx#4172] opened 2016-06-27 03:05 UTC
#### Issue details
I was making a game, utilizing a [fixed timestep](http://gafferongames.com/game-physics/fix-your-timestep/) for the first time, when I noticed that when my player (a red rectangle) was moving, occasionally it would jump forward many extra pixels. Thinking it was the timestep, I tried many different things, but eventually found that for whatever reason Libgdx was just occasionally getting really high frame times, accompanied with FPS drop. As a test, I made a new blank Libgdx project with no tools checked and nothing but Desktop selected. This new project still had the occasional high frame times and FPS drops.

#### Reproduction steps/code
I've tested this on four different computers, all with the same results. This doesn't seem to be a universal problem (as many people have successfully developed with Libgdx), but I did find some threads (I would link, but I can't seem to find them right now) on the forums about what sounds like a similar issue, but they didn't come to a resolution. Below is a barebones version of the code I was using to see the problem. For my game I wanted vSync disabled and the framerate to be unlimited, but the problem occurs regardless of whether vSync is enabled or the framerate is limited. I've also included some logs of the output of the run of the below program. I've put the in delta time seconds, only so it's easier to read.
```java
public class Barebones extends ApplicationAdapter {
	
	private float time;
	
    public void create () {
        
    }

    public void render () {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        time = Gdx.graphics.getRawDeltaTime();
		System.out.print((time*1000)+", ");
		if((time*1000)>2f){
			System.out.print("High Frame Time");
		}
		System.out.println();
    }

    public static void main (String[] args) throws Exception {
    	LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
    	config.vSyncEnabled = false;
    	config.foregroundFPS = 0;
        new LwjglApplication(new Barebones(), config);
    }
}
```
[Log1](https://paste.ee/p/schUb)
[Log2](https://paste.ee/p/4HX1S)
[Log3](https://paste.ee/p/vQonj)
The logs are quite large; I recommend just Ctrl+F and look for the word High. This will show the frame times that are significantly higher than the usual ones.

#### Version of LibGDX and/or relevant dependencies
Using Libgdx version 1.9.3.

#### Affected Platforms
I've only seen this behavior on Windows, but i haven't tried it on other platforms, beacuse what I was making was for the desktop only.

**Comment by xoppa** [comment] 2016-06-27 05:16
Duplicate of #3348

**Closed by xoppa** 2016-06-27 05:16 UTC
