### ISSUE TITLE
java.lang.NullPointerException at com.badlogic.gdx.graphics.g2d.TextMarkup.setDefaultChunk

### ISSUE THREAD

**Issue by haikami** [libgdx/libgdx#2772] opened 2015-01-23 20:57 UTC
I am using gdx  1.5.2 and got the following crash report from an android device running 4.4.4:
```java
java.lang.NullPointerException
at com.badlogic.gdx.graphics.g2d.TextMarkup.setDefaultChunk(TextMarkup.java:177)
at com.badlogic.gdx.graphics.g2d.TextMarkup.clear(TextMarkup.java:144)
at com.badlogic.gdx.graphics.g2d.BitmapFontCache.clear(BitmapFontCache.java:308)
at com.badlogic.gdx.graphics.g2d.BitmapFont.draw(BitmapFont.java:259)
```

The line that crashed is:
```
scoreFontMedium.draw(batch, text, (int)(w+ K.POS_SCORE_W_1*textScale),(int)(h-K.POS_SCORE_H_2*textScale));
```

This happened on a random iteration and only once. It seems that in the following  method of TextMarkup class, newChunk is null, but I have no idea what is all this about.
```java
	public void setDefaultChunk (Color color, int start) {
		ColorChunk newChunk = colorChunkPool.obtain();
		newChunk.color.set(color);
		newChunk.start = start;
		colorChunks.add(newChunk);
		setDefaultColor(newChunk.color);
	}
```

Any idea of what's going on?

**Comment by badlogic** [comment] 2015-02-02 16:40
No idea what could cause this. `colorChunkPool` can not return null, and `newChunk.color` can also never be null. The only thing i see in `TextMarkup` that's a bit wonky is the use of a static pool. I fixed that up a little. Please give the latest nightlies a try. Closing this out, as we can't reproduce it.

**Closed by badlogic** 2015-02-02 16:40 UTC

**Comment by BenGoldberg** [comment] 2015-03-18 02:21
I'm running the latest version of libgdx (1.5.4) on an Android device running 4.0.4 and I got this same exception.

```java
com.badlogic.gdx.graphics.g2d.TextMarkup.setDefaultChunk(TextMarkup.java:192) at com.badlogic.gdx.graphics.g2d.TextMarkup.clear(TextMarkup.java:159) at com.badlogic.gdx.graphics.g2d.BitmapFontCache.clear(BitmapFontCache.java:329) at com.badlogic.gdx.graphics.g2d.BitmapFontCache.setText(BitmapFontCache.java:571)
```

I've only seen it happen once so I'm not sure if I can recreate it.
