### ISSUE TITLE
Texture Data generated from float[] values 

### ISSUE THREAD

**Issue by davids91** [libgdx/libgdx#6516] opened 2021-05-01 06:12 UTC
#### Issue details
https://stackoverflow.com/questions/67298120/loading-generated-texture-data-is-inconclusive-in-libgdx-lwjgl

I have tried to generate a texture manually to upload to a texture, and then display it, but it seems floating point values 
are not supported when doing so. 
When the generated texture is rendered, it seems to deviate from the original color/value. In most cases the values provided by the FloatBuffers result in a black texture, sometimes there is an unexpected color(e.g. lime-green instead of beige).

#### Reproduction steps/code
Relevant source code is in the linked question

#### Version of LibGDX and/or relevant dependencies
Latest LibGDX at 2021.05.01. ; OpenGL ES

#### Stacktrace
N/A

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by tommyettinger** [comment] 2021-05-06 04:00
I answered on StackOverflow; long story short, it's a byte-order issue with your FloatBuffer. I hope the fix I provided on StackOverflow is sufficient; since this doesn't appear to be a bug in libGDX (although like all of the raw OpenGL APIs, it could be viewed as caused by a lack of documentation), I'm closing.

**Closed by tommyettinger** 2021-05-06 04:00 UTC

**Comment by mgsx-dev** [comment] 2021-05-06 11:27
see also BufferUtils#newFloatBuffer
