### ISSUE TITLE
LWJGL3 VSYNC issues (have a fix)

### ISSUE THREAD

**Issue by Ktar5** [libgdx/libgdx#5827] opened 2019-10-31 02:59 UTC
Removed, check out this comment for the real fix that I found. https://github.com/libgdx/libgdx/issues/5826#issuecomment-578456720

**Comment by mgsx-dev** [comment] 2019-10-31 10:29
maybe a duplicate of #4274

**Comment by Ktar5** [comment] 2019-10-31 19:12
I've been told by mgsx that this doesn't fix the issue at hand since that method doesn't do all the vsync issues. However in my testing this has completely solved all screen tearing issues where the Sync class didn't really solve it without external forcing of vsync by my nvidia driver interface. I could definitely be wrong but I believe this warrants more testing.

**Comment by NathanSweet** [comment] 2020-07-17 19:58
Duplicate of: #4274

**Closed by NathanSweet** 2020-07-17 19:58 UTC
