### ISSUE TITLE
GWT version conflict 2.8.2 <-> 2.10.0

### ISSUE THREAD

**Issue by Hyperion2400** [libgdx/libgdx#7325] opened 2024-01-21 14:30 UTC
#### Issue details
I built a project with gdx-setup and tried to run the html module. However I got the error below.
After some messing around I found that downgrading the GWT version in html/build.gradle to 2.8.2 from 2.10.0 fixed that issue.

It's probably related to these commits from 2 months ago that upgrade GWT and add a dependency: https://github.com/libgdx/libgdx/commit/93503b4120f2c6002c7b1ecc73fc36bef4b678a0 https://github.com/libgdx/libgdx/commit/fe99b6a16a4146aab76a728f607d7a3bb49ece6f
However when I search gdx-backend-gwt-1.12.1.jar I only find a reference to 2.8.2, not 2.10.0.

The added dependency also doesn't seem to be compatible with Java 8. I only got it to work with Java 11.

This issue was also mentioned here: https://github.com/libgdx/libgdx/pull/7250#issuecomment-1810311362

#### Reproduction steps/code
- generate html project with gdx-setup 1.12.1
- run gradlew html:superdev

#### Version of libGDX and/or relevant dependencies
gdx-setup: 1.12.1
Java: 11
IDE: IntelliJ IDEA 2023.2.5

#### Stacktrace
```
Compiling module com.hyperion.tunnelcopter.GdxDefinitionSuperdev
   [ERROR] Errors in 'generated://EDE6402AFBDE09D1E8D4A9C9E9098379/com/badlogic/gwtref/client/IReflectionCache2Generated.java'
      [WARN] Line 15151: Referencing method 'com.badlogic.gdx.scenes.scene2d.Actor.ancestorsVisible': method 'com.badlogic.gdx.scenes.scene2d.Actor.ancestorsVisible()' is deprecated
      [WARN] Line 15952: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActor': method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActor(Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 15953: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorAt': method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorAt(ILcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 15954: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorBefore': method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorBefore(Lcom/badlogic/gdx/scenes/scene2d/Actor;Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 15955: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorAfter': method 'com.badlogic.gdx.scenes.scene2d.ui.Container.addActorAfter(Lcom/badlogic/gdx/scenes/scene2d/Actor;Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 16343: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.setWidget': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.setWidget(Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 16344: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.getWidget': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.getWidget()' is deprecated
      [WARN] Line 16345: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActor': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActor(Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 16346: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorAt': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorAt(ILcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 16347: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorBefore': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorBefore(Lcom/badlogic/gdx/scenes/scene2d/Actor;Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 16348: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorAfter': method 'com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.addActorAfter(Lcom/badlogic/gdx/scenes/scene2d/Actor;Lcom/badlogic/gdx/scenes/scene2d/Actor;)' is deprecated
      [WARN] Line 16453: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.SelectBox.showList': method 'com.badlogic.gdx.scenes.scene2d.ui.SelectBox.showList()' is deprecated
      [WARN] Line 16455: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.SelectBox.hideList': method 'com.badlogic.gdx.scenes.scene2d.ui.SelectBox.hideList()' is deprecated
      [WARN] Line 16526: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.Slider.setSnapToValues': method 'com.badlogic.gdx.scenes.scene2d.ui.Slider.setSnapToValues([FF)' is deprecated
      [WARN] Line 16920: Referencing method 'com.badlogic.gdx.scenes.scene2d.ui.Tree.getNodes': method 'com.badlogic.gdx.scenes.scene2d.ui.Tree.getNodes()' is deprecated
      [WARN] Line 17323: Referencing method 'com.badlogic.gdx.scenes.scene2d.utils.Selection.hasItems': method 'com.badlogic.gdx.scenes.scene2d.utils.Selection.hasItems()' is deprecated
      [WARN] Line 17673: Referencing method 'com.badlogic.gdx.utils.JsonValue.size': method 'com.badlogic.gdx.utils.JsonValue.size()' is deprecated
      [ERROR] Line 7088: No source code is available for type jsinterop.annotations.JsMethod; did you forget to inherit a required module?
      [ERROR] Line 7328: No source code is available for type jsinterop.annotations.JsIgnore; did you forget to inherit a required module?
      [ERROR] Line 7342: No source code is available for type jsinterop.annotations.JsType; did you forget to inherit a required module?
      [ERROR] Line 7595: No source code is available for type jsinterop.annotations.JsProperty; did you forget to inherit a required module?
   Tracing compile failure path for type 'com.badlogic.gwtref.client.IReflectionCache2Generated'
      [ERROR] Errors in 'generated://EDE6402AFBDE09D1E8D4A9C9E9098379/com/badlogic/gwtref/client/IReflectionCache2Generated.java'
         [ERROR] Line 7088: No source code is available for type jsinterop.annotations.JsMethod; did you forget to inherit a required module?
         [ERROR] Line 7595: No source code is available for type jsinterop.annotations.JsProperty; did you forget to inherit a required module?
         [ERROR] Line 7342: No source code is available for type jsinterop.annotations.JsType; did you forget to inherit a required module?
         [ERROR] Line 7328: No source code is available for type jsinterop.annotations.JsIgnore; did you forget to inherit a required module?
   [ERROR] Hint: Check that the type name 'com.badlogic.gwtref.client.IReflectionCache2Generated' is really what you meant
   [ERROR] Hint: Check that your classpath includes all required source roots
   [ERROR] Errors in 'com/badlogic/gwtref/client/ReflectionCache.java'
      [ERROR] Line 23: Rebind result 'com.badlogic.gwtref.client.IReflectionCache2Generated' could not be found

> Task :html:draftCompileGwt FAILED
```

#### Please select the affected platforms
- [x ] HTML/GWT

**Comment by Frosty-J** [comment] 2024-01-21 16:46
Duplicate of #7283. libGDX 1.12.1 for GWT 2.8; 1.12.2-SNAPSHOT for 2.10. Since gdx-setup builds aren't aligned with libGDX releases, it likely won't work out-of-the-box until the next release of libGDX.

**Closed** 2024-01-21 17:28 UTC
Labels: duplicate
