### ISSUE TITLE
Intersector.intersectSegments returns wrong result for specific consecutive segments

### ISSUE THREAD

**Issue by FlorentMasson** [libgdx/libgdx#5057] opened 2018-01-14 19:55 UTC
#### Issue details
For specific segments points, when the segments have a point in common, Intersector.intersectSegments returns true instead of false.

#### Reproduction steps/code
```
res=Intersector.intersectSegments(31.485935f, 199.49142f, 35.280785f, 203.2859f, 36.99131f, 204.99626f, 35.280785f, 203.2859f, tmp);
System.out.println(res+" "+tmp);
res=Intersector.intersectSegments(31.485935f, 199.49142f, 35.280785f, 203.2859f, 35.280785f, 203.2859f, 36.99131f, 204.99626f, tmp);
System.out.println(res+" "+tmp);
```
Actual result:
```
true (34.859135,202.86429)
true (35.280785,203.2859)
```

Expected result:
```
false (0.0,0.0)
false (0.0,0.0)
```

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [ ] MacOS
(probably all, only tested on Windows&Linux)

**Comment by FlorentMasson** [comment] 2018-02-18 17:18
Not sure whether the result should be true or false, but the intersection point is just in the middle of one segment and therefore plain wrong (the cross product in my examples is near-zero but there is no near-zero comparison)

**Comment by obigu** [comment] 2018-02-18 22:19
But that is caused by loating-point arithmetic, not by a wrong implementation https://blogs.oracle.com/corejavatechtips/the-need-for-bigdecimal

**Comment by FlorentMasson** [comment] 2018-03-04 10:14
I know, but some implementation consider near zero numbers as zero by testing it against a low delta value like 1e-7
Also the algorithm output could be strengthened by checking the returned point is actually inside 1 of the 2 segements

**Comment by obigu** [comment] 2022-05-18 20:37
Closing this as the issue is not implementation related but a floating-point arithmetic precision limitation. Assuming colinearity is not intersection, the algorithm is ok.

**Closed by obigu** 2022-05-18 20:37 UTC
