### ISSUE TITLE
ProGuard obfuscation rules

### ISSUE THREAD

**Issue by SimpGameDev** [libgdx/libgdx#6982] opened 2022-09-06 17:33 UTC
#### Issue details
Creating an Android build with `minifyEnabled true` crashes:
com.badlogic.gdx.utils.SerializationException: Field not found: label (com.badlogic.gdx.scenes.scene2d.ui.TextTooltip$TextTooltipStyle)
  The file proguard-rules.pro does not contain the necessary rules to prevent that.
I tried this, but it didn't work:
```
-keep class com.badlogic.gdx.scenes.scene2d.ui.Skin
-keepclassmembers class com.badlogic.gdx.scenes.scene2d.ui.Skin
-keep class com.badlogic.gdx.scenes.scene2d.ui.TextTooltip
-keepclassmembers class com.badlogic.gdx.scenes.scene2d.ui.TextTooltip
-keep class com.badlogic.gdx.scenes.scene2d.ui.TextTooltip$TextTooltipStyle
-keepclassmembers class com.badlogic.gdx.scenes.scene2d.ui.TextTooltip$TextTooltipStyle
```

#### Reproduction steps/code
```
skin = new Skin();
  FreeTypeFontGenerator generator = new FreeTypeFontGenerator(Gdx.files.internal("ui/myfont.ttf"));
  FreeTypeFontParameter parameter = new FreeTypeFontParameter();
  parameter.size = 40;
  BitmapFont font = generator.generateFont(parameter);
  skin.add("font", font);
  skin.addRegions(new TextureAtlas("ui/myskin.atlas"));
  skin.load(Gdx.files.internal("ui/myskin.json"));
```

  

#### Version of libGDX and/or relevant dependencies
gdxVersion = '1.11.0'

#### Stacktrace
com.badlogic.gdx.utils.SerializationException: Error reading file: ui/myskin.json
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:106)
        at com.example.mygame.MyGame.createSkin(MyGame.java:47)
        at com.example.mygame.MyGame.create(MyGame.java:32)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:281)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
     Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: ui/myskin.json
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:803)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:104)
        at com.example.mygame.MyGame.createSkin(MyGame.java:47) 
        at com.example.mygame.MyGame.create(MyGame.java:32) 
        at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:281) 
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557) 
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272) 
     Caused by: com.badlogic.gdx.utils.SerializationException: Field not found: label (com.badlogic.gdx.scenes.scene2d.ui.TextTooltip$TextTooltipStyle)
    Serialization trace:
    {}."com.badlogic.gdx.scenes.scene2d.ui.TextTooltip$TextTooltipStyle".default.label
        at com.badlogic.gdx.utils.Json.readFields(Json.java:898)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readFields(Skin.java:495)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:1079)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:469)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:972)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.readNamedObjects(Skin.java:518)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:507)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:501)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:1006)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:469)
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:801)
        	... 6 more

#### Please select the affected platforms
- [ X] Android

**Comment by obigu** [comment] 2022-09-16 15:57
It looks like you managed to fix this with the help of a Discord user. It'd be great if you could add a comment with the solution in case other people come across the same problem as you and then close the issue.

**Comment by Frosty-J** [comment] 2022-09-16 16:04
As this is a common problem, we should probably add the required rules for JSON skins to work into the [default configuration](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/res/com/badlogic/gdx/setup/resources/android/proguard-rules.pro). If there are reasons not to, they could still be there in the form of comments.

**Comment by obigu** [comment] 2022-09-16 16:12
Sure, we can add in the form of comments to keep the Proguard config minimal and max shrinking by default.

**Comment by itsabhiaryan** [comment] 2023-08-26 12:53
Getting crash in android release build where proguard is enabled. This is happening after libgdx version update to 1.12.0
  @obigu what solution you are referring earlier ?
  
  java.lang.ExceptionInInitializerError
                                                                                                    	at com.badlogic.gdx.scenes.scene2d.ui.Label.<clinit>(SourceFile:8)
                                                                                                    	at b4.f.<init>(SourceFile:3)
                                                                                                    	at b4.f.<init>(SourceFile:5)
                                                                                                    	at h3.k.a(SourceFile:74)
                                                                                                    	at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(SourceFile:29)
                                                                                                    	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
                                                                                                    	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
                                                                                                    Caused by: java.lang.RuntimeException: Class cannot be created (missing no-arg constructor): com.badlogic.gdx.graphics.g2d.b$a
                                                                                                    	at com.badlogic.gdx.utils.c0.<init>(SourceFile:36)
                                                                                                    	at com.badlogic.gdx.utils.z.d(SourceFile:14)
                                                                                                    	at com.badlogic.gdx.utils.z.c(SourceFile:3)
                                                                                                    	at com.badlogic.gdx.graphics.g2d.b.<clinit>(SourceFile:3)

**Comment by crykn** [comment] 2023-09-03 11:20
The solution mentioned on Discord was:
> `-keep class`  all classes that are used there
> `-keep class com.badlogic.gdx.scenes.scene2d.ui.** { <init>(...); <fields>;  }` etc
> might need Color, BitmapFont maybe some other. if it explodes it is needed

**Comment by obigu** [comment] 2024-04-20 17:20
Fixed in https://github.com/libgdx/libgdx/pull/7375

**Closed by obigu** 2024-04-20 17:20 UTC
