### ISSUE TITLE
Shader context loss when Android game started via intent

### ISSUE THREAD

**Issue by dkarv** [libgdx/libgdx#3225] opened 2015-06-23 20:52 UTC
I came over a weird issue. When resuming an application via custom intent and not the launcher, all my ```ShaderProgram```s are lost (OpenGL context loss). 

How to reproduce:
1. start app via launcher
2. pause app (go to homescreen) but not dispose it
3. restart it via intent, for example in adb shell:
```
am start -n com.example.test.android/.AndroidLauncher
```

What should happen:
The shaders are managed, they should be recompiled after context loss.

It works when:
- restarting the app via launcher
- always recreating all shaders in ```Game.resume()``` AND disabling the firstResume behaviour in ```AndroidApplication.onResume()``` somehow (otherwise the first onResume is kind of ignored)
- launching the app initially via intent when it wasn't in the background or running before

It doesn't work:
- restarting via own intent (not only the one coming from adb, also when accepting a invitation in the Google Play Games app that launches your game)

My app is not the only one with this issue, I could reproduce it here:
https://github.com/FAU-Inf2/fly-gdx/

If you need code examples of my app I will post them here.

Thanks for your good work! Maybe someone can figure out what is happening here and how to solve it.

**Comment by xoppa** [comment] 2015-06-23 20:59
Please provide enough information to reproduce the issue you're reporting, including a [sscce](http://sscce.org/) (single class test case) and the information about the device you're experiencing it on. See: https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md. Also include the steps you took to verify that this is indeed an issue with libgdx.

**Comment by MobiDevelop** [comment] 2015-06-23 21:10
Perhaps try adding `android:launchMode="singleTask"` to the activity element in your AndroidManifest.xml and see if that alleviates the problem.

**Comment by xoppa** [comment] 2015-06-23 21:14
Just browsing a bit through that code, it looks like it uses alot of lazy initialized statics which aren't managed properly. So I doubt that this is a libgdx issue.

**Comment by dkarv** [comment] 2015-06-23 21:35
@MobiDevelop adding that line resolved the problem! Thanks! Wasn't aware of that option.

@xoppa Yeah there may be some crazy code in the project, but the adb logs told me drawing failed because of the shaders that got lost with the OpenGL context, no NPE or similiar...

So it isn't really an issue with libgdx, it just isn't supported to use more than one task, am I right?
If someone wants to take a deeper look into this I can provide a sscce, otherwise the issue can be closed.

**Comment by badlogic** [comment] 2015-06-23 21:36
It is supported, unless you store mamaged resources in statics and don't
reinitialize on activity restart. Which appears to be the case in the
project.

TL:DR: DON'T USE STATICS, EVER!

**Comment by xoppa** [comment] 2015-06-23 21:42
Yeah, I never said NPE or similar and I doubt that an OpenGL context being lost is actually related (iirc, it is recovered since 2.3 ish). Anyways, using statics without managing them is going to cause issues and the issue you're describing looks alot like that. Closing this. Please feel free to open a new issue including sscce if you find an issue with libgdx and have verified that it is actually an issue with libgdx.

**Closed by xoppa** 2015-06-23 21:42 UTC
Labels: need more info

**Comment by MobiDevelop** [comment] 2015-06-23 23:24
For the sake of correctness, you probably don't actually want to use the
launchMode thing as it is discouraged by Google, though I'd be curious when
people would want more than one instance of the game open on device.

Long story short, boo statics.

**Comment by deathbeam** [comment] 2015-06-23 23:32
DON'T USE STATICS, EVER....

*gasp* com.badlogic.gdx.Gdx *gasp*
