### ISSUE TITLE
Timer only triggering repeat task in foreground.

### ISSUE THREAD

**Issue by vedi0boy** [libgdx/libgdx#4514] opened 2016-12-30 19:11 UTC
#### Issue details
When I use the [Timer](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/Timer.html#scheduleTask-com.badlogic.gdx.utils.Timer.Task-float-float-) it only ticks the timer if the program is in the foreground. I looked through the documentation and there doesn't seem to be a way to allow it in background as well. I think this should be implemented since Timer is not only used for foreground tasks.

#### Reproduction steps/code
1. Set up a repeated task with the Timer
2. Run the game
3. Focus view on another window other than the game
4. Task no longer happens until returning to game window

#### Version of LibGDX and/or relevant dependencies
1.9.4

#### Please select the affected platforms
- [x] Windows (Only one I tested)

**Comment by xoppa** [comment] 2016-12-30 20:04
duplicate of #4182

**Closed by xoppa** 2016-12-30 20:04 UTC
