### ISSUE TITLE
variable "size" is not incremented by the Array constructor

### ISSUE THREAD

**Issue by Robot717** [libgdx/libgdx#5451] opened 2018-11-16 11:22 UTC
#### Issue details:
Please see **Array.java, line 53**
```
	public Array (boolean ordered, int capacity) {
		this.ordered = ordered;
		items = (T[])new Object[capacity];
	}
```
This code resizes **_items_**, but it does not increment the **_size_** variable to correctly reflect the new size. Because of the incorrect size it's impossible to use **_Array.set()_** method as it will throw IndexOutOfBoundsException:
```
	public void set (int index, T value) {
		if (index >= size) throw new IndexOutOfBoundsException("index can't be >= size: " + index + " >= " + size);

```

#### Reproduction ### steps/code:
        Array<String> testArray = new Array<String>(2);
        testArray.set(0, "It's a bug!");

#### Version of LibGDX and/or relevant dependencies:
com.badlogicgames.gdx\gdx\1.9.8\...\gdx-1.9.8-sources.jar!\com\badlogic\gdx\scenes\scene2d\Actor.java

#### affected platforms:
- [ X ] Android
- [ X ] iOS (robovm)
- [ X ] iOS (MOE)
- [ X ] HTML/GWT
- [ X ] Windows
- [ X ] Linux
- [ X ] MacOS

**Comment by MobiDevelop** [comment] 2018-11-16 16:03
The size field represents the number of items that are in the array, not the capacity of it.

**Comment by EtK2000** [comment] 2018-11-17 16:15
As @MobiDevelop said, this is intended behavior.
Please close this issue.

**Comment by EtK2000** [comment] 2018-11-19 06:11
Capacity is the size of the backing array aka the max size without requiring creating a new backing array.

Size is the current Array (not the backing one) length, this lets you know how many values are currently in it.

So to recap:
capacity is max length without reallocation
size is equivalent to array.length

**Closed** 2018-11-19 06:44 UTC

**Comment by Robot717** [comment] 2018-11-19 07:05
Thank you for the explanation. It looks like the idea of the **_capacity_** is that you can request memory for the array elements upfront (e.g. during your game "loading") so that when you go to the "active" part of the game and you want to store (**_add()_**) data into that array, you will not have any lags caused by memory allocation if you fit within the specified capacity... After the Array's constructor is called with non-zero capacity the memory in the backing array is allocated, but you cannot write to this memory until you call **_add()_**

**Comment by NathanSweet** [comment] 2018-11-26 19:34
You can set the `size` field or use `setSize` (which returns the backing array).
