### ISSUE TITLE
GlyphLayout and newlines minor issue

### ISSUE THREAD

**Issue by ColourTann** [libgdx/libgdx#4876] opened 2017-08-30 00:37 UTC
BitmapFont font = new BitmapFont();
font.draw(batch, "Lorem ipsum dolor sit amet", 50, 50, 100, Align.center, true);
font.draw(batch, "Lorem ipsum\ndolor sit amet", 250, 50, 100, Align.center, true);

When drawing, the line breaks after "ipsum", so they should be identical if drawn on top of each other but they are not. I believe this is due to the space between "ipsum" and "dolor" being treated as part of the top line. This also affects the width reported by GlyphLayout.

Affects version 1.9.5

#### Please select the affected platforms
Probably all of them? Desktop and Android at least.

**Comment by NathanSweet** [comment] 2017-11-02 00:43
I don't know what font you are testing, but I saw weird behavior in [this modified BitmapFontTest](http://n4te.com/x/319-rpA0.txt) which I traced to [this commit](https://github.com/libgdx/libgdx/commit/0852f43d5cf8a0ffe35824ce9f7c1301d760747d#commitcomment-25344466). After [fixing the font](https://github.com/libgdx/libgdx/commit/e848f2cb2711b570bc09e4f7c0d23258712da8e9), I'm not sure if I see your problem.

Can you please check to make sure your font doesn't have the padding swapped (ie it was created after the above commit swapped the padding)? If you still have a problem, can you please post an executable example?

**Comment by xGnoSiSx** [comment] 2017-11-02 16:23
Hello Nathan, libgdx treats spaces differently in terms of length between words and as leading or trailing spaces. I went as far as to stop using multiline strings (was easier for me, and simplified localization work)

The same is true in general without line breaks: eg. " Hello World" The space before hello doesn't have the same size as the space between Hello and world. This is trivial to detect - I'm stripping all of the leading and trailing spaces automatically in my code.

**Comment by NathanSweet** [comment] 2017-11-03 01:42
@xGnoSiSx OK, but it isn't clear if that is a separate issue. Without a repro, this issue will have to be closed.

**Comment by xGnoSiSx** [comment] 2017-11-03 09:32
I understand, but i think this is liked to this one. I've been through the code that lays out glyphs and calculates total width and I was unable to follow it though or understand it. I think it has multiple problems that surface one by one with these "corner cases" and needs to be refactored & cleared out. I mean this in the best possible way - no offense to anyones work.

**Comment by NathanSweet** [comment] 2017-11-06 02:53
@xGnoSiSx I can't possible fix or refactor anything until I can actually reproduce a problem. I assume your issue is not the same as this issue, so please file a separate issue and provide an SSCCE.

Closing this issue for now. We will reopen it if @ColourTann provides an SSCCE.

**Closed by NathanSweet** 2017-11-06 02:53 UTC
Labels: scene2d

**Comment by xGnoSiSx** [comment] 2017-11-06 13:29
@NathanSweet understood, I just wanted to point this out since that bit of code is weak. 

Regardless, I've coded around those issues, so this is not a priority for me.
