### ISSUE TITLE
TiledMap properties don't get html decoded

### ISSUE THREAD

**Issue by lyze237** [libgdx/libgdx#6462] opened 2021-03-20 01:05 UTC
#### Issue details
Common xml characters (e.g. `<>&"`) get encoded (e.g. `&amp;`) inside a `.tmx` file.

Libgdx doesn't convert those values back to their original values and keeps those instead.

#### Reproduction steps/code
* Create a new tilemap in tiled.
* Create a new tileset.
* Create a custom property on a tile in the tileset with key `hi&` and value `Hello&<>"`
![image](https://user-images.githubusercontent.com/11274700/111854436-8eefbe00-891f-11eb-8410-514c4e725f7c.png)

```xml
<properties>
    <property name="hi&amp;" value="Hello&amp;&lt;&gt;&quot;"/>
</properties>
```
* Parse that propery in libgdx:

```java
for (int x = 0; x < layer.getWidth(); x++)
{
    for (int y = 0; y < layer.getHeight(); y++)
    {
        TiledMapTileLayer.Cell cell = layer.getCell(x, y);
        if (cell == null)
            continue;

        String prop = cell.getTile().getProperties().get("hi&", null, String.class); // never triggers
        if (prop != null)
        {
            System.out.println(prop);
            return;
        }
        
        prop = cell.getTile().getProperties().get("hi&amp;", null, String.class); // triggers
        if (prop != null)
        {
            System.out.println(prop); // Prints Hello&amp;&lt;&gt;&quot;
            return;
        }
    }
}
```

#### Expected

The key `hi&` should exist, and it's value should be `Hello&<>"`

#### Actually

The key `hi&amp;` exists and it's value is `Hello&amp;&lt;&gt;&quot;`

#### Version of LibGDX and/or relevant dependencies
1.9.14

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by lyze237** [comment] 2021-03-20 23:43
Seems to be a bug in the xml parser.

**Comment by mgsx-dev** [comment] 2021-03-22 10:23
i think it's a duplicate of #4831 or at least realted.

**Comment by tommyettinger** [comment] 2021-04-01 04:23
If you need to wrangle the .rl files used to generate XmlReader.java, you can get a working version of Ragel here https://github.com/sci-bots/ragel/releases/tag/ragel-6.10 . Some `@Null` annotations have been added to the current Java code, so you'd probably need to track where those were added manually to the generated file. There may be other changes, I don't know.

**Comment by mgsx-dev** [comment] 2021-04-21 21:03
i'm closing since it's a duplicate.

**Closed by mgsx-dev** 2021-04-21 21:03 UTC
