### ISSUE TITLE
LWJGL 3 backend V-Sync problem on desktop

### ISSUE THREAD

**Issue by francogp** [libgdx/libgdx#4274] opened 2016-08-27 02:20 UTC
All my monitors work on 60 hz:

### Issue details
- If I use **LWJGL 3.0, 3.1**, coded V-Sync ON (and forced V-Sync on Radeon Drivers), I get **30 FPS** (windowed mode).
- If I use **LWJGL 3.0, 3.1**, coded V-Sync ON (and DISABLED V-Sync on Radeon Drivers), I get **60 FPS** (windowed mode).
- If I use **LWJGL 2.x**, coded V-Sync ON (and forced V-Sync on Radeon Drivers), I get **60 FPS** (windowed mode) as expected on my monitor Hz.
- If I use **LWJGL 2.x**, coded V-Sync ON (and DISABLED V-Sync on Radeon Drivers), I get **60 FPS** (windowed mode)

### Expected results
I should always get 60 FPS as my monitor expect, instead of 30.

#### Version of LibGDX and/or relevant dependencies
libGDX 1.9.4, 1.9.5, 1.9.6, 1.9.7-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

Windows 10 + AMD + Forced v-sync on drivers = **30 FPS problem appear**.
Windows 10 + NVIDIA + Forced v-sync on drivers = 60 FPS.
Ubuntu 17.10 + NVIDIA+ Forced v-sync on drivers = 60 FPS.

My general PC specs: Windows 10 pro 64 bits. AMD FX-8350 8cores@4Ghz, motherboard Gigabyte GA-970A-DS3P, 16Gb ram, AMD Radeon R9 280x, SSD 840 EVO 500Gb.

_NOTE_: Using latest drivers on all PC up today.

**Comment by francogp** [comment] 2016-08-29 21:25
UPDATE:

Windows + AMD = this problem appear.
Windows + NVIDIA = CAN'T reproduce.
Linux + NVIDIA = CAN'T reproduce.

**Comment by xGnoSiSx** [comment] 2016-10-24 01:39
Win 10 Laptop, 980m GTX, 30 FPS all the time with lwjgl3.
lwjgl 2.x always at 60

latest build.

**Comment by mbrlabs** [comment] 2016-10-24 08:40
This might not be a libgdx issue at all. 
You should probably verify this with a vanilla lwjgl3 project: [https://www.lwjgl.org/guide](https://www.lwjgl.org/guide)

**Comment by xGnoSiSx** [comment] 2016-10-24 12:04
> This might not be a libgdx issue at all.
You should probably verify this with a vanilla lwjgl3 project: https://www.lwjgl.org/guide

I'll try it and report here soon.

**Comment by Scellow** [comment] 2016-10-25 01:40
Maybe your driver is overriding the VSYNC config

Check in the control panel of your driver (CCC for AMD i think), and see if VSYNC is set to override application profile

**Comment by xGnoSiSx** [comment] 2016-10-27 22:59
Well Gents, results:
If libgdx is compiled against lwjgl 3.1.0-SNAPSHOT then it has frame rate issues.

1. created project with source from  https://www.lwjgl.org/guide. Gradle generated from nightly tab in downloads/lwjgl3 homepage.

2. Added the Timer class from SilveTiger:
 https://github.com/SilverTiger/lwjgl3-tutorial/blob/master/src/silvertiger/tutorial/lwjgl/core/Timer.java
3. Updated the loop to account for the timer & set the window title:

		while ( !glfwWindowShouldClose(window) ) {
			
			delta = timer.getDelta();
			
			glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // clear the framebuffer

			timer.updateUPS();
			timer.updateFPS();
			timer.update();
			glfwSetWindowTitle(window, "FPS: " + timer.getFPS());

			glfwSwapBuffers(window); // swap the color buffers
			// Poll for window events. The key callback above will only be
			// invoked during this call.
			glfwPollEvents();
		}

Result is the test runs at 60 fps, while gdx tests at 30: (57 below is due to the snipping tool)
Of course I tested in lwjgl 2 in another demo project and in my projects that I use v2, I still get 60 fps on all those. Project source attached. Note: all demos run at 30, not just the tile test below.

I'm open to suggestions & doing more troubleshooting.

![capture](https://cloud.githubusercontent.com/assets/8305672/19788417/fe969646-9c9f-11e6-8087-163f6dd18eda.PNG)

[test project.zip](https://github.com/libgdx/libgdx/files/557210/test.project.zip)

**Comment by code-disaster** [comment] 2016-11-11 20:52
My experience here (on a MacBook Pro, OS X 10.11) completely contradicts the [GLFW documentation](http://www.glfw.org/docs/3.1/window.html#buffer_swap).

- with glfwSwapInterval(0) (which it says is no vsync) I get 60 fps
- with glfwSwapInterval(1) (vsync) I get 60/N fps, where N is the number of windows open e.g. in MultiWindowTest
- with glfwSwapInterval(-1) I get no vsync (300 fps and more), but the referenced extension document states something totally different

**Comment by xGnoSiSx** [comment] 2016-11-15 17:32
Not sure if any commits in the last 20 days affected this at all. I'll probably re-test, on the weekend with the latest build.

**Comment by badlogic** [comment] 2016-12-04 12:49
Please report back on this. I tested on macOS Sierra and Windows 10 and could not find an issue.

**Comment by xGnoSiSx** [comment] 2016-12-19 15:50
Will try out with the new release soon!

**Comment by francogp** [comment] 2016-12-19 16:01
confirmed on libGDX 1.9.4 and LWJGL 3.1

**Comment by xGnoSiSx** [comment] 2016-12-28 18:05
> confirmed on libGDX 1.9.5 and LWJGL 3.1 (windows)

Aye, The issue persists. :(

**Comment by xGnoSiSx** [comment] 2016-12-30 02:17
Update:

This narrows it down - a lot -
I wanted to try this with a clean 1.9.5 project once more. I had a suspicion that this could be a libgdx tests error. 

![test](https://cloud.githubusercontent.com/assets/8305672/21558612/cda147e0-ce34-11e6-879e-c2e8349fd0bd.PNG)

... and I had success! The issue does indeed vanish. So the problem should be either in:

1. in the libgdx tests code.
2. in the way multi window rendering is done, since the tests app has 2 of them open and 30 is 60/2. (haven't played with this functionality at all)
3. somewhere in between libgdx - lwjgl (API use or fps reporting issue?).

francogp, can you try this as well?

**Comment by francogp** [comment] 2016-12-30 02:30
@xGnoSiSx nope.. I keep getting 30FPS with that code. If I deactivate vsync from radeon driver, then I get 60 FPS, like I said before.

**Comment by xGnoSiSx** [comment] 2016-12-30 05:57
Well the above code is for a single window test. This is weird.

Not gonna say that 60/number of windows is not buggy either and that's what I'm still getting with LaunchTestsLwjgl3 still, regardless of driver vsync settings.

**Comment by Schyfis** [comment] 2017-06-20 03:19
I can confirm this bug still exists, and affects single-window applications. My graphics hardware is Radeon HD 7970 + Radeon RX 480.

I made a separate branch of my game to test the LWJGL3 backend, and I get 30 FPS as opposed to 60 FPS with the LWJGL2 backend. Switching to fullscreen changes it to 60. I also tested using a barebones project and got the same result.

Explicitly setting vsync to false in the application configuration or setting it later using `Gdx.graphics.setVSync(false)` changes it to a solid 60 FPS.

**Comment by xGnoSiSx** [comment] 2017-10-09 00:52
I've done some more recent tests and played with the vsync property as well on 1.9.6.

I've got a 980m GTX, on windows 10 on a 4k Monitor. And I've got no problems.

Turning vsync on or off at full screen has the expected behavior. Astronomical frames when off and 60 frames when on. Same results when run in windowed mode.

I also tried to reproduce https://github.com/glfw/glfw/issues/676 but I can't - or at least it's not clear when this occurs.

**Comment by francogp** [comment] 2017-10-09 01:00
@xGnoSiSx as I state before, It can be reproduced ONLY on AMD graphic cards.

**Comment by francogp** [comment] 2017-10-22 03:58
#https://github.com/LWJGL/lwjgl3/issues/340#issuecomment-338410798

**Comment by Schyfis** [comment] 2019-05-05 18:57
It's been a while but I updated my LWJGL3 project and tested again. I believe this bug no longer affects single-window applications. When vsync is on it is correctly matching my refresh rate at 60 FPS. (Radeon RX 580 + Radeon R9 200)

When vsync is off the frame rate is uncapped. Which makes sense I guess, but is this intended? There used to be something like cfg.foregroundFPS to control the FPS regardless of vsync, but it doesn't seem to exist anymore in the LWJGL3 backend. That pretty much makes vsync mandatory to prevent graphics card melting, doesn't it?

**Comment by mgsx-dev** [comment] 2019-09-27 10:19
I have a similar issue with my setup : Linux Ubuntu 16.04 + Intel GPU + Nvidia GPU.
IIRC it's a known issue with linux not handling vsync with multiple GPUs.
In my case vsync doesn't work and FPS is always uncapped.

I found a workaround by porting LWJGL2 feature : http://forum.lwjgl.org/index.php?topic=6582.0

Now i can force FPS to any value i want and prevent my graphics card melting.

Question is, should/could we include this Sync class in libgdx lwjgl3 backend? (i can make the PR)

more than fixing some vsync issues, it could be a feature if you want to force FPS for some reasons.

**Comment by Ktar5** [comment] 2019-10-31 02:44
Is there any update on fixing the actual vsync issues, as opposed to using the sync class to force the fps?

**Comment by Monarchis** [comment] 2020-01-31 11:24
@Ktar5, @francogp is the current libgdx Version (1.9.10) also affected or is this Issue already fixed / gone?

**Comment by Ktar5** [comment] 2020-02-03 20:30
@Monarchis all versions (snapshots too) are affected.

**Comment by xGnoSiSx** [comment] 2020-02-11 18:09
I should mention that I'm also using a multi-monitor setup since 2018. As Ktar mentioned, Behaviour is different  if you use such a setup. I haven't found documentation in LWJGL 3 relevant for this.
My guess is that this affects initialization and FPS somehow.

**Comment by Ktar5** [comment] 2020-02-12 20:19
THIS HAS A FIX, PLEASE LOOK AT THIS COMMENT I MADE ON A DIFFERENT POST:
https://github.com/libgdx/libgdx/issues/5826#issuecomment-578456720

**Comment by crykn** [comment] 2020-08-30 18:44
This issue seems to have mixed a few different problems, so let's try to unravel those: 

1. Vsync is not working properly in multi-window situations. This was apparently fixed in e8abed6e0c67829e30e23e723f42ba07217ca98a.
2. There were issues with vsync and AMD hardware. According to @xGnoSiSx and @Schyfis, the problems no longer seems to be happening in later libGDX versions. Moreover, since the initial reports lwjgl was updated (3.1.3 -> 3.2.3).
3. When switching to fullscreen, the vsync setting is ignored (also see #5826). By my tests, this is still happening on Windows, but not on Mac OS. This can be fixed by setting vsync again after activating fullscreen.
4. According to @mgsx-dev, Linux is not respecting the vsync setting in certain configurations. This can, however, be circumvented by using the lwjgl2 [Sync](http://forum.lwjgl.org/index.php?topic=6582.0) class.

Only number 4 may still be an issue. On our end, we could solve this by implementing the Sync class in libGDX. This would also allow us to offer a foregroundFPS-option as we did with the lwjgl2 backend.

**Closed by crykn** 2020-08-30 18:44 UTC
Labels: LWJGL3, bug

**Comment by Ktar5** [comment] 2020-09-01 02:30
@crykn I believe you're missing the main issue that I found. On a multi-monitor setup (not multi-window), where each monitor has a different refresh rate, v-sync goes wild.

**Comment by crykn** [comment] 2020-09-01 07:48
Hey @Ktar5 if you're referring to the issue that you reported in #5826, I have submitted #6150 as a fix.

**Comment by Ktar5** [comment] 2020-09-02 00:54
@crykn Not entirely sure. I'd need to test. But it didn't matter if it was multi-window.

**Comment by crykn** [comment] 2020-09-02 01:12
#6150 is not related to multi-windows, that is just the reason why the fix proposed there doesn't work.

The issue reported in #5286 was that after enabling fullscreen mode on windows, the vsync setting would be ignored.

**Comment by crykn** [comment] 2020-12-29 11:29
Just for future reference: yesterday, a user on the Discord server reported an issue which might be related:

> [...] if vsync is enabled, the game will launch in windowed mode with 60 fps, maintain 60 fps when I toggle to fullscreen, **but then drop to a stable 30 fps after switching again back to windowed.**

(Gdx version: 1.9.12, OS: Windows, Graphics card: Radeon RX 580, Forced V-Sync in the Radeon Drivers: disabled)

Disabling vsync and using `Gdx.graphics.setForegroundFps(60)` was the advised solution. However, that lead to screen tearing in fullscreen mode, so the final solution was turning vsync on only for fullscreen mode.

**Comment by Zymus** [comment] 2021-02-28 22:19
This issue is present in Windows using NVIDIA 1080Ti, with Project settings (Windows+P) set to Duplicate (but not Extend).

With Duplicate, with Swap Interval 1, 30FPS max.
With Extend, with Swap Interval 1, 60FPS max.
