### ISSUE TITLE
Example generated project fails with an assertion

### ISSUE THREAD

**Issue by matkoniecz** [libgdx/libgdx#5916] opened 2020-02-21 18:55 UTC
Please ensure you have given all the following requested information in your report.

#### Issue details
I followed this initial step https://github.com/libgdx/libgdx/wiki/A-Simple-Game and reached the end of https://github.com/libgdx/libgdx/wiki/A-Simple-Game#project-setup

Program successfully compiled and ran on the Android.

I followed https://libgdx.badlogicgames.com/documentation/gettingstarted/Packaging.html to test whatever desktop version works.

> ./gradlew desktop:dist

> Generates a fat jar in desktop/build/libs directory that you can run with

> java -jar desktop.jar

Generated jar failed with

> Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

#### Reproduction steps/code
I just followed https://github.com/libgdx/libgdx/wiki/A-Simple-Game#project-setup

Repo with generated skeleton code is at https://github.com/matkoniecz/libgdx-failed-tutorial (I just used the project generator and made 0 changes to the generated code)

#### Version of LibGDX and/or relevant dependencies
https://github.com/libgdx/libgdx/wiki/Project-Setup-Gradle appears to generate projects with LibGDX 1.9.10 (`gdxVersion = '1.9.10'`)

#### Please select the affected platforms
I was trying to run "desktop" variant on the Linux

- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

#### Full log of generated jar

```
java -jar desktop-1.0.jar 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/mateusz/Downloads/libgdx_test/desktop/build/libs/desktop-1.0.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

#### More platform info

```
mateusz@grisznak:~/Downloads/libgdx_test$ uname -a
Linux grisznak 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
mateusz@grisznak:~/Downloads/libgdx_test$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1, mixed mode, sharing)
```

### Even more

I tried to script steps leading to a crash, but for some unclear reason

`java -jar gdx-setup.jar --dir libgdxtest --name drop --package com.badlogic.drop --mainClass Drop --sdkLocation /home/mateusz/Android/Sdk` crashes

(I previously used `java -jar gdx-setup.jar` in GUI mode)

```
Executing '/home/mateusz/Downloads/libgdxtest/gradlew clean'

> Configure project :
Using already downloaded SDK: /home/mateusz/.moe/moe-sdk-1.4.0

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mateusz/Downloads/libgdxtest/build.gradle' line: 100

* What went wrong:
A problem occurred evaluating root project 'libgdxtest'.
> 'void org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(java.lang.String)'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

**Comment by PokeMMO** [comment] 2020-02-22 00:53
LWJGL2 is incompatible with OpenJDK11+ on *some* linux distros.

Either switch to LWJGL3, or OpenJDK 8, or an alternative OpenJDK distribution.

**Comment by matkoniecz** [comment] 2020-02-22 10:18
I would prefer to not downgrade system-wide Java so I will try LWJGL3 and alternative OpenJDK distribution.

As I understand I can try using OpenJDK made by an another provider - https://stackoverflow.com/a/52431765 list multiple ones, other than what is packaged for Lubuntu. I will try to do this and report back.

> switch to LWJGL3

I found https://github.com/libgdx/libgdx/issues/3673

> in your core projects dependencies, change:

> `compile "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"`

> to

> `compile "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"`

but I am worried that issue "Finish LWJGL 3 backend and request for testing" is open. Hopefully it is "final polishing is missing", not "mostly broken and unfinished"

**Comment by shatterblast** [comment] 2020-03-20 17:12
The LWJGL 3 part is fine for LWJGL 2 functionality.  Vulkan helped address this in a way.  LWJGL 3 does not fully support Vulkan, instead of the other way around.  Its base support is fine.  In Linux, I think you want Nvidia driver 340 or higher for full LWJGL 3 support on OpenGL.

**Comment by tommyettinger** [comment] 2020-03-21 01:29
Just so we're clear, LWJGL3 has Vulkan bindings but libGDX does not use Vulkan, and the above message re: Vulkan is entirely irrelevant to libGDX at this point in time. I'm not sure what prompted a mention of GPU hardware, because this error has already been resolved more than once by switching to a different OpenJDK distro. GPU drivers don't even need to be considered if you switch your JDK and stay on LWJGL2...

**Comment by shatterblast** [comment] 2020-03-21 01:56
I dis-agree.  LWJGL 3 provides better support for 2012 devices and beyond.

**Comment by tommyettinger** [comment] 2020-03-21 06:17
I'm saying that mentioning hardware doesn't matter because people have fixed this issue numerous times by changing to an OpenJDK distro that doesn't have this bug. If targeting older devices, you can distribute AdoptOpenJDK with your game, and use whatever LWJGL you currently use, and this particular error should not happen.

**Comment by shatterblast** [comment] 2020-03-21 15:23
That makes sense in a way.

**Comment by crykn** [comment] 2020-08-28 16:17
This issue is caused by a combination of LWJGL 2 and some JDKs on Linux. Since the former is no longer recommended (-> LWJGL 3) and the latter is out of our hand, I'm closing this.

**Closed by crykn** 2020-08-28 16:17 UTC
