### ISSUE TITLE
Back button on android not being catched by Gdx.input.isKeyJustPressed()

### ISSUE THREAD

**Issue by Betalord** [libgdx/libgdx#4363] opened 2016-10-12 21:49 UTC
As I said in the description of this issue, the back button on android device is not being catched by Gdx.input.isKeyJustPressed(). Instead, Gdx.input.isKeyPressed() works fine. Of course, I do Gdx.input.setCatchBackKey(true) before so that is not the problem.
I found another guy confirming this issue here:
http://gamedev.stackexchange.com/questions/104311/libgdx-why-doesnt-gdx-input-iskeyjustpressed-work
He also provides sample code how to reproduce the problem.

**Comment by xoppa** [comment] 2016-10-13 05:51
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by Betalord** [comment] 2016-10-17 14:11
I'm not sure what is missing in my post - a demo to reproduce it? In the link I provided you see the source code that causes this problem.

Anyway, let me give you an example. See this post:
http://gamedev.stackexchange.com/questions/114972/handling-back-button-in-android-without-implementing-inputprocessor/114985#114985

I'll copy paste his code, since it is exactly the same as mine but without some more advanced stuff that I used (that has nothing to do with this problem though).


```
public class MainMenuScreen implements Screen{
    //omitted unnecessary code
    @Override
    public void render(float delta) {
    if (Gdx.input.justTouched()) {
        game.setScreen(game.STS);   //Setting 2nd Screen
    } else if (Gdx.input.isKeyPressed(Keys.BACK)) {
        System.out.println("mms back");
        if(Gdx.input.isKeyJustPressed(Keys.BACK))
        Gdx.app.exit();            // Exiting   
    }
}

public class StageScreen implements Screen{
    //omitted unnecessary code
    @Override
    public void render(float delta) {
        if (Gdx.input.isKeyPressed(Keys.BACK)) {
        System.out.println("backed to mms in android");
        if(Gdx.input.isKeyJustPressed(Keys.BACK))
        game.setScreen(game.MMS);  //going back to Main screen
    }
}
```

isKeyPreesed(Keys.BACK) return true, but isKeyJustPressed(Keys.BACK) returns false in both cases. Gdx.input.setCatchBackKey(true) is set correctly (before this code is reached).

If you require any further explanation, please do tell, but you need to be more specific in what exactly you need to know, because the link you provided contains no "issue template".

**Comment by fegemo** [comment] 2016-12-17 21:10
Hi @Betalord and @xoppa, I could also reproduce this issue. Looking at [`AndroidInput.java:347`](https://github.com/libgdx/libgdx/blob/9b8f20b2d0e96e53f0f2b98dc8f6131c810aae71/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java#L347-L358), it looks like it happens when there is no InputProcessor attached. I attached a dummy InputAdapter and it worked fine.

**Comment by MrStahlfelge** [comment] 2020-08-30 12:48
Problems with isKeyJustPressed on Android are already fixed in the meantime.

**Closed by MrStahlfelge** 2020-08-30 12:48 UTC
Labels: need more info
